window.transcript = {
  "videoId": "cc4rF5dNJs0",
  "title": "Case No. 2020-0638 Master Commissioner Hearing",
  "dateString": "Streamed live on Sep 2, 2020",
  "date": "2020-09-02T00:00:00",
  "timestamps": [
    "00:00",
    "00:19",
    "00:21",
    "00:22",
    "00:24",
    "00:28",
    "00:29",
    "00:33",
    "00:35",
    "00:38",
    "00:41",
    "00:43",
    "00:44",
    "00:46",
    "00:48",
    "00:50",
    "00:52",
    "00:54",
    "00:56",
    "00:58",
    "00:59",
    "01:02",
    "01:04",
    "01:07",
    "01:09",
    "01:11",
    "01:12",
    "01:16",
    "01:17",
    "01:19",
    "01:22",
    "01:25",
    "01:28",
    "01:29",
    "01:32",
    "01:33",
    "01:37",
    "01:39",
    "01:40",
    "01:42",
    "01:44",
    "01:47",
    "01:49",
    "01:50",
    "01:52",
    "01:54",
    "01:56",
    "01:59",
    "02:00",
    "02:02",
    "02:04",
    "02:05",
    "02:09",
    "02:10",
    "02:23",
    "02:26",
    "02:27",
    "02:30",
    "02:32",
    "02:34",
    "02:36",
    "02:38",
    "02:41",
    "02:43",
    "02:45",
    "02:48",
    "02:50",
    "02:53",
    "02:55",
    "02:57",
    "03:00",
    "03:03",
    "03:04",
    "03:08",
    "03:10",
    "03:12",
    "03:13",
    "03:16",
    "03:18",
    "03:19",
    "03:22",
    "03:23",
    "03:25",
    "03:27",
    "03:30",
    "03:31",
    "03:34",
    "03:37",
    "03:37",
    "03:40",
    "03:44",
    "03:48",
    "03:50",
    "03:53",
    "03:56",
    "04:00",
    "04:02",
    "04:06",
    "04:10",
    "04:13",
    "04:14",
    "04:17",
    "04:21",
    "04:24",
    "04:25",
    "04:28",
    "04:29",
    "04:32",
    "04:37",
    "04:39",
    "04:40",
    "04:43",
    "04:44",
    "04:48",
    "04:53",
    "04:57",
    "05:00",
    "05:03",
    "05:06",
    "05:09",
    "05:11",
    "05:14",
    "05:19",
    "05:23",
    "05:25",
    "05:26",
    "05:29",
    "05:30",
    "05:32",
    "05:34",
    "05:37",
    "05:38",
    "05:42",
    "05:43",
    "05:45",
    "05:48",
    "05:49",
    "05:51",
    "05:52",
    "05:55",
    "05:56",
    "06:00",
    "06:02",
    "06:04",
    "06:06",
    "06:09",
    "06:13",
    "06:18",
    "06:20",
    "06:22",
    "06:39",
    "06:42",
    "06:44",
    "06:46",
    "06:49",
    "06:55",
    "06:56",
    "06:59",
    "07:01",
    "07:02",
    "07:03",
    "07:09",
    "07:12",
    "07:15",
    "07:18",
    "07:18",
    "07:21",
    "07:22",
    "07:25",
    "07:29",
    "07:32",
    "07:34",
    "07:35",
    "07:38",
    "07:40",
    "07:44",
    "07:46",
    "07:48",
    "07:51",
    "07:55",
    "07:58",
    "08:02",
    "08:06",
    "08:10",
    "08:14",
    "08:17",
    "08:19",
    "08:22",
    "08:24",
    "08:26",
    "08:28",
    "08:29",
    "08:31",
    "08:33",
    "08:35",
    "08:38",
    "08:41",
    "08:45",
    "08:47",
    "08:49",
    "08:53",
    "09:00",
    "09:04",
    "09:08",
    "09:10",
    "09:11",
    "09:13",
    "09:14",
    "09:16",
    "09:18",
    "09:22",
    "09:25",
    "09:26",
    "09:29",
    "09:33",
    "09:34",
    "09:38",
    "09:42",
    "09:42",
    "09:45",
    "09:46",
    "09:50",
    "09:54",
    "09:57",
    "09:58",
    "09:59",
    "10:01",
    "10:04",
    "10:06",
    "10:10",
    "10:14",
    "10:17",
    "10:21",
    "10:23",
    "10:24",
    "10:29",
    "10:32",
    "10:36",
    "10:38",
    "10:39",
    "10:41",
    "10:42",
    "10:48",
    "10:51",
    "10:54",
    "10:55",
    "10:56",
    "11:00",
    "11:01",
    "11:04",
    "11:04",
    "11:06",
    "11:07",
    "11:09",
    "11:11",
    "11:12",
    "11:18",
    "11:20",
    "11:21",
    "11:25",
    "11:28",
    "11:29",
    "11:33",
    "11:35",
    "11:37",
    "11:40",
    "11:42",
    "11:44",
    "11:46",
    "11:48",
    "11:50",
    "11:52",
    "11:54",
    "11:56",
    "12:00",
    "12:01",
    "12:04",
    "12:06",
    "12:08",
    "12:11",
    "12:14",
    "12:16",
    "12:19",
    "12:22",
    "12:23",
    "12:27",
    "12:30",
    "12:32",
    "12:34",
    "12:35",
    "13:18",
    "13:32",
    "13:36",
    "13:41",
    "13:44",
    "13:47",
    "13:48",
    "13:51",
    "13:52",
    "13:54",
    "13:56",
    "13:58",
    "13:59",
    "14:03",
    "14:07",
    "14:09",
    "14:11",
    "14:12",
    "14:16",
    "14:20",
    "14:26",
    "14:29",
    "14:31",
    "14:32",
    "14:36",
    "14:38",
    "14:47",
    "14:51",
    "14:51",
    "14:55",
    "14:57",
    "14:58",
    "15:00",
    "15:02",
    "15:05",
    "15:08",
    "15:10",
    "15:12",
    "15:14",
    "15:16",
    "15:19",
    "15:22",
    "15:23",
    "15:26",
    "15:27",
    "15:28",
    "15:31",
    "15:35",
    "15:39",
    "15:40",
    "15:43",
    "15:44",
    "15:47",
    "15:51",
    "15:52",
    "15:54",
    "15:57",
    "15:58",
    "16:00",
    "16:06",
    "16:08",
    "16:12",
    "16:15",
    "16:16",
    "16:20",
    "16:21",
    "16:24",
    "16:24",
    "16:26",
    "16:27",
    "16:28",
    "16:31",
    "16:32",
    "16:33",
    "16:34",
    "16:38",
    "16:41",
    "16:43",
    "16:45",
    "16:46",
    "16:49",
    "16:50",
    "16:53",
    "16:53",
    "16:57",
    "17:00",
    "17:04",
    "17:07",
    "17:11",
    "17:13",
    "17:15",
    "17:16",
    "17:19",
    "17:20",
    "17:24",
    "17:26",
    "17:29",
    "17:29",
    "17:33",
    "17:37",
    "17:38",
    "17:40",
    "17:43",
    "17:44",
    "17:48",
    "17:51",
    "17:52",
    "17:54",
    "17:55",
    "17:56",
    "17:58",
    "18:00",
    "18:01",
    "18:02",
    "18:04",
    "18:05",
    "18:07",
    "18:08",
    "18:11",
    "18:13",
    "18:14",
    "18:18",
    "18:25",
    "18:28",
    "18:29",
    "18:32",
    "18:33",
    "18:35",
    "18:36",
    "18:39",
    "18:41",
    "18:44",
    "18:47",
    "18:48",
    "18:52",
    "18:53",
    "18:55",
    "18:56",
    "18:59",
    "19:00",
    "19:03",
    "19:04",
    "19:07",
    "19:11",
    "19:13",
    "19:15",
    "19:17",
    "19:19",
    "19:20",
    "19:22",
    "19:23",
    "19:25",
    "19:26",
    "19:29",
    "19:32",
    "19:35",
    "19:36",
    "19:38",
    "19:40",
    "19:44",
    "19:49",
    "19:52",
    "19:53",
    "19:56",
    "20:00",
    "20:03",
    "20:04",
    "20:06",
    "20:09",
    "20:10",
    "20:12",
    "20:14",
    "20:15",
    "20:17",
    "20:18",
    "20:21",
    "20:21",
    "20:24",
    "20:25",
    "20:28",
    "20:30",
    "20:31",
    "20:32",
    "20:35",
    "20:36",
    "20:38",
    "20:41",
    "20:43",
    "20:45",
    "20:47",
    "20:49",
    "20:49",
    "20:51",
    "20:52",
    "20:54",
    "20:56",
    "20:57",
    "20:59",
    "21:03",
    "21:06",
    "21:09",
    "21:12",
    "21:13",
    "21:15",
    "21:16",
    "21:18",
    "21:21",
    "21:23",
    "21:26",
    "21:27",
    "21:29",
    "21:31",
    "21:33",
    "21:35",
    "21:37",
    "21:38",
    "21:42",
    "21:46",
    "21:51",
    "21:53",
    "21:55",
    "21:58",
    "22:02",
    "22:04",
    "22:05",
    "22:08",
    "22:10",
    "22:14",
    "22:17",
    "22:18",
    "22:20",
    "22:22",
    "22:23",
    "22:25",
    "22:26",
    "22:27",
    "22:30",
    "22:32",
    "22:33",
    "22:35",
    "22:37",
    "22:39",
    "22:40",
    "22:45",
    "22:47",
    "22:49",
    "22:51",
    "22:52",
    "22:55",
    "22:56",
    "22:58",
    "23:00",
    "23:01",
    "23:04",
    "23:08",
    "23:12",
    "23:15",
    "23:16",
    "23:19",
    "23:20",
    "23:21",
    "23:24",
    "23:25",
    "23:28",
    "23:30",
    "23:31",
    "23:32",
    "23:34",
    "23:36",
    "23:38",
    "23:40",
    "23:41",
    "23:43",
    "23:44",
    "23:48",
    "23:51",
    "23:52",
    "23:55",
    "23:56",
    "23:58",
    "23:59",
    "24:01",
    "24:03",
    "24:05",
    "24:06",
    "24:09",
    "24:10",
    "24:13",
    "24:14",
    "24:18",
    "24:21",
    "24:23",
    "24:25",
    "24:28",
    "24:31",
    "24:35",
    "24:36",
    "24:38",
    "24:41",
    "24:42",
    "24:43",
    "24:45",
    "24:48",
    "24:49",
    "24:51",
    "24:53",
    "24:55",
    "24:58",
    "25:02",
    "25:03",
    "25:07",
    "25:10",
    "25:13",
    "25:14",
    "25:16",
    "25:18",
    "25:18",
    "25:21",
    "25:22",
    "25:23",
    "25:26",
    "25:29",
    "25:30",
    "25:33",
    "25:37",
    "25:38",
    "25:43",
    "25:47",
    "25:49",
    "25:50",
    "25:53",
    "25:54",
    "25:56",
    "25:57",
    "26:01",
    "26:04",
    "26:06",
    "26:07",
    "26:10",
    "26:11",
    "26:13",
    "26:14",
    "26:15",
    "26:16",
    "26:18",
    "26:19",
    "26:22",
    "26:23",
    "26:25",
    "26:28",
    "26:29",
    "26:32",
    "26:33",
    "26:35",
    "26:37",
    "26:39",
    "26:40",
    "26:41",
    "26:43",
    "26:45",
    "26:47",
    "26:49",
    "26:50",
    "26:52",
    "26:53",
    "26:58",
    "27:01",
    "27:02",
    "27:05",
    "27:08",
    "27:10",
    "27:12",
    "27:13",
    "27:15",
    "27:18",
    "27:19",
    "27:21",
    "27:23",
    "27:26",
    "27:28",
    "27:30",
    "27:31",
    "27:33",
    "27:35",
    "27:37",
    "27:38",
    "27:40",
    "27:42",
    "27:45",
    "27:48",
    "27:51",
    "27:54",
    "27:57",
    "28:00",
    "28:03",
    "28:06",
    "28:09",
    "28:10",
    "28:12",
    "28:13",
    "28:17",
    "28:18",
    "28:21",
    "28:23",
    "28:25",
    "28:27",
    "28:29",
    "28:31",
    "28:32",
    "28:33",
    "28:36",
    "28:36",
    "28:39",
    "28:41",
    "28:43",
    "28:45",
    "28:47",
    "28:49",
    "28:52",
    "28:53",
    "28:55",
    "28:57",
    "28:59",
    "29:00",
    "29:04",
    "29:07",
    "29:08",
    "29:10",
    "29:12",
    "29:14",
    "29:16",
    "29:18",
    "29:19",
    "29:21",
    "29:24",
    "29:24",
    "29:27",
    "29:28",
    "29:30",
    "29:32",
    "29:34",
    "29:37",
    "29:38",
    "29:40",
    "29:41",
    "29:42",
    "29:44",
    "29:47",
    "29:52",
    "29:54",
    "29:55",
    "29:58",
    "29:58",
    "30:03",
    "30:06",
    "30:09",
    "30:12",
    "30:13",
    "30:16",
    "30:18",
    "30:19",
    "30:21",
    "30:22",
    "30:24",
    "30:25",
    "30:27",
    "30:29",
    "30:30",
    "30:32",
    "30:33",
    "30:34",
    "30:36",
    "30:37",
    "30:39",
    "30:41",
    "30:44",
    "30:49",
    "30:51",
    "30:52",
    "30:53",
    "30:56",
    "31:01",
    "31:02",
    "31:05",
    "31:05",
    "31:09",
    "31:13",
    "31:14",
    "31:17",
    "31:19",
    "31:20",
    "31:23",
    "31:24",
    "31:26",
    "31:27",
    "31:28",
    "31:31",
    "31:33",
    "31:35",
    "31:36",
    "31:39",
    "31:40",
    "31:43",
    "31:45",
    "31:47",
    "31:49",
    "31:51",
    "31:52",
    "31:54",
    "31:56",
    "31:59",
    "32:01",
    "32:03",
    "32:04",
    "32:06",
    "32:08",
    "32:10",
    "32:12",
    "32:13",
    "32:14",
    "32:16",
    "32:17",
    "32:20",
    "32:21",
    "32:23",
    "32:24",
    "32:26",
    "32:28",
    "32:30",
    "32:32",
    "32:34",
    "32:35",
    "32:37",
    "32:42",
    "32:43",
    "32:46",
    "33:12",
    "33:15",
    "33:17",
    "33:19",
    "33:22",
    "33:23",
    "33:27",
    "33:29",
    "33:32",
    "33:36",
    "34:00",
    "34:29",
    "34:34",
    "34:36",
    "34:37",
    "34:41",
    "34:46",
    "34:50",
    "34:54",
    "34:57",
    "34:59",
    "35:01",
    "35:03",
    "35:11",
    "35:15",
    "35:16",
    "35:20",
    "35:27",
    "35:29",
    "35:32",
    "35:36",
    "35:39",
    "35:39",
    "35:42",
    "35:44",
    "35:46",
    "35:49",
    "35:51",
    "35:54",
    "35:58",
    "35:59",
    "36:02",
    "36:04",
    "36:05",
    "36:09",
    "36:11",
    "36:13",
    "36:16",
    "36:19",
    "36:20",
    "36:23",
    "36:24",
    "36:27",
    "36:31",
    "36:32",
    "36:34",
    "36:37",
    "36:42",
    "36:45",
    "36:49",
    "36:52",
    "36:54",
    "36:54",
    "36:58",
    "37:01",
    "37:02",
    "37:05",
    "37:08",
    "37:09",
    "37:13",
    "37:16",
    "37:18",
    "37:20",
    "37:22",
    "37:24",
    "37:26",
    "37:30",
    "37:32",
    "37:35",
    "37:37",
    "37:39",
    "37:42",
    "37:43",
    "37:46",
    "37:48",
    "37:50",
    "37:56",
    "37:59",
    "38:00",
    "38:05",
    "38:08",
    "38:09",
    "38:12",
    "38:13",
    "38:16",
    "38:17",
    "38:19",
    "38:21",
    "38:25",
    "38:28",
    "38:30",
    "38:32",
    "38:34",
    "38:36",
    "38:39",
    "38:44",
    "38:48",
    "38:50",
    "39:16",
    "39:18",
    "39:30",
    "39:32",
    "39:35",
    "39:39",
    "39:40",
    "39:42",
    "39:44",
    "39:48",
    "39:52",
    "39:55",
    "39:58",
    "39:58",
    "40:01",
    "40:04",
    "40:07",
    "40:12",
    "40:16",
    "40:16",
    "40:18",
    "40:20",
    "40:24",
    "40:27",
    "40:27",
    "40:29",
    "40:30",
    "40:33",
    "40:36",
    "40:38",
    "40:39",
    "40:44",
    "40:48",
    "40:51",
    "40:52",
    "40:57",
    "41:00",
    "41:02",
    "41:04",
    "41:07",
    "41:08",
    "41:12",
    "41:15",
    "41:17",
    "41:18",
    "41:21",
    "41:22",
    "41:25",
    "41:26",
    "41:30",
    "41:34",
    "41:40",
    "42:00",
    "42:06",
    "42:27",
    "42:36",
    "42:44",
    "42:48",
    "42:55",
    "42:58",
    "42:59",
    "43:01",
    "43:07",
    "43:10",
    "43:12",
    "43:13",
    "43:15",
    "43:17",
    "43:18",
    "43:21",
    "43:23",
    "43:25",
    "43:26",
    "43:30",
    "43:33",
    "43:36",
    "43:40",
    "43:43",
    "43:47",
    "43:48",
    "43:51",
    "43:52",
    "43:54",
    "43:56",
    "43:58",
    "44:00",
    "44:02",
    "44:02",
    "44:06",
    "44:09",
    "44:11",
    "44:14",
    "44:18",
    "44:20",
    "44:21",
    "44:23",
    "44:28",
    "44:30",
    "44:32",
    "44:33",
    "44:35",
    "44:40",
    "44:44",
    "44:47",
    "44:50",
    "44:52",
    "44:54",
    "44:55",
    "44:59",
    "45:01",
    "45:03",
    "45:04",
    "45:05",
    "45:08",
    "45:12",
    "45:14",
    "45:16",
    "45:20",
    "45:21",
    "45:23",
    "45:24",
    "45:27",
    "45:28",
    "45:30",
    "45:31",
    "45:33",
    "45:35",
    "45:37",
    "45:38",
    "45:41",
    "45:41",
    "45:43",
    "45:45",
    "45:51",
    "45:53",
    "45:55",
    "45:58",
    "46:00",
    "46:01",
    "46:04",
    "46:07",
    "46:11",
    "46:12",
    "46:14",
    "46:16",
    "46:18",
    "46:21",
    "46:25",
    "46:27",
    "46:29",
    "46:34",
    "46:40",
    "46:44",
    "46:47",
    "46:54",
    "47:01",
    "47:05",
    "47:08",
    "47:12",
    "47:15",
    "47:18",
    "47:21",
    "47:23",
    "47:27",
    "47:31",
    "47:35",
    "47:38",
    "47:39",
    "47:43",
    "47:46",
    "47:52",
    "47:54",
    "47:55",
    "47:59",
    "48:27",
    "48:33",
    "48:51",
    "49:06",
    "49:28",
    "49:33",
    "51:04",
    "51:06",
    "51:08",
    "51:12",
    "51:14",
    "51:17",
    "51:19",
    "51:21",
    "51:24",
    "51:26",
    "51:27",
    "51:30",
    "51:31",
    "51:33",
    "51:34",
    "51:38",
    "51:41",
    "51:44",
    "51:48",
    "51:52",
    "51:54",
    "51:56",
    "51:59",
    "52:00",
    "52:03",
    "52:05",
    "52:07",
    "52:10",
    "52:10",
    "52:15",
    "52:17",
    "52:19",
    "52:25",
    "52:30",
    "52:32",
    "52:35",
    "52:36",
    "52:39",
    "52:41",
    "52:44",
    "52:45",
    "52:47",
    "52:49",
    "52:51",
    "52:52",
    "52:54",
    "52:57",
    "52:58",
    "53:02",
    "53:05",
    "53:08",
    "53:11",
    "53:14",
    "53:18",
    "53:22",
    "53:25",
    "53:27",
    "53:31",
    "53:34",
    "53:37",
    "53:42",
    "53:45",
    "53:47",
    "53:49",
    "53:50",
    "53:53",
    "53:57",
    "54:00",
    "54:01",
    "54:04",
    "54:06",
    "54:07",
    "54:10",
    "54:12",
    "54:13",
    "54:15",
    "54:23",
    "54:27",
    "54:31",
    "54:33",
    "54:35",
    "54:40",
    "54:43",
    "54:46",
    "54:51",
    "54:54",
    "54:59",
    "55:02",
    "55:04",
    "55:06",
    "55:08",
    "55:10",
    "55:13",
    "55:14",
    "55:17",
    "55:21",
    "55:24",
    "55:25",
    "55:28",
    "55:29",
    "55:31",
    "55:34",
    "55:36",
    "55:37",
    "55:39",
    "55:42",
    "55:43",
    "55:44",
    "55:46",
    "55:49",
    "55:52",
    "55:52",
    "55:55",
    "55:57",
    "56:01",
    "56:02",
    "56:04",
    "56:07",
    "56:10",
    "56:11",
    "56:14",
    "56:16",
    "56:20",
    "56:22",
    "56:24",
    "56:26",
    "56:29",
    "56:32",
    "56:35",
    "56:36",
    "56:37",
    "56:41",
    "56:43",
    "56:44",
    "56:47",
    "56:48",
    "56:50",
    "56:51",
    "56:53",
    "56:54",
    "56:56",
    "56:58",
    "57:01",
    "57:02",
    "57:05",
    "57:06",
    "57:08",
    "57:09",
    "57:11",
    "57:13",
    "57:14",
    "57:16",
    "57:19",
    "57:21",
    "57:25",
    "57:29",
    "57:32",
    "57:34",
    "57:38",
    "57:40",
    "57:41",
    "57:44",
    "57:48",
    "57:51",
    "57:52",
    "57:54",
    "57:56",
    "57:59",
    "58:00",
    "58:03",
    "58:04",
    "58:06",
    "58:08",
    "58:10",
    "58:13",
    "58:17",
    "58:20",
    "58:22",
    "58:24",
    "58:26",
    "58:30",
    "58:34",
    "58:37",
    "58:38",
    "58:41",
    "58:43",
    "58:45",
    "58:47",
    "58:49",
    "58:52",
    "58:53",
    "58:56",
    "58:57",
    "59:00",
    "59:04",
    "59:07",
    "59:09",
    "59:11",
    "59:14",
    "59:15",
    "59:16",
    "59:20",
    "59:22",
    "59:24",
    "59:27",
    "59:30",
    "59:32",
    "59:32",
    "59:35",
    "59:37",
    "59:39",
    "59:40",
    "59:43",
    "59:48",
    "59:50",
    "59:51",
    "59:52",
    "59:54",
    "59:56",
    "59:59",
    "60:00",
    "60:01",
    "60:04",
    "60:08",
    "60:09",
    "60:12",
    "60:12",
    "60:14",
    "60:15",
    "60:18",
    "60:19",
    "60:21",
    "60:22",
    "60:25",
    "60:27",
    "60:28",
    "60:32",
    "60:36",
    "60:41",
    "60:44",
    "60:46",
    "60:49",
    "60:49",
    "60:52",
    "60:54",
    "60:56",
    "60:58",
    "61:00",
    "61:02",
    "61:05",
    "61:06",
    "61:07",
    "61:10",
    "61:13",
    "61:16",
    "61:19",
    "61:22",
    "61:24",
    "61:26",
    "61:27",
    "61:31",
    "61:33",
    "61:34",
    "61:38",
    "61:40",
    "61:42",
    "61:44",
    "61:46",
    "61:49",
    "61:53",
    "61:57",
    "62:01",
    "62:05",
    "62:08",
    "62:12",
    "62:16",
    "62:18",
    "62:19",
    "62:22",
    "62:26",
    "62:29",
    "62:32",
    "62:36",
    "62:38",
    "62:40",
    "62:42",
    "62:44",
    "62:47",
    "62:48",
    "62:51",
    "62:53",
    "62:54",
    "62:56",
    "62:57",
    "63:01",
    "63:02",
    "63:06",
    "63:08",
    "63:09",
    "63:11",
    "63:14",
    "63:15",
    "63:17",
    "63:21",
    "63:25",
    "63:29",
    "63:32",
    "63:32",
    "63:36",
    "63:39",
    "63:41",
    "63:42",
    "63:47",
    "63:51",
    "63:52",
    "63:55",
    "63:57",
    "63:59",
    "64:02",
    "64:06",
    "64:09",
    "64:12",
    "64:13",
    "64:16",
    "64:17",
    "64:19",
    "64:20",
    "64:23",
    "64:24",
    "64:28",
    "64:31",
    "64:35",
    "64:37",
    "64:39",
    "64:41",
    "64:42",
    "64:46",
    "64:49",
    "64:50",
    "64:52",
    "64:54",
    "64:57",
    "65:00",
    "65:01",
    "65:04",
    "65:05",
    "65:07",
    "65:09",
    "65:12",
    "65:16",
    "65:20",
    "65:23",
    "65:25",
    "65:28",
    "65:31",
    "65:33",
    "65:35",
    "65:38",
    "65:41",
    "65:43",
    "65:44",
    "65:47",
    "65:48",
    "65:51",
    "65:53",
    "65:55",
    "65:58",
    "65:59",
    "66:02",
    "66:04",
    "66:05",
    "66:07",
    "66:08",
    "66:11",
    "66:12",
    "66:14",
    "66:16",
    "66:19",
    "66:21",
    "66:23",
    "66:24",
    "66:28",
    "66:30",
    "66:31",
    "66:33",
    "66:35",
    "66:37",
    "66:39",
    "66:41",
    "66:42",
    "66:44",
    "66:45",
    "66:49",
    "66:50",
    "66:53",
    "66:54",
    "66:57",
    "67:01",
    "67:06",
    "67:09",
    "67:10",
    "67:12",
    "67:14",
    "67:15",
    "67:18",
    "67:20",
    "67:23",
    "67:25",
    "67:27",
    "67:28",
    "67:32",
    "67:35",
    "67:38",
    "67:39",
    "67:40",
    "67:43",
    "67:44",
    "67:48",
    "67:50",
    "67:54",
    "67:58",
    "68:01",
    "68:05",
    "68:08",
    "68:10",
    "68:13",
    "68:16",
    "68:19",
    "68:24",
    "68:28",
    "68:31",
    "68:34",
    "68:37",
    "68:38",
    "68:40",
    "68:42",
    "68:45",
    "68:47",
    "68:50",
    "68:53",
    "68:55",
    "68:57",
    "68:58",
    "69:01",
    "69:02",
    "69:06",
    "69:08",
    "69:09",
    "69:11",
    "69:12",
    "69:16",
    "69:17",
    "69:18",
    "69:20",
    "69:21",
    "69:24",
    "69:28",
    "69:30",
    "69:32",
    "69:35",
    "69:38",
    "69:40",
    "69:43",
    "69:47",
    "69:49",
    "69:50",
    "69:52",
    "69:54",
    "69:58",
    "70:01",
    "70:02",
    "70:04",
    "70:07",
    "70:10",
    "70:14",
    "70:16",
    "70:18",
    "70:21",
    "70:24",
    "70:25",
    "70:27",
    "70:29",
    "70:33",
    "70:34",
    "70:37",
    "70:41",
    "70:44",
    "70:48",
    "70:50",
    "70:52",
    "70:56",
    "70:59",
    "71:01",
    "71:04",
    "71:07",
    "71:08",
    "71:10",
    "71:13",
    "71:17",
    "71:20",
    "71:23",
    "71:24",
    "71:27",
    "71:30",
    "71:33",
    "71:36",
    "71:38",
    "71:40",
    "71:42",
    "71:45",
    "71:46",
    "71:49",
    "71:51",
    "71:54",
    "71:57",
    "72:00",
    "72:01",
    "72:04",
    "72:05",
    "72:08",
    "72:22",
    "72:51",
    "73:01"
  ],
  "transcripts": [
    "[Music]",
    "the honorable supreme court of ohio is",
    "now an open session",
    "pursuant to adjournment master",
    "commissioner gregory matthews presiding",
    "good morning everyone uh we are here",
    "this morning in case number 2020-0638",
    "hassan mohammed",
    "petitioner versus william eckleberry",
    "seneca county sheriff respondent",
    "we are here for an evidentiary hearing",
    "on petitioner's request for rid of",
    "habeas corpus",
    "and for the record i'll note that this",
    "hearing is being conducted remotely",
    "and that it is open to the public as it",
    "is being streamed",
    "live online through a link on the",
    "court's website",
    "council would you please introduce",
    "yourselves for the record",
    "eric allen on behalf of petitioner",
    "hassan mohamed",
    "derek devine on behalf of respondent",
    "william f ecklebury seneca county",
    "sheriff",
    "thank you now it is my understanding",
    "that we have two witnesses who may be",
    "providing live",
    "testimony this morning um before we",
    "begin i want to give a brief instruction",
    "to the witnesses um before uh before we",
    "proceed",
    "um so gentlemen in a moment you will be",
    "removed from the main",
    "hearing into a virtual ra waiting room",
    "where you will be not be able to see or",
    "hear what's going on the in",
    "in this hearing while you're in those",
    "waiting rooms",
    "um i'm instructing you now not to watch",
    "the hearing while it is being streamed",
    "live online",
    "and i'm also instructing you not to",
    "communicate with each other",
    "in any way while the hearing is going on",
    "or to listen to",
    "each other's testimony before you",
    "yourself have testified",
    "um do either of you have any questions",
    "about that",
    "no sir all right thank you",
    "michael you can now move the witnesses",
    "to the waiting room",
    "thanks michael um so before we hear for",
    "from witnesses um i'll give about",
    "council an opportunity to make a brief",
    "opening statement if you would like um",
    "mr allen",
    "uh yes your honor um in looking at this",
    "case and filing the",
    "the state habeas petition i would",
    "uh mention a number of things that we",
    "hope to prove here this morning",
    "uh first the bond was set",
    "uh in this case without counsel present",
    "uh has remained at a million dollars",
    "for the time that mr hassan has been",
    "incarcerated",
    "both of his brothers will testify to his",
    "lack of a criminal record of any kind",
    "his character",
    "um where he was in 2018",
    "as the respondent has brought up uh the",
    "facts of the case",
    "which normally aren't brought up in a",
    "bond hearing but this is sort of a",
    "not a bond hearing but something",
    "different so",
    "um we believe that once you hear all the",
    "evidence that",
    "you'll find that the bond is",
    "unreasonable and and reset it",
    "accordingly thank you",
    "mr devine would you like to make an",
    "opening statement at this time",
    "yes your honor thank you um a couple of",
    "things",
    "uh first i think it's important that the",
    "this um this hearing be undertaken",
    "um uh as a review for an abuse of",
    "discretion by the trial court",
    "um the the",
    "the this proceeding should look at",
    "the the factors of under criminal 46 for",
    "this for the establishment of bond",
    "as we've indicated in our",
    "in our filings certified copies",
    "the petitioner has been indicted on four",
    "felony counts",
    "uh two uh f1s and two",
    "f twos with gun specifications",
    "um and we believe that that the nature",
    "of those charges",
    "is uh should should be a significant",
    "factor",
    "for a trial court and establishing bond",
    "and in this court's review of that bond",
    "i would also indicate that in the",
    "filings that we've",
    "we've made there there's certified",
    "copies from a",
    "a moiler case mr moyler was",
    "i indicted for aiding and abetting",
    "the petitioner in this case moiler",
    "is the person who identifies petitioner",
    "as the individual who got out of the car",
    "and fired the handgun",
    "moiler has pled guilty to two felony",
    "counts",
    "as it relates to his indictment as the",
    "aider and a better of petitioner",
    "as it relates to these proceedings",
    "we've been we've included a copy",
    "certified copy of mr",
    "moyler's judgment entry for his bond",
    "hearing",
    "and as the person who was accused of",
    "aiding in a betting",
    "petitioner his bond was set at the exact",
    "same amount",
    "as petitioners we would also",
    "um think that the evidence is going to",
    "establish",
    "that there's been no motion filed in the",
    "trial court",
    "where the evidence being presented to",
    "this court",
    "has ever been presented and we would",
    "think that",
    "that proceeding",
    "and and granting any type of relief",
    "without first giving the trial court",
    "that same opportunity",
    "would establish a precedent that",
    "um that would not be appropriate",
    "thank you thank you",
    "yeah and with that mr allen you may call",
    "your first witness",
    "oh uh ali muhammad",
    "[Music]",
    "mr muhammad i'm going to need you to",
    "display a photo id before i can",
    "administer the oath",
    "within just a moment thank you",
    "and if you would raise your right hand",
    "please do you solemnly swear or affirm",
    "the testimony you give will be the truth",
    "the whole truth and nothing but the",
    "truth",
    "yes ma'am thank you",
    "mr allen thank you um",
    "how are you related to hassan muhammad",
    "i am his older brother okay how much",
    "older are you",
    "than he is i am he was 94 so i'm four",
    "years older than him",
    "okay how how big a family do you have",
    "um we are in total six",
    "not um so i got five siblings okay",
    "and where are you from originally um",
    "originally",
    "i was born in somalia okay okay and",
    "where does your family live now",
    "they live in columbus ohio okay and",
    "hassan where where did he go to school",
    "he was going to",
    "the american institute of um i think",
    "modern technology medicine okay",
    "and what was he going to school for",
    "uh for his art degree okay okay",
    "how about high school um high school",
    "i believe he i think he went to either",
    "canal winchester or ghana okay",
    "and do you remember him ever getting",
    "into fights in school",
    "no not at all other than",
    "normal sibling issues did he ever get",
    "violent with you",
    "um nope we're just we're brothers so",
    "from time to time",
    "we pump heads here and there but he's",
    "not a violent person",
    "okay now do you ever remember him being",
    "arrested as a juvenile",
    "no about as an adult other than this",
    "than this um okay",
    "and we talked about the nursing school",
    "did he finish nursing school",
    "yeah he graduated of uh january 2017.",
    "okay",
    "what kind of person is hassan um",
    "he's a he's a kind timid individual",
    "he's uh very meticulous with his uh with",
    "his work",
    "um and he's empathetic so he definitely",
    "has a big heart",
    "okay you ever seen him with a gun or any",
    "weapon no sir",
    "okay now your your father is sick",
    "that is chris uh what's wrong with your",
    "dad",
    "um he got into an accident um",
    "october 13th of 2008 2018. he got into a",
    "very bad accident he was in a coma for",
    "about give or take three or four months",
    "okay uh simon helped take care of him at",
    "any point yes",
    "yes he did we uh we all pretty much came",
    "together at that point",
    "to uh help the family needs okay",
    "um does he help help with your mother",
    "yeah he helps um with my mom we do have",
    "a",
    "younger sibling who has down syndrome so",
    "it's a 24-hour care with him",
    "so my mom it's nearing her old age so he",
    "definitely helps out",
    "okay okay",
    "um you ever heard hassan mention a",
    "girlfriend in washington dc",
    "not to my knowledge okay",
    "ever mentioned to you with john moyler",
    "no sir",
    "okay now",
    "2000 did hassan ever live with you",
    "yeah he moved with me on um december of",
    "2017.",
    "okay and where were you living at that",
    "time",
    "where was i living i was living in",
    "pittsburgh okay",
    "and what was he doing for work um",
    "he was he was helping me out i was um i",
    "was pretty much starting my own business",
    "here",
    "so he um he finished school so",
    "he was in there um getting his like",
    "trying to finish his net nclex so he was",
    "studying",
    "i was supplying him with any financial",
    "needs that he needed",
    "um but he was a big help over here in",
    "pittsburgh for me okay and what do you",
    "do for a living",
    "um i run a home health agency okay okay",
    "you ever did he ever mentioned tiffany",
    "ohio to you",
    "no not at all",
    "did he ever mention students in tiffin",
    "ohio",
    "no no not at all okay",
    "and you had mentioned before that if you",
    "needed money you would give it to him",
    "yeah and he also um drove",
    "he did like a jitney um like an uber",
    "service so he usually",
    "usually gets money through that it's",
    "like like 100 or 200",
    "a week that he would receive so that",
    "should that was able to you know",
    "keep him above water but anything else",
    "that he needed i would i would supply",
    "okay okay do you know a uh kenneth",
    "turner",
    "yes how do you know ken turner",
    "um he's uh good friends with hassan he's",
    "the one that he was driving",
    "um to and from work um",
    "i i vaguely met him well prior to the",
    "arrest and everything i know i",
    "i know him now um but back",
    "back in the day he i usually just",
    "probably seen him once",
    "and who see he was a good guy okay",
    "do you uh remember taking a video with",
    "him",
    "do i remember taking a video with him",
    "yes yes",
    "okay i'm gonna see if i can do this",
    "so",
    "um",
    "can everybody see that",
    "i cannot i can just see the",
    "filings mr allen this is michael you're",
    "gonna need to stop",
    "sharing your screen open the video and",
    "have it staged",
    "and then you'll click on share screen",
    "again and then when you share the screen",
    "then it will give you the option to",
    "choose the video",
    "player that is open so",
    "stop sharing the screen correct okay",
    "that's the green box at the top there",
    "should be red next to it where it says",
    "stop sharing",
    "okay now open locally the video okay get",
    "it staged ready to begin",
    "okay okay now hit share screen",
    "highlight the video click on the band",
    "then at the bottom there are two boxes",
    "you want to optimize",
    "for uh optimize video for f for sharing",
    "and then share computer sound",
    "and then click share okay",
    "can you see this yes yeah i could see",
    "that",
    "yeah okay is does that look like the",
    "the video that you took with mr turner",
    "that is correct",
    "okay does that look like a fair and",
    "accurate copy of that video",
    "yes sir okay i'm gonna play this in its",
    "entirety it's about 17 minutes if that's",
    "all right",
    "okay",
    "all right uh please state your name for",
    "the record kenneth turner",
    "okay kenneth",
    "um did you know or knew a hassan",
    "muhammad",
    "yes i knew he saw muhammad he was a cool",
    "kid",
    "and you know he helped me out in the",
    "situation for my job",
    "okay um",
    "so i'm gonna ask you a series of",
    "questions okay",
    "okay um just be honest with me it's not",
    "something that",
    "um i understand that uh",
    "you didn't know muhammad and uh the next",
    "following questions i just need you to",
    "be as honest as possible of course",
    "okay good um are you aware that he was",
    "arrested",
    "yes i was aware his brother had called",
    "me like immediately after it happened",
    "okay",
    "so do you know why he was arrested",
    "i'm not specifically sure but i think",
    "the way his brother was telling me",
    "he was identified in a situation that",
    "matched his identity",
    "but was i like i guess with some other",
    "guy",
    "but i don't believe that happened",
    "because the song was with me the whole",
    "spring",
    "of 2018 and he was not in the highest",
    "because i had work and he was taking me",
    "back and forth to work that was not",
    "right",
    "okay so you knew",
    "now now you and i both know 2018 is kind",
    "of far away right",
    "yeah that's okay like a little over a",
    "year ago",
    "i want to say well then at the time you",
    "know before he was",
    "arrested i knew him like a year and some",
    "change",
    "okay okay um and you",
    "you could remember these dates how",
    "because i met her sawing in january",
    "of um",
    "2018 at uh savoy",
    "this restaurant in the strip district uh",
    "they had a new year's eve party so i met",
    "him in 2018",
    "of january and that's how long i knew",
    "him for a year in this",
    "game until he was you know so like okay",
    "so when was the last time",
    "you saw her the last time i saw the song",
    "was",
    "the ending week",
    "of march of 2019 just a few months ago",
    "actually well i'm sorry not two minutes",
    "ago but 2019",
    "a few months after the new years of 2019",
    "i've seen them like the end of",
    "the ending week of march yeah",
    "yeah and i tried calling him but his",
    "phone kept going to voicemail",
    "i've been calling him like a whole month",
    "after you know that and his phone was",
    "one of voicemail",
    "and then that's when his brother ali",
    "caught me you know and i almost got",
    "fired from my job because i know right",
    "to work",
    "so i was really pressuring him to you",
    "know debate depending on him",
    "and relying on him to come back and",
    "forth to work okay",
    "so so okay let's let's go back so you",
    "you can remember these dates because he",
    "was",
    "derived to work correct yes okay so",
    "let me ask you on march 27 2018",
    "did you see hassan yes i did see us on",
    "march 27th",
    "of 2018. he used to he picked me up in",
    "fourth",
    "he picked me up back and forth from my",
    "home to work",
    "so um i can pick up my clients and we",
    "had an arrangement with each other",
    "so yes i seen him and so do you",
    "so so so you were scheduled to work on",
    "march 27 2018",
    "yes which i believe is the weakness my",
    "client's name is charles and troll",
    "i got him for six hours a day and it was",
    "from two day",
    "2 pm to 8 pm so that was a tuesday",
    "because i got him on tuesdays",
    "wednesdays thursdays and fridays so yes",
    "and i had a song",
    "taking me to pick him up okay so so so",
    "is march 23rd a weekday or a weekend",
    "march 23rd is actually a weekday but i",
    "have my client on the 27th sorry that's",
    "not march 23rd",
    "27th yes but i mean that's still a",
    "weekday but i had my client on the 27th",
    "which was also a weekday",
    "which was a tuesday i want to say",
    "because i had anyone uh that beginning",
    "of the week",
    "yes okay so what were you wearing",
    "when you were sorry",
    "i was wearing a gray sweatshirt and a",
    "great sweatshirt",
    "both great sweatpants i don't think they",
    "have nothing to do with",
    "the incident about hassan okay gotcha",
    "um is it true like as a home health aide",
    "you have to have training yeah some sort",
    "of bad",
    "okay um and",
    "did he tell you what he did or worked as",
    "or yeah when i met her son",
    "we had an agreement to take michael to",
    "work take me back and forth to work",
    "because uber's list was more expensive",
    "so",
    "he knocked a few dollars off for me",
    "which was appreciative so",
    "back and forth trips you know him taking",
    "him back and forth to work we discussed",
    "him",
    "um taking his i want to say a nursing",
    "exam",
    "or to be his clinician's exam to become",
    "a nurse",
    "and um whenever he moved here from ohio",
    "so that's what he's putting his focus on",
    "his nursing license like he worked for",
    "uh",
    "upmc here oh okay and that's something",
    "that helped him with",
    "you know now did he work for upmc at the",
    "time or he was you're saying he's just",
    "studying like he's getting his license",
    "or no he was just studying",
    "for his nursing exam and he just moved",
    "from a higher he didn't work there again",
    "but",
    "his his working abilities was driving",
    "driving me",
    "back and forth to work and hustling you",
    "know trying to make a living",
    "on his living an innocent living because",
    "he was very delicate he was a good guy",
    "very friendly guy okay now okay so so",
    "did did he tell you uh if he",
    "oh like like he said you said that you",
    "know that he's from ohio yeah he said it",
    "was from a husband since i met him i",
    "knew him",
    "no he didn't go try because he was",
    "offered",
    "he was offered if he passed his nursing",
    "license exam he was offered 10k",
    "bonus on the spot you know if he started",
    "working with upmc",
    "so that's what his main focus was was",
    "his license so that's what he was doing",
    "other than that no he didn't go back and",
    "forth to ohio because i had work",
    "and he would take me back and forth to",
    "work okay",
    "uh okay so",
    "okay give me a second here",
    "okay because i'm a little parched myself",
    "yeah sorry you need some water we'll get",
    "you we're almost done here okay",
    "um so how how often did he say he",
    "he he um he visits ohio",
    "he didn't really say as long as i knew",
    "him he didn't ever go back",
    "so i so between new years when he moved",
    "there you said he moved there new year's",
    "or i met him new year okay so",
    "between new year's and when he was",
    "arrested",
    "did you ever had a conversation with him",
    "saying hey i'm going to ohio this",
    "weekend",
    "no he didn't like he didn't want to go",
    "back to life because he was studying for",
    "his nursing exam",
    "and besides me and him was real cool",
    "after that so we kind of vaped off each",
    "other made a connection",
    "and he was not right back and forth to",
    "work so we kind of connected",
    "and we just stayed around each other it",
    "was very friendly vibes okay",
    "so so what's hassan's height i'm 16.",
    "so i know he probably came out like to",
    "my shoulders",
    "i'm see about my shoulders so probably a",
    "little under",
    "six foot i want to say he's not he's",
    "tall but",
    "i'm tall and i'm big i'm like a giant",
    "son everybody's shorter than me",
    "and like did you know his facial",
    "complexioner",
    "he looked like me same question",
    "like honey all right so um",
    "did you ever see hassan with a gun or",
    "engaged in any",
    "criminal activities no because i'm not a",
    "criminal",
    "i don't engage engaging activities",
    "that's not my lifestyle a song whenever",
    "we hung with each other",
    "it was nothing but laughs you know great",
    "times out to eat you know he just smoked",
    "hookah and played basketball in his free",
    "time",
    "and that's that's that i don't know his",
    "before like when he moved here",
    "to pittsburgh but i know he was here he",
    "was a good dude great dude he was very",
    "fun",
    "um you know we just had our own little",
    "connection",
    "so he never said anything about hey um",
    "anything about like guns or you never",
    "notice anything in his car",
    "like did you no no he's a pretty clean",
    "guy he was kind of like you kind of",
    "remind me of like",
    "and i believe he came from like a",
    "suburban background because me myself i",
    "don't hang around",
    "nothing out of the ordinary so okay so",
    "so what",
    "what color card did did he drive i was",
    "here",
    "he drove a white impala like an older",
    "white impala",
    "okay have you ever seen him with",
    "a gold toyota no it was",
    "it was only one standard coral which was",
    "his white chevy impala",
    "okay are you sure yes okay",
    "i'm very sure i'm very 100 positive did",
    "he have a girlfriend in virginia",
    "i don't know nothing about girlfriends",
    "but i never hear",
    "in the city he was a ladies man he had a",
    "lot of ladies around him",
    "but that's not something i want to talk",
    "about that's personal okay okay",
    "i don't want to bring that one um do you",
    "know what side of town he lived in",
    "he lived on the north side he lived on",
    "the north side right by agh allegheny",
    "general hospital to be exact",
    "that's where we live okay and um",
    "kind of like to get a yeah how long did",
    "he live there",
    "since i've known him a year okay",
    "and and did you",
    "did you did he ever did you ever see him",
    "like smoke",
    "marijuana or anything like that or no",
    "like i said all you did was just smoke",
    "hookah",
    "and play basketball so so okay kind of",
    "like an athlete",
    "okay so let me explain to you what's",
    "going on here again hassana",
    "is currently being accused of committing",
    "a crime",
    "attempted murder wow",
    "now my question to you is what city did",
    "he say he's from like",
    "did he move from north ohio",
    "central or um",
    "i don't really know i'm from pittsburgh",
    "everyone knew ohio",
    "but i know he just said columbus ohio",
    "that's all i know",
    "okay so have you ever heard him talk",
    "about",
    "toledo",
    "have you ever heard him talk about ohio",
    "i've never heard him say that against",
    "her",
    "tipping i never heard of tiff in ohio",
    "and he never explained",
    "nothing to ohio and i'm not the type of",
    "guy to get in someone's personal",
    "business i let people event when they",
    "want to vent",
    "you know not ask questions of course i",
    "want to get to know you as a person but",
    "i bought a criminal past or anything he",
    "never stated anything like that but like",
    "i said as far as i knew him",
    "right we had our kind of like bromance",
    "our own you know",
    "relationship a civilized relationship so",
    "that's something i can go based off of",
    "but i know for a fact",
    "this guy didn't do no murdering no",
    "killings like he didn't come out to me",
    "like that because i don't play that i'm",
    "a certified",
    "you know nursing assistant so i don't",
    "want that around me and i have a child",
    "that i got full custody of so i can't",
    "afford anything like that for it to",
    "happen",
    "so okay as far as him being a criminal",
    "no sir",
    "okay so so",
    "so you don't see him ever committing",
    "such",
    "a crime like attempted murder no okay do",
    "you see him committing any type of fraud",
    "no anybody can commit fraud but like",
    "again like i said if he was the type of",
    "person committed fraud",
    "he wouldn't have made no range no",
    "arrangements for me to even",
    "you know scramble that change driving",
    "him driving back and forth to work so",
    "no he's not a friend trust me i know",
    "people that are frogs but he's not one",
    "he don't come off as that type of guy",
    "like see i got the wrong person i really",
    "want to tell y'all",
    "i'm a thousand percent sure that you",
    "guys have the wrong",
    "guy i was with him on the day y'all",
    "talking about him",
    "committing a crime or incident that",
    "happened he was not there",
    "okay so",
    "uh march um",
    "you said that that date",
    "you have to go into work yeah and your",
    "shift ends at 6 pm",
    "nothing's at 8. it is 3 p.m to 8 p.m",
    "yes my client has six hours",
    "so",
    "is there any way you could see him on",
    "that date",
    "going to back to ohio and then coming",
    "pick you back",
    "up not exactly i don't think so because",
    "whenever",
    "we whenever he dropped me off at work he",
    "had came from playing basketball",
    "and then he was talking for a little bit",
    "and we both was tired because",
    "i was working and he was just like well",
    "i'm just going to go to sleep and then",
    "just call me ahead of time so i could be",
    "on time to pick you up",
    "so you don't have no words so at 2 p.m",
    "he",
    "he dropped you off and he dropped you",
    "off",
    "at your client's house that you take",
    "care of yes so then",
    "you're assuming that he came back home",
    "and went to sleep and took a nap",
    "no i'm not assuming no this is what i",
    "said",
    "what i said was he i had to be working",
    "at two o'clock so he played basketball",
    "practice or basketball early in the",
    "morning you know",
    "early afternoon late afternoon",
    "and he came to pick me up about a",
    "quarter after one",
    "130 he picked me up and we went to my",
    "client's house at two",
    "so again i said when we got in the car",
    "we was talking we both",
    "we both exaggerated we were tired so",
    "whenever he dropped me off he said he",
    "was gonna go home and go back to sleep",
    "but he told me to call him ahead of time",
    "so i",
    "he's gonna be late picking me up got it",
    "so what",
    "was he paying what were you paying him",
    "to to have him drive you",
    "like fifty dollars sometimes i would",
    "just a little bit extra money",
    "but he was kind of like a friend so i'm",
    "gonna look out for him and i wanted to",
    "try to help him you know pursue his",
    "career that he went in",
    "right right so i want to show some of",
    "those podcasts okay so fifty dollars",
    "uh like fifty dollars a week or",
    "a week yeah like fifty dollars a week",
    "here",
    "okay sometimes i would add it more right",
    "so",
    "okay let me ask you this on that date",
    "now do you ever foresee that maybe he",
    "was driving some different car",
    "sir no like did he have another car that",
    "you know",
    "okay no whenever i met him you know he",
    "picked me up from work and even if",
    "when i went on a few times i met up with",
    "him you know we all be",
    "you know having fun drinking a little",
    "bit and then even walking outside you",
    "know when the",
    "when the bars closed or the hookah cafes",
    "closes he walked to his car which was a",
    "white chevy impala",
    "make sure you get their save and we will",
    "be with a couple of friends around this",
    "and that was that",
    "i never see him in any other car and",
    "even",
    "you know the gassy hungry or even when",
    "he was with me no one had a gold",
    "car i don't know okay did hus",
    "did hassan carry a wallet",
    "or have you ever seen him like if you",
    "don't have if you have to go to a",
    "drive-through",
    "yeah and a person takes out his wallet",
    "um now did he have several credit cards",
    "or",
    "how does i pay him cash if i mean if",
    "everything",
    "but if you if you try to remember if you",
    "try to um i guess going like a dunkin",
    "donuts or something",
    "yeah would he have several credit cards",
    "in his wallet or was it was cash or what",
    "was",
    "it would be cash i'd pay cash so i",
    "believe",
    "but you've never seen him with like 10",
    "different credit cards did you",
    "did you ever see him with more than one",
    "credit card in there did he ever like",
    "you know",
    "not that i know of i don't think i've",
    "ever seen with a credit card",
    "like not 10 different credit cards but",
    "no just cash",
    "okay okay uh",
    "all right that's pretty much and i don't",
    "i want to say",
    "one thing for the record i don't know",
    "the situation like i don't know the full",
    "situation",
    "or the full explanation from what's",
    "going on with him",
    "but i know that hassan was not there on",
    "the date that y'all said he was there",
    "which was what march 27th",
    "that it happened i know someone's",
    "because he was with me emperor says he's",
    "not that guy i don't know if",
    "if it's a race thing you know that still",
    "exists or whatever in this society but i",
    "know that",
    "hassan mohammed was not there he was",
    "with me taking me to work to look at my",
    "clan",
    "charles scott between 2 and 8 p.m and he",
    "dropped me off i couldn't because",
    "i'm not the type i don't want to i don't",
    "like being picked up late or i don't",
    "want to be late to anything",
    "so i know for a fact he didn't do it and",
    "i believe that in my heart a thousand",
    "and he didn't do that that man is",
    "innocent",
    "all right other questions no that's",
    "that's pretty much it thanks kenneth",
    "okay i appreciate it",
    "all right uh please state your name for",
    "the record kenneth turner",
    "okay um",
    "okay sorry about that",
    "is that uh the video that you took with",
    "mr turner",
    "yes sir does it appear altered in any",
    "way",
    "no okay did he also provide you with",
    "some records",
    "uh from his employment yes",
    "okay see if i can do this correctly",
    "okay",
    "all right",
    "all right can you see that um",
    "sort of well yeah it's loading i believe",
    "yeah i can see it now",
    "okay does that appear to be the",
    "um record that he provided you about his",
    "employment that is correct sir",
    "okay and for the record",
    "uh the video is we have listed that as",
    "exhibit one",
    "we've listed the employment records as",
    "exhibit two",
    "if you're keeping score at home okay",
    "and on that it shows that on the 27th he",
    "worked from",
    "2 to 8 p.m",
    "okay all right",
    "do you know if hassan can afford a",
    "million dollar bond",
    "um i don't know",
    "how about your family i believe my",
    "family",
    "wouldn't be able to do this as well",
    "how much money can your family raise to",
    "pay bond for mr",
    "mohammed for a song um five five",
    "thousand",
    "okay",
    "and would you be able to",
    "ensure he would appear at every court",
    "appearance yes sir",
    "he believed that he would show up to",
    "every court appearance",
    "yes he would okay",
    "uh would he abide by any conditions of",
    "the bond",
    "he would abide by all the conditions",
    "do you have any concerns that he would",
    "uh take off",
    "and leave your family owing the bond no",
    "no no no",
    "no at all",
    "and is your family willing to uh",
    "put up this money knowing that they'll",
    "have to appear for trial",
    "yes okay",
    "and miss hassan's health",
    "um how long has he been locked up",
    "um a year in some change now",
    "okay and that was in pittsburgh as well",
    "as the seneca county jail correct that",
    "is",
    "that is correct",
    "i'm sorry something just popped up on my",
    "screen all right",
    "i'm sorry",
    "if you noticed any health issues for a",
    "song",
    "while he was incarcerated yes",
    "yeah he was complaining about the uh the",
    "whole coronavirus things",
    "how um there's really not much social",
    "distancing and stuff like",
    "that um and lately he's been complaining",
    "about how he has um",
    "infection in his tooth so okay",
    "yeah other than that i feel like he's a",
    "resilient resilient man",
    "you have any concerns about his mental",
    "health um",
    "no well no not at all okay",
    "now if he was released do you think",
    "hassan is a threat to anybody",
    "no not at all okay i have no further",
    "questions",
    "the divine any cross-examination",
    "yes just a couple questions good morning",
    "mr mohammed",
    "good morning uh have you ever provided",
    "testimony in the seneca county common",
    "police court regarding",
    "this subject no this will be my first",
    "time",
    "has mr turner ever provided any",
    "testimony",
    "in the seneca county column police court",
    "well today will be the first time",
    "okay so so to your knowledge he's never",
    "he's never been to tiffin no",
    "okay no further questions thank you your",
    "honor",
    "mr allen anything further with this",
    "witness",
    "okay he can be excused",
    "thank you you're welcome sir have a nice",
    "day",
    "mr allen you can call your next witness",
    "uh ishmael muhammad",
    "mr muhammad once you unmute i'll need",
    "you to display your photo id",
    "[Music]",
    "thank you and if you would raise your",
    "right hand when you're ready",
    "do you suddenly swear or affirm the",
    "testimony you give will be the truth the",
    "whole truth and nothing but the truth",
    "i do thank you",
    "mr allen go ahead thank you um",
    "you're hassan mohammed's brother yes",
    "you're as older younger brother younger",
    "uh",
    "a year younger and uh what kind of",
    "person is he",
    "in general hassan is a very",
    "calm person timid he's very friendly",
    "and also a very determined person hard",
    "working",
    "in terms of school and things of that",
    "nature okay",
    "is he a violent person no he",
    "uh i mean throughout my life the last",
    "time",
    "i i've seen hassan ever fight was",
    "probably",
    "elementary school um throughout his life",
    "he was never a person who liked to fight",
    "more to sort of reason try to solve",
    "things through",
    "verbally dizzy on a gun or a rifle",
    "no never touched one and he",
    "he was in nursing school did you uh",
    "collect some records from the nursing",
    "school",
    "do i have some what was that yeah do you",
    "do you remember collecting some record",
    "did hassan go to",
    "school for nursing do you remember",
    "collect",
    "some records for that",
    "um yeah i don't have it uh with me at",
    "the moment but uh",
    "well i'm gonna i'm gonna show them to",
    "you here i",
    "i don't have it with me at the moment",
    "but he um he graduated from nursing",
    "school",
    "in the beginning of january",
    "okay he",
    "there we go okay uh",
    "can you see that",
    "okay",
    "can you see that",
    "try this again",
    "how about this can you see that",
    "um one it's a bit",
    "blurry there let me see",
    "yeah that's his transcript okay that",
    "appear to be the",
    "mature and accurate copy of what you",
    "received",
    "yeah that's the one i sent you okay a",
    "while back",
    "yeah he went to the american institute",
    "of alternative medicine that's",
    "and did he graduate did he graduate from",
    "there",
    "as far as you know yeah he graduated",
    "from there he uh he was actually",
    "preparing uh studying for quite some",
    "time for the uh",
    "nursing certification nclex exam",
    "okay and he began studying that",
    "uh right after he graduated and",
    "ultimately what was hassan trying to",
    "become in his life what was he trying to",
    "do for employment uh",
    "ultimately what he was trying to achieve",
    "is to become a nurse",
    "he wanted to take some time off a bit",
    "you know it's a debrief because",
    "you know nursing school can be a bit",
    "difficult but he uh",
    "ultimately wanted to become a director",
    "of nursing for his brother's home health",
    "care",
    "our brother okay",
    "and in terms of hassan being a threat to",
    "anyone do you have any concerns about",
    "him being a threat",
    "no no and",
    "your brother's been locked up for",
    "roughly 18 months",
    "do you have any uh concerns about his",
    "health",
    "uh could you repeat that part sorry the",
    "video is kind of audio's kind of lagging",
    "that's all right do you have any",
    "concerns about hassan's health",
    "since he's been incarcerated",
    "uh in in in the jail at the moment",
    "yes",
    "uh yeah i mean his concern uh when he",
    "was younger",
    "uh he always had his little heart",
    "problems",
    "um i i'm not sure if it was",
    "he got infections or younger when he was",
    "younger but he always had heart problems",
    "he would have heart palpitations and",
    "whatnot",
    "um my dad has murmurs",
    "i believe he also has that as well",
    "um one another thing he also has",
    "anxieties",
    "uh he he has anxiety he",
    "one of the things i remember in school",
    "was whenever there was a test or",
    "upcoming exam",
    "you would usually need to like probably",
    "take it",
    "alone or you know a different time",
    "period because of the",
    "anxiety during the test was so much for",
    "him um",
    "you know being jailed for that long i'm",
    "pretty sure that",
    "all those problems have you know gotten",
    "worse",
    "considering he's never been seen by",
    "actual",
    "doctor or whatnot okay",
    "uh other than what you've mentioned are",
    "there any mental health issues that",
    "you're concerned about i mean in jail i",
    "mean he's con he's been in there for",
    "almost what i don't know 13 years",
    "actually 13 months i can't remember",
    "uh he meant i mean the anxiety is",
    "worse um he you know when i talk to him",
    "he's not the same individual as he was",
    "before",
    "um he has insomnia he doesn't really",
    "sleep much",
    "um overall he's just very",
    "disease i'd say he's",
    "i don't know he's not the same person he",
    "was once before",
    "yeah okay",
    "did he ever mention a john moiler to you",
    "okay repeat that sorry the video is",
    "lagging again",
    "did you ever mention a john moiler to",
    "you",
    "um can you hear me now don't know",
    "what to do but let me interject here for",
    "a minute uh and let's go off the record",
    "um michael do you have any uh",
    "anything you can assist with here",
    "uh no greg he uh it's strictly due to",
    "his internet connection so if it",
    "hasn't uh cleared up uh the best",
    "course is for him to to dial in",
    "okay mr allen are you near the end",
    "with him how much longer are we not much",
    "longer",
    "um mr mohammed can you hear hear us",
    "right now um yeah",
    "i can't even i can't really hear much",
    "why don't we michael let's do the dial",
    "in",
    "um to wrap this up",
    "okay sounds good",
    "[Applause]",
    "[Music]",
    "are we still off the road",
    "[Music]",
    "mr",
    "[Music]",
    "we have you back in the hearing room",
    "we're off the record at this point",
    "um and mr allen is going to uh conclude",
    "his examination so let's go back on the",
    "record",
    "uh so we're back on the record uh mr",
    "mohamed had some",
    "uh technical connection issues and",
    "um does have been addressed hopefully we",
    "were able to finish",
    "his examination mr muhammad i will",
    "remind you that you",
    "are still under oath uh mr allen i'll",
    "turn it back to you",
    "thank you um mr mohammed did a son ever",
    "mention a john moiler",
    "uh never and me yeah never i never",
    "heard of a john muller about tiffin ohio",
    "going",
    "yeah never heard of tiffin before this",
    "case okay",
    "if if uh hassan was released where would",
    "he live",
    "uh he'd live in columbus uh",
    "my father went in a car crash back in",
    "october of 13th so he um",
    "of 2018 so he actually wants to spend",
    "more time with",
    "his father and is that",
    "would that be equipped for electronic",
    "monitoring or gps if the court were",
    "to impose that yes okay",
    "[Music]",
    "and",
    "what do you know if uh he would have any",
    "work",
    "if he was released is there any",
    "discussion about him",
    "having employment or anything like that",
    "um",
    "i have he would if he were to come out i",
    "mean his primary",
    "focus would probably be to continue his",
    "study",
    "i'm trying for that uh nursing",
    "certification exam the net in class exam",
    "yeah so he has a lot of books here and",
    "you want it actually yeah",
    "okay can you your family or or",
    "hassan afford a million dollar bond",
    "no what what would be a a reasonable",
    "bond that you could afford",
    "um i mean we would prefer him coming out",
    "you know with",
    "no no amount to pay since we believe",
    "he's innocent but uh",
    "if we're pushing it i'd say maybe 5 000",
    "okay that's that's if",
    "uh it were 10 percent or 10",
    "yeah okay and do you have any",
    "uh concerns that hassan would abide by",
    "the conditions of the court",
    "yeah he would he would abide by every",
    "rule set upon him",
    "okay do you have any concerns that he",
    "would be a threat to anyone no",
    "um you were present in",
    "december at the motion to suppress",
    "hearing yes",
    "do you remember me asking the judge to",
    "reduce the bond",
    "yes i do remember okay do you remember",
    "what his answer was",
    "yes he denied it and kept it as a",
    "million okay",
    "i have no further questions mr devine",
    "good morning mr mohammed good morning",
    "um have you ever testified uh",
    "or offered evidence in any manner in the",
    "seneca county common police court",
    "regarding the release of your brother",
    "uh no i have no further questions your",
    "honor thank you",
    "mr allen anything um no your honor uh",
    "this witness may be excused thank you mr",
    "mohammed for your time this morning",
    "all right thank you",
    "mr allen any additional evidence this",
    "morning to present",
    "your honor i would just ask that the uh",
    "the three exhibits that we",
    "um discussed via the live testimony be",
    "admitted",
    "the other um",
    "exhibit that we had proffered uh",
    "is is for um",
    "[Music]",
    "we just ask you to consider that as well",
    "that's just that's something that i just",
    "got so it would be difficult to get a",
    "witness to testify to that so we'd ask",
    "that you consider that as well",
    "and for the record can you just briefly",
    "explain what that other",
    "exhibit is that you're referring to i i",
    "can",
    "probably be good for the record to",
    "explain what each one is",
    "exhibit one is the video of mr turner",
    "exhibit two is mr turner's employment",
    "records",
    "exhibit three is a page and i can",
    "introduce the entire",
    "report if you wish from a police report",
    "where by the",
    "one of the victims picked out the",
    "original hussein muhammad that the",
    "tiffin police department picked up and",
    "exhibit four",
    "is mr muhammad's transcript from nursing",
    "school",
    "okay thank you um",
    "with that anything else from the",
    "petitioner this morning",
    "um other than argument now yeah we'll do",
    "argument at the end",
    "mr devine um any any uh",
    "evidence to present this morning we",
    "would rest on the evidence we've",
    "previously",
    "uh submitted via sworn affidavit from",
    "detective chandler and the certified",
    "copies",
    "from the seneca county common police",
    "court",
    "okay thank you um and obviously it's",
    "already",
    "has been alluded to just now both",
    "parties did file",
    "written evidence and some other",
    "information last week",
    "with the clerk's office under criminal",
    "rule 46",
    "f that information and the evidence in",
    "addition to what was presented this",
    "morning",
    "does not need to conform to the rules of",
    "evidence therefore the information",
    "presented",
    "this morning and the documents",
    "previously filed with the clerk are",
    "submitted for the court's consideration",
    "um and with that we'll conclude with",
    "closing arguments uh mr allen",
    "yeah sharon thank you i um i i think",
    "first we have to to start uh mr muhammad",
    "was brought back",
    "from um pittsburgh uh a bond hearing",
    "was held in front of a magistrate",
    "without counsel",
    "the bond was set at a million dollars",
    "um it should be noted in this case that",
    "uh while there was a shooting no one was",
    "hit",
    "or injured in this matter doesn't",
    "obviously excuse what occurred but",
    "there was no uh physical injury to",
    "anyone",
    "um i did request the court to reduce the",
    "bond",
    "at the conclusion of emotions to",
    "suppress hearing the second mr mohammed",
    "testified",
    "to that the judge refused to allow",
    "uh reduction in the bond um and",
    "that motionless press was sitting for",
    "about four months",
    "what is finally ruled upon we were in",
    "the middle of the pandemic",
    "mr muhammad has no prior criminal record",
    "mr muhammad has no history of violence",
    "mr muhammad would certainly abide by any",
    "conditions",
    "of the court if they were good to",
    "release him on bond",
    "i believe that both mr mohammed's",
    "testified they could probably afford a",
    "fifty thousand dollar bond",
    "i think that's more in line with a",
    "reasonable bond",
    "given the fact that here no persons were",
    "injured",
    "given that um there is some question",
    "as to the identity of mr mohammed",
    "the first person they picked up was",
    "picked out by the victim as this is the",
    "person so",
    "you know you have to wonder you know",
    "whether or not they're going to be able",
    "to get a",
    "conviction in this case mr moyler we",
    "have always argued that mr moyler was",
    "pressured into making this",
    "identification of mr muhammad",
    "so with looking at all those things and",
    "all those things that we presented both",
    "here",
    "in live testimony and via paper",
    "testimony and the video that",
    "was played for the court we would ask",
    "that you uh",
    "reduce the bond and release mr mohammed",
    "from the seneca county jail",
    "thank you and one one question for you",
    "mr allen",
    "you're asking for a reduction of the",
    "bond and is there a specific amount that",
    "you're asking the court to reduce it to",
    "i i would ask the court to reduce fifty",
    "thousand dollars with a ten percent",
    "provision",
    "um that's in line with uh his",
    "lack of a criminal history uh his",
    "ties to the community in columbus",
    "columbus is roughly an hour and a half",
    "from",
    "from tiffin which is where he'd be",
    "living um",
    "and i think that's that's far more",
    "reasonable than",
    "and that certainly would uh make sure",
    "that he would",
    "come to court and abide by any",
    "conditions if his family had to put up",
    "that amount of money",
    "okay thank you mr devine",
    "thank you your honor um",
    "mr allen had hit on criminal rule 46",
    "um and and we would agree that we're not",
    "aware of any prior convictions",
    "um we would we would strongly disagree",
    "though",
    "as it relates to the the nature of the",
    "offense",
    "the fact that nobody was hit with the",
    "bullet and injured",
    "uh does not negate in any way the",
    "alleged criminal conduct",
    "uh in this case uh the defendant is",
    "indicted on two counts of attempted",
    "murder",
    "um and then two counts of felony assault",
    "for uh the firing of a handgun",
    "into an automobile uh in in the",
    "city of tiffin uh when you look at 46",
    "c1 you look at the nature and",
    "circumstances of the crime charged",
    "and whether the defendant used right",
    "access to a weapon",
    "we have somebody who is indicted",
    "for a felony of the first degree which",
    "faces",
    "a significant period of incarceration",
    "gun specification would be a mandatory",
    "additional time",
    "so the defendant is looking at",
    "significant",
    "incarceration if he is convicted",
    "as it relates to um the identification",
    "of of the uh of the petitioner",
    "um we we agree there was an uh",
    "somebody named hassan i'm sorry hussain",
    "muhammad who was initially identified",
    "by the victim of the crime",
    "as as being the shooter the person who",
    "the state is relying on to identify the",
    "shooter",
    "is a person who was driving the car",
    "to the crime scene who saw with",
    "a person who had been part of a scam",
    "to defraud a financial institution",
    "the girlfriend of moyler",
    "gave a statement to tiffany police that",
    "she went to high school",
    "with petitioner and she's the one who",
    "actually came forward",
    "when hussein muhammad's picture was in",
    "the paper",
    "and said you got the wrong guy so our",
    "identification at trial is going to be",
    "based on",
    "the girlfriend of moyler who went to",
    "high school with",
    "petitioner and mr moyler moyler was",
    "indicted",
    "on complicity 2 charges",
    "and he pled guilty to a complicity to",
    "felonious assault",
    "and an inferior degree offense of",
    "complicity to aggravated assault",
    "and he was sentenced to a term of",
    "incarceration for his role",
    "in these crimes while",
    "i i i don't have any",
    "way to explain",
    "why tiffany police department would be",
    "pressuring",
    "mueller to identify",
    "hassan muhammad as the shooter",
    "instead of hussein muhammad as the",
    "shooter",
    "both the misidentified hussein",
    "and the uh since identified hassan",
    "are not people who the different police",
    "department has previously dealt with",
    "they're not on the radar of local law",
    "enforcement it's not like this person",
    "is a is a known um you know",
    "you know bad guy who the police uh have",
    "you know has focused on these are both",
    "um both muhammad's are are were known to",
    "be",
    "residents of franklin county and had no",
    "involvement",
    "prior to this with seneca accounting so",
    "that there's there's no",
    "there's no logical basis for tiffany",
    "police department",
    "pressuring moiler who admitted his role",
    "in the crimes",
    "readily to have him misidentify",
    "a petitioner as the person who committed",
    "the crime",
    "i think it's important for this this",
    "court to consider",
    "um the the precedent that that",
    "petitioner is is asking um he's",
    "presented",
    "evidence and testimony here today that",
    "has never been presented",
    "to the trial court judge he's asking",
    "the trial court uh judge's determination",
    "on bond",
    "to be changed or modified based on",
    "evidence",
    "uh arguments that have never been made",
    "to the trial court judge",
    "the the precedent that could be created",
    "uh would would be literally",
    "everybody incarcerated pending",
    "adjudication of criminal charges once",
    "their bond reduced",
    "this would create the precedent of of",
    "allowing everyone to not even make an",
    "argument to the trial court judge",
    "and run to the supreme court and say i",
    "want my bond reduced",
    "none of these arguments the evidence",
    "has ever been presented to the trial",
    "court judge",
    "right now we can't schedule the matter",
    "for trial",
    "because uh petitioner",
    "is currently being evaluated for a",
    "determination of his competency",
    "to stand trial and to assist counsel in",
    "that trial",
    "so we're in a holding pattern um and and",
    "i agree with mr allen uh",
    "there was a there was a motion to",
    "suppress there was a delay getting a",
    "ruling on the motion distress",
    "and then we were in the in the throes of",
    "the",
    "uh of the covet pandemic uh but the",
    "motion was filed on july one",
    "it would be my expectation if the",
    "petitioner is deemed competent",
    "that the trial court would schedule the",
    "matter for trial",
    "relatively quickly um again we're in",
    "you know we're in unchartered territory",
    "though with the",
    "the getting the evaluation done uh it's",
    "been it's been two months now",
    "waiting for a report from forensic five",
    "on the competence",
    "and i'm not sure if that's because",
    "they're waiting records",
    "or they're or they're or they're having",
    "trouble you know",
    "with whatever process but um you know",
    "we're we're waiting that determination",
    "on competence um",
    "before we can actually you know have a",
    "trial um",
    "finally the the um",
    "mr allen advocated that that",
    "petitioner has local ties we would we",
    "would disagree",
    "you know we would suggest local ties are",
    "local ties to the community where he is",
    "indicted",
    "uh that would be seneca county uh not",
    "franklin county franklin county",
    "um is is in the state of ohio but it's a",
    "significant distance",
    "and if he would violate the terms of his",
    "bond",
    "the the relative ease",
    "of a judge dealing with",
    "a bond for somebody who is in franklin",
    "county is much different than somebody",
    "who is local",
    "it also makes it much more difficult if",
    "if the court",
    "wants to monitor the person while",
    "they're on bond",
    "finally",
    "the best evidence before this court",
    "as to the appropriateness of the bond",
    "for petitioner is the bond",
    "for the driver of the car indicted for",
    "the same offenses as set forth",
    "in the certified copies that we provided",
    "was the same amount",
    "i would suggest that if",
    "if a person was the driver of the car",
    "maybe his bond could be",
    "should be less in",
    "in this case",
    "because of the circumstances mr moyler",
    "was arrested",
    "much quicker and was charged and went",
    "through the criminal justice system",
    "in 2018 and at the time he went through",
    "his bond was set at a million dollars",
    "no 10 percent when mr um",
    "muhammad petitioner comes to seneca",
    "county in 2019",
    "his bond was set at the exact same",
    "amount",
    "by the by the exact same magistrate at 1",
    "million no 10 percent",
    "based on the nature of the charges that",
    "and the and the rules of criminal",
    "procedure",
    "so we would suggest that that is the",
    "best evidence",
    "that the bond is is not an abuse of",
    "discretion",
    "because it's the exact same bond that",
    "the driver got",
    "when he was went through the court",
    "system in 2018.",
    "thank you your honor thank you",
    "mr allen i'll give you an opportunity",
    "for a brief rebuttal",
    "thank you um i think",
    "uh it it does make a difference um",
    "when you talk about the magistrate",
    "setting a bond without council president",
    "uh how he considered anything other than",
    "the um co-defendant got this bond i",
    "didn't",
    "obviously didn't consider anything about",
    "mr muhammad then he just",
    "set the bond i think this",
    "the respondent is is concerned about the",
    "court",
    "getting in the business of setting bond",
    "or being",
    "a watcher of common police court judges",
    "i think that's a great idea certainly",
    "as you look at the bail reform movement",
    "as you look at trying to reform",
    "the plea bargaining process i think more",
    "defense attorneys should do this to try",
    "and",
    "have someone look at whether or not this",
    "bond is set to make sure the person",
    "shows up and is uh not a threat to the",
    "community",
    "or this is this bond was set to enforce",
    "or force a plea in the case so",
    "i think in this case",
    "that there is little uh",
    "doubt that a million dollar bond is not",
    "something that he could afford",
    "it's not something that would um",
    "ensure his appearance at the pre-trials",
    "motion hearings and the trial",
    "and it's certainly not to ensure the",
    "safety of the community so again we",
    "would ask that you",
    "uh reduce the bond and release mr",
    "mohammed",
    "your honor your honor yes sir if my",
    "argument was was misunderstood i have no",
    "objection to the supreme court or the",
    "court of appeals",
    "looking at bond i'm suggesting that it's",
    "it's it's inappropriate",
    "for the evidence being submitted to",
    "this court was not presented to the",
    "common police court judge",
    "for his review and making a",
    "determination first",
    "uh your your it's my suggestion that",
    "that you're second guessing",
    "a trial court judge with information",
    "that was never presented to that trial",
    "court judge",
    "thank you with that",
    "uh i i believe uh we are done here this",
    "morning",
    "um my recommendation to the court will",
    "be forthcoming",
    "um and with that we stand adjourned",
    "thank you judge",
    "[Music]",
    "[Applause]",
    "you"
  ]
}