window.transcript = {
  "videoId": "EmIbtYBG5WI",
  "title": "Portrait Dedication Ceremony - Justice Terrence O'Donnell",
  "dateString": "Sep 22, 2020",
  "date": "2020-09-22T00:00:00",
  "timestamps": [
    "00:00",
    "00:02",
    "00:03",
    "00:07",
    "00:11",
    "00:13",
    "00:14",
    "00:18",
    "00:19",
    "00:21",
    "00:23",
    "00:25",
    "00:27",
    "00:29",
    "00:31",
    "00:33",
    "00:35",
    "00:38",
    "00:40",
    "00:42",
    "00:45",
    "00:46",
    "00:48",
    "00:50",
    "00:52",
    "00:54",
    "00:55",
    "00:57",
    "00:59",
    "01:00",
    "01:03",
    "01:05",
    "01:09",
    "01:11",
    "01:14",
    "01:16",
    "01:19",
    "01:21",
    "01:22",
    "01:23",
    "01:25",
    "01:28",
    "01:30",
    "01:32",
    "01:34",
    "01:36",
    "01:37",
    "01:40",
    "01:40",
    "01:42",
    "01:44",
    "01:46",
    "01:48",
    "01:50",
    "01:52",
    "01:54",
    "01:57",
    "01:58",
    "02:01",
    "02:03",
    "02:05",
    "02:09",
    "02:12",
    "02:14",
    "02:16",
    "02:19",
    "02:21",
    "02:23",
    "02:25",
    "02:27",
    "02:29",
    "02:31",
    "02:33",
    "02:35",
    "02:37",
    "02:39",
    "02:41",
    "02:44",
    "02:46",
    "02:48",
    "02:50",
    "02:54",
    "02:57",
    "02:58",
    "03:00",
    "03:04",
    "03:05",
    "03:07",
    "03:09",
    "03:11",
    "03:12",
    "03:14",
    "03:16",
    "03:18",
    "03:20",
    "03:22",
    "03:23",
    "03:25",
    "03:27",
    "03:29",
    "03:31",
    "03:33",
    "03:34",
    "03:37",
    "03:40",
    "03:41",
    "03:43",
    "03:44",
    "03:47",
    "03:48",
    "03:51",
    "03:53",
    "03:57",
    "03:58",
    "04:01",
    "04:03",
    "04:06",
    "04:09",
    "04:12",
    "04:14",
    "04:18",
    "04:21",
    "04:22",
    "04:26",
    "04:29",
    "04:30",
    "04:33",
    "04:34",
    "04:38",
    "04:42",
    "04:48",
    "04:51",
    "04:54",
    "04:57",
    "05:01",
    "05:03",
    "05:05",
    "05:09",
    "05:10",
    "05:12",
    "05:14",
    "05:17",
    "05:19",
    "05:20",
    "05:22",
    "05:24",
    "05:27",
    "05:28",
    "05:31",
    "05:33",
    "05:36",
    "05:39",
    "05:40",
    "05:42",
    "05:44",
    "05:46",
    "05:48",
    "05:50",
    "05:52",
    "05:54",
    "05:56",
    "05:59",
    "06:02",
    "06:03",
    "06:06",
    "06:07",
    "06:10",
    "06:11",
    "06:14",
    "06:15",
    "06:17",
    "06:20",
    "06:22",
    "06:23",
    "06:26",
    "06:26",
    "06:28",
    "06:30",
    "06:31",
    "06:33",
    "06:35",
    "06:37",
    "06:38",
    "06:40",
    "06:42",
    "06:45",
    "06:47",
    "06:48",
    "06:51",
    "06:52",
    "06:55",
    "06:57",
    "06:59",
    "07:00",
    "07:02",
    "07:04",
    "07:06",
    "07:08",
    "07:09",
    "07:11",
    "07:13",
    "07:16",
    "07:18",
    "07:20",
    "07:22",
    "07:23",
    "07:26",
    "07:28",
    "07:30",
    "07:31",
    "07:34",
    "07:36",
    "07:38",
    "07:40",
    "07:43",
    "07:44",
    "07:46",
    "07:48",
    "07:51",
    "07:53",
    "07:55",
    "07:56",
    "07:59",
    "08:01",
    "08:02",
    "08:05",
    "08:07",
    "08:09",
    "08:10",
    "08:13",
    "08:15",
    "08:17",
    "08:19",
    "08:22",
    "08:24",
    "08:27",
    "08:28",
    "08:31",
    "08:33",
    "08:36",
    "08:38",
    "08:40",
    "08:41",
    "08:43",
    "08:45",
    "08:47",
    "08:48",
    "08:50",
    "08:51",
    "08:54",
    "08:54",
    "08:57",
    "08:59",
    "09:01",
    "09:03",
    "09:04",
    "09:07",
    "09:09",
    "09:11",
    "09:13",
    "09:14",
    "09:17",
    "09:17",
    "09:19",
    "09:22",
    "09:23",
    "09:27",
    "09:29",
    "09:31",
    "09:33",
    "09:35",
    "09:38",
    "09:41",
    "09:42",
    "09:45",
    "09:46",
    "09:48",
    "09:49",
    "09:51",
    "09:53",
    "09:54",
    "09:57",
    "09:58",
    "10:02",
    "10:05",
    "10:07",
    "10:10",
    "10:11",
    "10:14",
    "10:15",
    "10:17",
    "10:19",
    "10:22",
    "10:23",
    "10:26",
    "10:28",
    "10:29",
    "10:31",
    "10:33",
    "10:37",
    "10:39",
    "10:41",
    "10:42",
    "10:44",
    "10:46",
    "11:18",
    "11:22",
    "11:33",
    "11:35",
    "11:36",
    "11:38",
    "11:39",
    "11:41",
    "11:42",
    "11:45",
    "11:46",
    "11:49",
    "11:50",
    "11:53",
    "11:54",
    "11:56",
    "11:58",
    "11:59",
    "12:03",
    "12:05",
    "12:07",
    "12:10",
    "12:12",
    "12:14",
    "12:15",
    "12:17",
    "12:19",
    "12:22",
    "12:24",
    "12:25",
    "12:28",
    "12:29",
    "12:32",
    "12:35",
    "12:37",
    "12:40",
    "12:41",
    "12:44",
    "12:44",
    "12:48",
    "12:52",
    "12:54",
    "12:56",
    "12:59",
    "13:00",
    "13:01",
    "13:04",
    "13:05",
    "13:07",
    "13:08",
    "13:10",
    "13:13",
    "13:14",
    "13:17",
    "13:19",
    "13:21",
    "13:25",
    "13:25",
    "13:28",
    "13:29",
    "13:32",
    "13:34",
    "13:36",
    "13:37",
    "13:39",
    "13:41",
    "13:44",
    "13:46",
    "13:49",
    "13:50",
    "13:53",
    "13:55",
    "13:57",
    "14:00",
    "14:02",
    "14:04",
    "14:07",
    "14:08",
    "14:13",
    "14:16",
    "14:17",
    "14:19",
    "14:20",
    "14:22",
    "14:24",
    "14:28",
    "14:30",
    "14:32",
    "14:34",
    "14:35",
    "14:37",
    "14:38",
    "14:40",
    "14:42",
    "14:45",
    "14:46",
    "14:50",
    "14:52",
    "14:54",
    "14:57",
    "15:00",
    "15:02",
    "15:05",
    "15:06",
    "15:08",
    "15:10",
    "15:13",
    "15:15",
    "15:18",
    "15:20",
    "15:23",
    "15:27",
    "15:29",
    "15:30",
    "15:33",
    "15:34",
    "15:36",
    "15:38",
    "15:40",
    "15:42",
    "15:43",
    "15:45",
    "15:48",
    "15:51",
    "15:53",
    "15:55",
    "15:59",
    "16:01",
    "16:04",
    "16:06",
    "16:08",
    "16:10",
    "16:12",
    "16:14",
    "16:17",
    "16:19",
    "16:22",
    "16:23",
    "16:26",
    "16:27",
    "16:29",
    "16:31",
    "16:33",
    "16:34",
    "16:36",
    "16:39",
    "16:42",
    "16:45",
    "16:46",
    "16:48",
    "16:50",
    "16:53",
    "16:55",
    "16:57",
    "16:59",
    "17:02",
    "17:05",
    "17:07",
    "17:11",
    "17:13",
    "17:15",
    "17:19",
    "17:21",
    "17:24",
    "17:28",
    "17:31",
    "17:34",
    "17:38",
    "17:40",
    "17:43",
    "17:46",
    "17:48",
    "17:49",
    "17:54",
    "17:56",
    "17:57",
    "17:59",
    "18:01",
    "18:03",
    "18:05",
    "18:06",
    "18:08",
    "18:11",
    "18:13",
    "18:15",
    "18:15"
  ],
  "transcripts": [
    "hear ye hear ye the honorable supreme",
    "court of ohio is now an open session",
    "pursuant to adjournment",
    "you may be seated good morning everyone",
    "welcome to the portrait dedication for",
    "terence o'donnell",
    "the 140 justice of the supreme court of",
    "ohio",
    "as you can see we're doing things much",
    "differently for this portrait dedication",
    "than we've done in the past and of",
    "course that is due to our current global",
    "pandemic",
    "during a normal time the courtroom would",
    "be filled and justice o'donnell",
    "along with friends family and colleagues",
    "would be here in the courtroom with me",
    "knowing him as i do we'd be listening to",
    "the cleveland pipe and drum corps",
    "pipe us in with their bagpipes wearing",
    "kilts",
    "but current social distancing rules make",
    "that impossible i'm afraid",
    "in his absence three of his children and",
    "three of his grandchildren are here with",
    "us today to help",
    "unveil the portrait and i'm grateful",
    "that the o'donnell name is well",
    "represented",
    "unveiling ceremony the unveiling",
    "ceremony we're holding today is of huge",
    "importance terry was an incredible force",
    "on the court for 15 years",
    "he joined the court a few months after i",
    "did in 2003.",
    "looking back i'm sure tod as i call him",
    "would agree that it was a very special",
    "error",
    "i'm referring to the incredible",
    "experience of working with the late",
    "chief justice tom moyer",
    "we saw firsthand firsthand how humble",
    "and accessible tom was",
    "what a mild-mannered chief could",
    "accomplish because he had an incredible",
    "ability",
    "to work with people the moyer court was",
    "collegial",
    "and while we worked hard we also enjoyed",
    "socializing on tuesday evenings with",
    "group dinners",
    "while chief justice moyer created the",
    "supreme court's commission on",
    "professionalism it was terry who not",
    "only served on the commission",
    "but also tirelessly supported its work",
    "he was instrumental in the creation of",
    "the lawyer to lawyer mentoring program",
    "it was one of the most impressive",
    "mentoring programs in the nation",
    "it began in 2006 as a pilot and became a",
    "permanent program in 2008",
    "pairing experienced lawyers with newly",
    "minted attorneys for one year",
    "helping with the transition from law",
    "school to practicing attorney",
    "it's an excellent program that not only",
    "benefits the new lawyer",
    "but the mentors say they learn and grow",
    "along with their mentees",
    "that is a legacy that justice o'donnell",
    "should be very very proud of",
    "justice o'donnell has also had the",
    "unique distinction of having worked on",
    "in all three buildings that have been",
    "the home of the",
    "supreme court of ohio when he was amir",
    "spratt he clerked for justice corrigan",
    "when the court was housed in the ohio",
    "state house",
    "annex our former site up until 2004",
    "was the third floor of the rhodes tower",
    "and here",
    "in the thomas j moyer ohio judicial",
    "center which we've occupied since 2004.",
    "justice o'donnell also served as",
    "chairman of the ohio legal rights",
    "services commission which oversees the",
    "protection and advocacy",
    "of the developmentally disabled and",
    "mentally ill statewide",
    "he was a past member of the board of",
    "trustees of our lady of the wayside",
    "a non-profit organization dedicated to",
    "serving the needs of the mentally and",
    "physically challenged",
    "where his brother john o'donnell lived",
    "for 10 years until he passed away in",
    "2011.",
    "one of his most notable accomplishments",
    "is his position of director emeritus of",
    "the st",
    "patrick's day parade in cleveland rain",
    "sleet or snow couldn't stop terry or the",
    "parade",
    "justice o'donnell is a man who is",
    "devoted to his family",
    "his profession his community his",
    "heritage",
    "and his religion now it is my pleasure",
    "to introduce father hugh",
    "mcgigan he is the pastor of our lady of",
    "light",
    "community in fort myers florida he will",
    "deliver this morning's invocation",
    "good morning it is a great pleasure that",
    "i come before you this day",
    "to give this invocation and honor our",
    "very good friend",
    "justice o'donnell who asked this",
    "of us this day that we come before our",
    "god",
    "and we pray his blessing",
    "almighty ever-living god whose hand lies",
    "every human heart",
    "and the rights of your people look we",
    "favor",
    "we pray on justice o'donnell",
    "today who governed with this body",
    "and governed with authority we pray",
    "that your people who prospered",
    "under his leadership he assured each and",
    "every one of us our peace",
    "and our freedoms may your gift",
    "come upon him this day dear lord in",
    "security",
    "in your name we pray thank you father",
    "i also have the honor today of",
    "introducing former justice and current",
    "speaker of the house robert cupp who",
    "will deliver brief remarks",
    "it is an honor for me to offer a few",
    "remarks",
    "for the dedication of justice terrence",
    "o'donnell's supreme court portrait",
    "today and because justice o'donnell",
    "values brevity",
    "he has allotted to me just a few minutes",
    "to offer observations and",
    "so i will be concise justice o'donnell",
    "cherished being a judge and the work of",
    "a judge",
    "it has been his element his passion his",
    "professional calling",
    "nearly 16 years of service on ohio's",
    "highest court",
    "was informed by prior 14 years as a",
    "common police trial",
    "court judge eight years as a district",
    "court of appeals judge",
    "and a keen legal mind he set an example",
    "as an exemplary jurist who not only",
    "honored",
    "the separation of powers enshrined in",
    "the three-branch structure",
    "of our state and national constitutions",
    "in theory",
    "but faithfully observed it in practice",
    "in his decisions",
    "and written opinions justice donald also",
    "had a passion to instill",
    "greater public respect for the legal",
    "profession",
    "as an essential and noble calling",
    "ultimately",
    "this led to the creation of the supreme",
    "court's lawyer to lawyer mentoring",
    "program",
    "pairing experienced lawyers with newly",
    "admitted lawyers",
    "as a way of passing on the best legal",
    "practices",
    "and the highest ethical standards to",
    "succeeding generations of lawyers",
    "justice o'donnell's dedicated work in",
    "this resulted in the program being",
    "recognized",
    "as one of the best in the nation his",
    "respect for tradition",
    "is illustrated by an item he kept in his",
    "supreme court chambers",
    "at the beginning of his legal career",
    "terry o'donnell",
    "worked as a law clerk for then justice",
    "j.j p corrigan",
    "who served as a mentor to him and was a",
    "continued influence throughout his",
    "career",
    "justice o'donnell was able to later",
    "acquire the now",
    "antique desk of his mentor and it held a",
    "place of honor in his chambers",
    "and served as a treasured inspiration",
    "with justice o'donnell would explain to",
    "those",
    "who visit his chambers as a colleague",
    "terry could not have been more welcoming",
    "and helpful to me",
    "when i arrived as a new member of the",
    "court always proactively checking to see",
    "that i knew what i should know",
    "about the workings of the court its",
    "protocols etiquette",
    "and informal expectations willingly",
    "sharing",
    "techniques he had used for years to get",
    "through massive stacks of briefs",
    "and opinion drafts he was himself a",
    "wonderful mentor",
    "as a supreme court justice i would",
    "sometimes study",
    "the portraits of former justices that",
    "were displayed in the hallways and rooms",
    "of the court",
    "and i noted the variations in the old",
    "justice's physical features",
    "hairstyles clothes and facial",
    "expressions",
    "and i often wondered what in life their",
    "personalities",
    "were like but through their likeness",
    "frozen in time alone",
    "one cannot know so here are a few things",
    "that posterity should know",
    "about the real life justice o'donnell's",
    "personality",
    "first of course he looks like a judge",
    "right out of central casting",
    "white hair gleaming eyes that are",
    "perceptive and knowing",
    "and a facial expression serious and",
    "thoughtful",
    "when on the bench or pondering weighty",
    "legal questions",
    "that would be justice o'donnell but",
    "there is more",
    "when he was not immersed in serious",
    "contemplation or",
    "writing an opinion or dissent he was",
    "friendly",
    "and outgoing and jovial he would make a",
    "point of greeting court staff",
    "no matter if he was headed to a court",
    "meeting in mid-conversation with another",
    "justice",
    "walking with his own staff or escorting",
    "a guest around the court",
    "and even when the conversation was",
    "serious he could lighten the room with a",
    "well-placed",
    "good-natured quip which he enjoyed",
    "telling",
    "and during our years on the court",
    "together we often traveled the state and",
    "attended the same meetings",
    "or events and when he speaks to a group",
    "there is always an urgency in his voice",
    "that draws the listener in",
    "whether explaining how the court decides",
    "to accept the case for review",
    "or how he views the role of a judge or",
    "the limits of judicial authority",
    "and then with an irish twinkle in his",
    "eye a broad smile on his face and yes",
    "his",
    "white judicial hair gleaming he would",
    "relate a humorous story and have",
    "everyone laughing",
    "and enjoying a fun laugh a hard act to",
    "follow",
    "for sure and that would also be justice",
    "o'donnell",
    "friend mentor conversationalist",
    "highly capable and worthy lawyer judge",
    "and supreme court justice",
    "justice terrence o'donnell may your",
    "portrait",
    "as the 149th justice of the supreme",
    "court of ohio",
    "continue to honor your significant",
    "contributions",
    "to the great body of ohio law and to the",
    "history",
    "of this great court",
    "thank you speaker cup at this time i'm",
    "going to invite",
    "the three children of justice o'donnell",
    "who are here today terence",
    "jr judge colleen o'donnell and norah",
    "o'donnell to come forward",
    "we also have with us terence's children",
    "terence iii",
    "charlie and claire and they will come up",
    "as well",
    "to unveil the portrait",
    "[Applause]",
    "thank you thank you all",
    "it's now my distinct honor to introduce",
    "justice",
    "terry o'donnell who will share a few",
    "remarks",
    "it is a distinct privilege to be able to",
    "present a portrait",
    "to the ohio supreme court albeit by",
    "recording",
    "due to the culvert 19 pandemic i still",
    "consider it",
    "a rare privilege and the opportunity to",
    "do so",
    "only being afforded to members who have",
    "served as justices",
    "on the supreme court of the state of",
    "ohio i had that privilege really due to",
    "the volunteer efforts of hundreds of",
    "people across the state of ohio",
    "to help me win elections so i could",
    "maintain my service on the court",
    "i'm indebted to judges all across the",
    "state of ohio",
    "and public officials especially people",
    "like governor bob taft",
    "and brian hicks his chief of staff",
    "bob bennett chairman of the ohio",
    "republican party",
    "joanne davidson cares and a host of",
    "others",
    "all of whom helped me earn this position",
    "on the court",
    "i am so proud to have had the",
    "opportunity to work with chief justice",
    "tom moyer",
    "tom served as chief for the supreme",
    "court",
    "for a period of 24 years he was humble",
    "he was powerful and he was quiet",
    "tom knew how to get things done he was",
    "an effective",
    "tourist judges from all over the state",
    "would come to him with problems or",
    "issues",
    "and he would carefully listen and make a",
    "decision",
    "they'd leave knowing that they had their",
    "case heard",
    "their problem resolved and they all",
    "trusted what tom would do",
    "in resolving issues that would come",
    "before him as chief justice",
    "i learned a lot from tom he didn't even",
    "know he was a teacher",
    "but i've tried to emulate both his",
    "temperament",
    "and demeanor in the service that i've",
    "afforded",
    "as a member of the supreme court i'm",
    "grateful today to father hugh mcquikman",
    "from our lady of light parish in estero",
    "florida",
    "father i want to thank you for your very",
    "kind words uh",
    "offered today in the uh invitation and",
    "benediction",
    "then two i had the opportunity of",
    "serving with then justice",
    "bob cupp who is now seeker of the house",
    "of representatives",
    "one day bob will have the opportunity to",
    "present a portrait to this court",
    "and a unique opportunity to present one",
    "to the house of representatives",
    "due to his legislative role bob is a",
    "competent",
    "uh public servant and his integrity",
    "and judgment and patience will serve him",
    "well",
    "in his role as speaker of the house of",
    "representatives",
    "i'm also very grateful that bob decided",
    "not to tell the whole truth",
    "in his comments made this afternoon",
    "i'm grateful to all my colleagues on the",
    "supreme court",
    "and for the opportunities i've had to",
    "share and exchange",
    "ideas and views on various cases over",
    "the years",
    "i'm especially grateful to chief justice",
    "o'connor",
    "with whom i've spent all of my 16 years",
    "on the supreme court",
    "chief thanks for all the memories",
    "today would not be possible without the",
    "talents of leslie adams",
    "who has done a tremendous job",
    "in presenting this portrait a likeness",
    "which i'm not sure is",
    "is really deserving finally i want to",
    "comment about",
    "ann schlatter and was my assistant when",
    "i first came on the court",
    "in 2003 and stayed with me right to the",
    "end",
    "for 16 years ann took care of all the",
    "problems that arose in her office",
    "and she made every day a great one thank",
    "you ann for all your efforts",
    "mary beth o'donnell is a long-suffering",
    "wife",
    "i'm grateful to her to terrance michael",
    "colleen and norah",
    "and to my brother michael and his family",
    "for all the support they gave me for all",
    "of those years",
    "so i know they were happy when i was",
    "leaving to go to columbus",
    "because it gave them a few days to catch",
    "up without me",
    "getting in the way i want to thank",
    "everyone in ohio for the privilege i had",
    "to serve on the ohio supreme court",
    "i've i've got many treasured memories",
    "and i'm very honored to have had the",
    "privilege of serving",
    "but the last chapter isn't yet written",
    "you see my son michael is a partner at",
    "ross mcdowell in cleveland ohio",
    "and he engineered a position for me as",
    "health counsel",
    "where i'm doing advocacy for those",
    "arguing cases in the court of appeals",
    "and supreme court and also arbitrating",
    "and media",
    "mediating cases for lawyers all around",
    "the state of ohio",
    "so i want to thank everyone for the",
    "opportunity to present these remarks",
    "this afternoon",
    "i want to especially thank stephanie",
    "hess who has coordinated",
    "all of the speakers and all of the",
    "logistics in making today possible",
    "i'm very grateful for the opportunities",
    "afforded to me",
    "i'm grateful for having a terrific",
    "judicial career in the state of ohio",
    "spanning more than 38 years i wish you",
    "all god's speed",
    "may god bless each and every one of you",
    "in all of your endeavors",
    "as he has blessed me and my family thank",
    "you all very much",
    "thank you cherry now father will you",
    "please deliver the benediction",
    "and for our prayer of benediction this",
    "day",
    "i'd ask us all now to bow our heads",
    "as an irish tradition we will pray the",
    "irish blessing upon you this day",
    "justice o'donnell as you ride now off",
    "into the sunset",
    "may the lord come and meet you",
    "may the wind be always at your back",
    "may the sun continue to shine warmly on",
    "your face",
    "until we meet again dear lord",
    "may god hold you terry in the palm of",
    "his hand",
    "as father son and holy spirit amen",
    "thank you father this concludes our",
    "program",
    "thank you all for watching those in the",
    "courtroom thank you for attending",
    "and thank you to the o'donnell family",
    "for being here during this very special",
    "occasion",
    "marshall will you please adjourn court",
    "all rise",
    "hear ye hear ye hear ye this open",
    "session of the honorable supreme court",
    "of ohio",
    "now stands adjourned"
  ]
}