window.transcript = {
  "videoId": "JEkDazi9HPY",
  "title": "Ohio on Trial: Mapp v. Ohio",
  "dateString": "Nov 18, 2020",
  "date": "2020-11-18T00:00:00",
  "timestamps": [
    "00:12",
    "00:15",
    "00:18",
    "00:19",
    "00:20",
    "00:23",
    "00:24",
    "00:26",
    "00:27",
    "00:29",
    "00:31",
    "00:32",
    "00:35",
    "00:35",
    "00:38",
    "00:41",
    "00:42",
    "00:45",
    "00:47",
    "00:49",
    "00:51",
    "00:53",
    "00:55",
    "00:58",
    "00:59",
    "01:01",
    "01:03",
    "01:06",
    "01:08",
    "01:09",
    "01:11",
    "01:12",
    "01:14",
    "01:15",
    "01:17",
    "01:19",
    "01:22",
    "01:24",
    "01:26",
    "01:27",
    "01:30",
    "01:32",
    "01:33",
    "01:35",
    "01:36",
    "01:38",
    "01:41",
    "01:44",
    "01:44",
    "01:46",
    "01:48",
    "01:50",
    "01:51",
    "01:53",
    "01:56",
    "01:57",
    "01:58",
    "02:00",
    "02:02",
    "02:03",
    "02:05",
    "02:06",
    "02:08",
    "02:10",
    "02:13",
    "02:14",
    "02:15",
    "02:18",
    "02:20",
    "02:33",
    "02:36",
    "02:37",
    "02:40",
    "02:41",
    "02:44",
    "02:48",
    "02:51",
    "02:52",
    "02:54",
    "02:56",
    "02:58",
    "03:01",
    "03:02",
    "03:04",
    "03:06",
    "03:08",
    "03:09",
    "03:11",
    "03:13",
    "03:15",
    "03:17",
    "03:19",
    "03:20",
    "03:22",
    "03:24",
    "03:26",
    "03:28",
    "03:29",
    "03:32",
    "03:33",
    "03:35",
    "03:37",
    "03:38",
    "03:40",
    "03:41",
    "03:43",
    "03:45",
    "03:46",
    "03:48",
    "03:50",
    "03:51",
    "03:52",
    "03:54",
    "03:56",
    "03:57",
    "03:59",
    "04:01",
    "04:03",
    "04:05",
    "04:07",
    "04:08",
    "04:09",
    "04:11",
    "04:12",
    "04:14",
    "04:16",
    "04:17",
    "04:21",
    "04:24",
    "04:26",
    "04:28",
    "04:30",
    "04:32",
    "04:34",
    "04:37",
    "04:39",
    "04:40",
    "04:41",
    "04:43",
    "04:45",
    "04:46",
    "04:48",
    "04:49",
    "04:51",
    "04:52",
    "04:54",
    "04:55",
    "04:57",
    "04:59",
    "05:01",
    "05:03",
    "05:04",
    "05:05",
    "05:07",
    "05:09",
    "05:11",
    "05:12",
    "05:14",
    "05:16",
    "05:18",
    "05:21",
    "05:22",
    "05:25",
    "05:26",
    "05:29",
    "05:30",
    "05:34",
    "05:38",
    "05:41",
    "05:43",
    "05:45",
    "05:47",
    "05:48",
    "05:50",
    "05:51",
    "05:53",
    "05:55",
    "05:56",
    "05:58",
    "06:00",
    "06:02",
    "06:03",
    "06:05",
    "06:06",
    "06:07",
    "06:09",
    "06:10",
    "06:12",
    "06:14",
    "06:16",
    "06:18",
    "06:20",
    "06:21",
    "06:23",
    "06:25",
    "06:27",
    "06:29",
    "06:30",
    "06:32",
    "06:34",
    "06:35",
    "06:36",
    "06:38",
    "06:40",
    "06:41",
    "06:43",
    "06:45",
    "06:46",
    "06:48",
    "06:49",
    "06:51",
    "06:53",
    "06:55",
    "07:00",
    "07:02",
    "07:03",
    "07:05",
    "07:07",
    "07:08",
    "07:11",
    "07:12",
    "07:13",
    "07:15",
    "07:17",
    "07:18",
    "07:20",
    "07:22",
    "07:23",
    "07:25",
    "07:27",
    "07:29",
    "07:30",
    "07:32",
    "07:34",
    "07:36",
    "07:36",
    "07:38",
    "07:40",
    "07:41",
    "07:42",
    "07:45",
    "07:47",
    "07:48",
    "07:51",
    "07:55",
    "07:57",
    "07:59",
    "08:01",
    "08:03",
    "08:03",
    "08:06",
    "08:07",
    "08:09",
    "08:11",
    "08:12",
    "08:13",
    "08:15",
    "08:16",
    "08:18",
    "08:20",
    "08:22",
    "08:26",
    "08:28",
    "08:29",
    "08:32",
    "08:33",
    "08:35",
    "08:37",
    "08:38",
    "08:40",
    "08:42",
    "08:44",
    "08:46",
    "08:48",
    "08:48",
    "08:51",
    "08:52",
    "08:55",
    "08:56",
    "08:57",
    "08:59",
    "09:00",
    "09:01",
    "09:03",
    "09:05",
    "09:07",
    "09:09",
    "09:13",
    "09:15",
    "09:16",
    "09:18",
    "09:20",
    "09:22",
    "09:23",
    "09:25",
    "09:26",
    "09:27",
    "09:42",
    "09:48",
    "09:51",
    "10:00"
  ],
  "transcripts": [
    "cleveland in the 1950s",
    "like a lot of cities had a numbers game",
    "this is now what we think of as like the",
    "ohio lottery",
    "people playing numbers every day hoping",
    "to",
    "pick the right numbers and get a payout",
    "but it was illegal",
    "the lottery was illegal and so it was",
    "really organized crime figures who were",
    "running",
    "daily policy or numbers games around the",
    "city",
    "local organized crime figures had very",
    "elaborate networks of people who would",
    "collect your numbers",
    "every day and figure out who who won and",
    "do payouts and of course take",
    "a cut of the winning so all of that that",
    "the policy game the numbers racket",
    "is being run by organized crime figures",
    "in cleveland throughout the 1950s",
    "and the police had particular units that",
    "were",
    "trying particularly to catch the guys",
    "running the numbers racket",
    "[Music]",
    "shondor burns had been running the",
    "numbers game and then ended up in prison",
    "for a couple years when he got back out",
    "of prison",
    "he wanted to start getting his cut of",
    "the numbers game again",
    "and he went to don king and the other",
    "guys running the numbers game and",
    "demanded his weekly payments",
    "so don king started paying him but",
    "eventually thought you know i'm sick of",
    "kicking back to shondura burns i think",
    "i'm going to run my own numbers game",
    "and he he quit paying shondor burns not",
    "long after that",
    "in 1957 a bomb goes off on the front",
    "porch of his house",
    "and don king believes that this is",
    "shondura burns sending him a message",
    "carl de lau is a cleveland police",
    "detective",
    "he is charged with enforcing the vice",
    "laws the anti-gambling laws",
    "he is very familiar with shondura burns",
    "and don king and the other",
    "people in the cleveland underworld",
    "ordinarily these kind of organized crime",
    "figures aren't giving a lot of",
    "information to the police",
    "but don king explains what went on and",
    "he said i think it was shondor burns",
    "he's the one who set this bomb on my",
    "house and he gives them a number of",
    "names",
    "including virgil ogletree virgil",
    "ogletree was a boxer in cleveland",
    "possibly connected to shondor burns and",
    "don king says",
    "you want to go find ogletree i think he",
    "was involved in this and the police",
    "develop information that ogletree may be",
    "staying at doll remap's house",
    "the police officers claimed that they",
    "were informed",
    "that there were some paraphernalia for",
    "the numbers game",
    "in the house and they were also informed",
    "that a person wanted for",
    "questioning in a bombing was in the",
    "house",
    "the remap was connected with a lot of",
    "figures in the boxing world and some of",
    "those figures were also connected to",
    "organized crime they were sometimes used",
    "as like the muscle for some of the",
    "organized crime figures",
    "in cleveland and she also owned a home",
    "in shaker heights and she would rent out",
    "some rooms in that house",
    "and sometimes she'd be renting out rooms",
    "to some of these boxers or maybe other",
    "people involved in the numbers racket",
    "the police arrive at doll remaps house",
    "this is a couple days after the bombing",
    "so it's not like an emergency or",
    "something they don't think there",
    "is a bomb in the house they knock on the",
    "door it's early afternoon",
    "and they want to come in and look for",
    "ogletree",
    "but dollerymap says no i don't want you",
    "to come in do you have a warrant",
    "they don't have a warrant so she does",
    "what every defense lawyer today would",
    "dream of which is",
    "she actually calls her lawyers it's",
    "remarkable she's a young",
    "african-american woman in cleveland",
    "owning her own home she has a daughter",
    "she's running her boarding house",
    "and she won't let the police in she's",
    "demanding to see a warrant and they",
    "don't have a warrant it's worth noting",
    "that",
    "it wasn't an emergency situation there",
    "wasn't really any reason for carl de lau",
    "not to go get a search warrant to enter",
    "her house it's really just that",
    "they didn't get search warrants very",
    "often back then eventually later in the",
    "afternoon the police break into the",
    "house and she immediately demands to see",
    "a warrant",
    "so the police hold up a piece of paper",
    "and say here's the warrant",
    "she grabs the piece of paper out of",
    "their hands and",
    "according to the u.s supreme court",
    "opinion she put",
    "this piece of paper into her bosom and",
    "very readily the police officer put his",
    "hands into her bosom",
    "and removed the paper later when we",
    "finally get into court",
    "the police have no warrant to show now",
    "the evidence discloses",
    "that no search warrant existed so",
    "whatever that piece of paper was that",
    "they were waving around",
    "it was not a search warrant to search",
    "her house they did arrest her",
    "they claimed that she was resisting",
    "arrest by trying to basically get the",
    "copy of the warrant",
    "which wasn't really a warrant and then",
    "they searched the house they did not",
    "find",
    "virgil ogletree which is the person they",
    "were there looking for",
    "they did find a number of materials that",
    "were like gambling",
    "policy numbers materials and they also",
    "found some materials that they thought",
    "were obscene",
    "so it starts out where she's charged",
    "with both gambling and obscenity but she",
    "goes to trial first on the gambling",
    "charge and is acquitted by the jury so",
    "that's done",
    "then she's prosecuted on the obscenity",
    "charge and she's found guilty so the",
    "ohio supreme court took the case",
    "and our supreme court four judges of the",
    "seven",
    "found that she was not constitutionally",
    "convicted",
    "but under our particular procedure where",
    "there is an",
    "affirmance",
    "then we need six of the seven",
    "jurists to hold this unconstitutional so",
    "even though map got a majority of the",
    "ohio supreme court to agree with her",
    "on first amendment grounds she didn't",
    "win the case",
    "so her lawyers appeal the case to the",
    "united states supreme court which takes",
    "the case and again",
    "in the mix are both the first amendment",
    "argument that her conviction for",
    "obscenity is unconstitutional",
    "because these materials were protected",
    "by the first amendment and her",
    "conviction was invalid",
    "or on the other hand a fourth amendment",
    "argument that the evidence had to be",
    "suppressed",
    "because it was obtained in violation of",
    "the fourth amendment so there were those",
    "two separate issues in the case",
    "so the u.s supreme court decides to take",
    "the case on fourth amendment grounds",
    "rather than the first amendment issue",
    "mapview ohio was decided in 1961. this",
    "is the warren court that's going to go",
    "on two years later to decide terry v",
    "ohio about stop and frisk it's going to",
    "decide miranda versus arizona",
    "a lot of these decisions setting up",
    "fundamental rights in particular for",
    "criminal defendants",
    "they hold that the police violated the",
    "fourth amendment by entering her home",
    "without a warrant that they had no",
    "justification for",
    "failing to get a warrant and therefore",
    "that the remedy they were going to apply",
    "was the exclusionary rule they were",
    "going to suppress the evidence",
    "because it had been obtained in",
    "violation of the fourth amendment",
    "mafia ohio is definitely one of the",
    "major decisions of the warren court",
    "and it's a huge decision in terms of",
    "taking a constitutional right",
    "and then applying a particular remedy",
    "which the fourth amendment does not say",
    "you exclude the evidence",
    "and applying that remedy to all state",
    "prosecutions there was a big reaction to",
    "mapping ohio especially",
    "among law enforcement they were really",
    "upset about the fact",
    "claiming that this was really going to",
    "impair their ability as law enforcement",
    "to carry out their jobs it was going to",
    "let the criminals",
    "go free mapview ohio did not change the",
    "substance of the fourth amendment",
    "it didn't change any of the rules about",
    "what the police are allowed to do",
    "when they can enter your home and when",
    "they need a warrant so if the police had",
    "been already complying with this",
    "constitutional requirements",
    "map the ohio wouldn't have changed much",
    "of anything the only thing that changed",
    "was the remedy",
    "they're not going to be able to use this",
    "evidence in court anymore and the fact",
    "that law enforcement reacted with such",
    "consternation",
    "was a significant piece of evidence that",
    "they were regularly violating people's",
    "fourth amendment rights",
    "the fact of the matter is that",
    "we are as citizens of ohio deprived",
    "of our constitutional rights against",
    "unlawful search and seizure",
    "when you look at dowry map's case and in",
    "particular the way things happen you see",
    "that",
    "when there was no remedy that the police",
    "cared about",
    "for enforcing the fourth amendment then",
    "the police pretty casually disregarded",
    "it",
    "it was just something written on paper",
    "and didn't have any really bite when you",
    "got into court",
    "the other case that i always tell my",
    "students about is a smaller case that",
    "nobody knows about",
    "state versus keeling decided in 1962",
    "by an ohio court of common pleas and",
    "what's interesting about the case is",
    "it features a lot of the same characters",
    "as matthew ohio",
    "you've got sergeant carl de lau you've",
    "got shondor burns the numbers runner and",
    "you've got the same prosecutors in",
    "matthew ohio they suspect that there's",
    "gambling going on in a particular suite",
    "in cleveland didn't go get a warrant",
    "they go down there they break in they",
    "search sure enough they find a bunch of",
    "gambling things",
    "the raid in that case happens a couple",
    "months after map v",
    "ohio is argued in the u.s supreme court",
    "and one month",
    "before the case is decided by the u.s",
    "supreme court i don't know if carl de",
    "lao knew what was happening in",
    "washington or not",
    "but while the u.s supreme court was",
    "considering that maybe we need to start",
    "excluding evidence if you don't get",
    "warrants carl de lau was up to the exact",
    "same thing back in cleveland",
    "dahl remap is this fantastic example of",
    "a",
    "a woman who insisted that the police try",
    "to follow the constitution to protect",
    "her rights and to take it to the united",
    "states supreme court and ultimately",
    "prevail and make the police do things",
    "the way that the",
    "constitution says that they're supposed",
    "to do them",
    "[Music]",
    "so",
    "[Music]",
    "you"
  ]
}