window.transcript = {
  "videoId": "jw0jsFmYg5w",
  "title": "Haunted Tales of the Ohio Statehouse",
  "dateString": "Oct 27, 2020",
  "date": "2020-10-27T00:00:00",
  "timestamps": [
    "00:00",
    "00:00",
    "00:02",
    "00:04",
    "00:06",
    "00:07",
    "00:11",
    "00:12",
    "00:16",
    "00:19",
    "00:22",
    "00:22",
    "00:25",
    "00:27",
    "00:29",
    "00:30",
    "00:33",
    "00:37",
    "00:40",
    "00:42",
    "00:44",
    "00:46",
    "00:48",
    "00:50",
    "00:52",
    "00:56",
    "00:59",
    "01:00",
    "01:03",
    "01:04",
    "01:07",
    "01:09",
    "01:12",
    "01:15",
    "01:17",
    "01:18",
    "01:21",
    "01:22",
    "01:27",
    "01:28",
    "01:29",
    "01:31",
    "01:32",
    "01:36",
    "01:39",
    "01:40",
    "01:43",
    "01:44",
    "01:49",
    "01:51",
    "01:53",
    "01:54",
    "01:56",
    "01:57",
    "01:59",
    "02:01",
    "02:05",
    "02:07",
    "02:08",
    "02:11",
    "02:13",
    "02:16",
    "02:19",
    "02:19",
    "02:24",
    "02:26",
    "02:28",
    "02:30",
    "02:32",
    "02:32",
    "02:36",
    "02:37",
    "02:39",
    "02:42",
    "02:43",
    "02:46",
    "02:48",
    "02:51",
    "02:52",
    "02:54",
    "02:57",
    "02:58",
    "03:01",
    "03:03",
    "03:06",
    "03:07",
    "03:10",
    "03:11",
    "03:14",
    "03:15",
    "03:19",
    "03:21",
    "03:23",
    "03:26",
    "03:29",
    "03:33",
    "03:34",
    "03:37",
    "03:40",
    "03:42",
    "03:45",
    "03:47",
    "03:50",
    "03:52",
    "03:54",
    "03:56",
    "04:01",
    "04:04",
    "04:05",
    "04:07",
    "04:09",
    "04:12",
    "04:13",
    "04:16",
    "04:16",
    "04:20",
    "04:23",
    "04:25",
    "04:29",
    "04:31",
    "04:33",
    "04:36",
    "04:39",
    "04:40",
    "04:43",
    "04:46",
    "04:49",
    "04:52",
    "04:53",
    "04:56",
    "04:57",
    "04:59",
    "05:00",
    "05:04",
    "05:08",
    "05:16",
    "05:18",
    "05:19",
    "05:23",
    "05:25",
    "05:27",
    "05:28",
    "05:30",
    "05:32",
    "05:33",
    "05:35",
    "05:37",
    "05:39",
    "05:40",
    "05:44",
    "05:47",
    "05:49",
    "05:51",
    "05:53",
    "05:54",
    "05:57",
    "06:00",
    "06:01",
    "06:03",
    "06:05",
    "06:06",
    "06:09",
    "06:10",
    "06:14",
    "06:16",
    "06:18",
    "06:21",
    "06:24",
    "06:25",
    "06:29",
    "06:32",
    "06:34",
    "06:35",
    "06:37",
    "06:40",
    "06:42",
    "06:44",
    "06:47",
    "06:48",
    "06:50",
    "06:54",
    "06:56",
    "06:59",
    "07:02",
    "07:03",
    "07:05",
    "07:06",
    "07:10",
    "07:14",
    "07:18",
    "07:19",
    "07:22",
    "07:24",
    "07:26",
    "07:28",
    "07:30",
    "07:33",
    "07:37",
    "07:38",
    "07:41",
    "07:45",
    "07:47",
    "07:50",
    "07:51",
    "07:53",
    "07:56",
    "07:58",
    "07:59",
    "08:04",
    "08:09",
    "08:12",
    "08:12",
    "08:15",
    "08:17",
    "08:19",
    "08:20",
    "08:23",
    "08:24",
    "08:27",
    "08:31",
    "08:35",
    "08:37",
    "08:39",
    "08:42",
    "08:44",
    "08:45",
    "08:46",
    "08:48",
    "08:53",
    "08:55",
    "08:58",
    "08:58",
    "09:01",
    "09:02",
    "09:03",
    "09:06",
    "09:08",
    "09:09",
    "09:13",
    "09:16",
    "09:18",
    "09:20",
    "09:22",
    "09:23",
    "09:25",
    "09:27",
    "09:29",
    "09:30",
    "09:35",
    "09:37",
    "09:38",
    "09:41",
    "09:43",
    "09:46",
    "09:48",
    "09:49",
    "09:52",
    "09:52",
    "09:54",
    "09:56",
    "09:58",
    "10:00",
    "10:03",
    "10:04",
    "10:07",
    "10:10",
    "10:14",
    "10:16",
    "10:18",
    "10:21",
    "10:22",
    "10:24",
    "10:25",
    "10:28",
    "10:31",
    "10:32",
    "10:35",
    "10:36",
    "10:39",
    "10:40",
    "10:43",
    "10:44",
    "10:49",
    "10:53",
    "10:57",
    "11:00",
    "11:04",
    "11:06",
    "11:08",
    "11:10",
    "11:12",
    "11:14",
    "11:16",
    "11:17",
    "11:19",
    "11:22",
    "11:24",
    "11:26",
    "11:28",
    "11:30",
    "11:32",
    "11:35",
    "11:37",
    "11:39",
    "11:43",
    "11:45",
    "11:47",
    "11:48",
    "11:51",
    "11:52",
    "11:54",
    "11:57",
    "11:59",
    "12:01",
    "12:03",
    "12:05",
    "12:07",
    "12:10",
    "12:12",
    "12:15",
    "12:18",
    "12:18",
    "12:21",
    "12:22",
    "12:26",
    "12:27",
    "12:29",
    "12:30",
    "12:32",
    "12:34",
    "12:36",
    "12:38",
    "12:40",
    "12:42",
    "12:43",
    "12:45",
    "12:47",
    "12:50",
    "12:52",
    "12:53",
    "12:56",
    "12:58",
    "13:00",
    "13:01",
    "13:04",
    "13:06",
    "13:09",
    "13:10",
    "13:13",
    "13:14",
    "13:18",
    "13:20",
    "13:22",
    "13:24",
    "13:26",
    "13:28",
    "13:32",
    "13:35",
    "13:38",
    "13:40",
    "13:42",
    "13:45",
    "13:46",
    "13:49",
    "13:50",
    "13:53",
    "13:55",
    "13:56",
    "13:58",
    "14:00",
    "14:02",
    "14:04",
    "14:05",
    "14:07",
    "14:10",
    "14:13",
    "14:15",
    "14:17",
    "14:19",
    "14:22",
    "14:24",
    "14:26",
    "14:29",
    "14:31",
    "14:33",
    "14:35",
    "14:36",
    "14:40",
    "14:40",
    "14:44",
    "14:45",
    "14:46",
    "14:49",
    "14:51",
    "14:54",
    "14:55",
    "14:57",
    "14:59",
    "15:01",
    "15:04",
    "15:05",
    "15:06",
    "15:08",
    "15:11",
    "15:12",
    "15:16",
    "15:19",
    "15:21",
    "15:23",
    "15:24",
    "15:26",
    "15:28",
    "15:29",
    "15:33",
    "15:35",
    "15:36",
    "15:37",
    "15:40",
    "15:43",
    "15:45",
    "15:47",
    "15:49",
    "15:51",
    "15:52",
    "15:54",
    "15:58"
  ],
  "transcripts": [
    "[Music]",
    "hello and welcome to haunted tales of",
    "the ohio state house",
    "my name is katie and i work at this",
    "historic building",
    "the ohio state house is over 150 years",
    "old",
    "with its construction starting in 1839.",
    "originally by penitentiary workers",
    "being 150 plus years old the state house",
    "has seen",
    "many important things rights given to",
    "ohioans",
    "important political historic speeches as",
    "well",
    "as on occasion a funeral",
    "as historians we believe that objects",
    "help to tell a story but what if",
    "these objects do more than just help to",
    "tell the story",
    "what if they hold on to the energy of",
    "the people and events",
    "that happened in the past and what if",
    "they help to keep the stories",
    "alive in more ways than we know",
    "what if this place and these objects",
    "serve as a conduit",
    "for the energy of events and people gone",
    "before",
    "and what if those people are still here",
    "in some way",
    "trying to tell their own story",
    "i myself have had multiple strange",
    "occurrences in this building that i",
    "cannot explain",
    "perhaps if you join us on a journey",
    "through this building",
    "you may be able to see these stories",
    "come alive",
    "[Music]",
    "[Laughter]",
    "[Music]",
    "[Laughter]",
    "the ohio penitentiary even though it has",
    "since been torn down",
    "still has a creepy hold on the ohio",
    "state house",
    "in more than one unsettling way",
    "as one of the oldest buildings in",
    "columbus the walls of the ohio state",
    "house",
    "have heard it all throughout its long",
    "history",
    "a whole host of characters have convened",
    "here it is of course",
    "the people's house it's no surprise then",
    "that along with the impressive beats",
    "that have been accomplished here",
    "there have also been some shocking and",
    "hair-raising tales that accompany those",
    "who used to wander these halls one",
    "gruesome rumor was perpetuated by former",
    "governor",
    "joseph euphoraker in september 1886",
    "governor forker spoke at the",
    "metropolitan opera house in columbus",
    "while campaigning for republican",
    "politicians who are running in the",
    "upcoming",
    "november election in an attempt",
    "to distinguish his party from the",
    "competition governor forker",
    "leveled a bold claim his predecessor",
    "democratic governor",
    "george hoadley had appointed some shady",
    "characters to oversee the state's",
    "penitentiary",
    "by the time governor forker had",
    "appointed a new prison warden",
    "the complex had fallen into a state of",
    "disrepair",
    "but that wasn't the worst of it forever",
    "claimed that one inmate",
    "frederick w nye contacted him with a",
    "signed affidavit",
    "proclaiming that he had been ordered to",
    "assist two doctors",
    "in the prison hospital in making canes",
    "out of dead prisoner's",
    "skin nai's services were required in",
    "stripping skin from the backs of",
    "deceased prisoners",
    "drying out the skin and preparing it for",
    "use on the canes",
    "in his sworn statement nye contended",
    "that he had made",
    "five canes two for each of the doctors",
    "and nye kept one for himself which he",
    "later passed on to the governor as",
    "proof of the scandal forecaster's speech",
    "was published in newspapers",
    "all across the state of ohio democrats",
    "of course declared the ghastly",
    "allegations to be false",
    "and the doctors said to be involved in",
    "the scandal staunchly denied the claims",
    "but the rumors persisted according to a",
    "doctor",
    "entrusted by forker to analyze nia's",
    "cane",
    "the cane was produced using three types",
    "of skin",
    "two from different people and one from",
    "an",
    "animal nye's story was also corroborated",
    "by other inmates and prison workers who",
    "noted the foul stench",
    "coming from his workshop so",
    "was there any truth to these claims or",
    "was it simply a way to drum up",
    "controversy before an election",
    "certainly it was not uncommon for prison",
    "workers to collect",
    "little trophies from deceased inmates",
    "stories about pieces of skin and hair",
    "were widely circulated",
    "we might never know if prison officials",
    "sanctioned",
    "the making of human skin canes but the",
    "story stayed",
    "front and center for many months and the",
    "governor",
    "who made such bold and sinister claims",
    "earned a new nickname skin came",
    "forager",
    "addicts have long been thought of as a",
    "hiding place",
    "for spirits and ghosts join our historic",
    "site manager chris",
    "on a journey up to the cupola to see",
    "what lurks",
    "there",
    "[Music]",
    "the yorkshire museum in the united",
    "kingdom issued a challenge a couple of",
    "years ago",
    "you see they had a curious object in",
    "their museum collections",
    "the object was a third to fourth century",
    "roman woman's hair bun made of real hair",
    "complete with the pin still sticking",
    "through it",
    "the challenge which was issued to other",
    "museums was",
    "can you beat it that is do you have an",
    "object that is creepier",
    "different museums responded",
    "enthusiastically",
    "one museum reported a petrified sheep's",
    "heart",
    "punctured by nails another museum",
    "reported",
    "a blood-soaked doll with a missing eye",
    "yet another museum reported a",
    "particularly gruesome",
    "smiling executioner's mask",
    "and finally another museum reported a",
    "decapitated cat",
    "curiously posed plucking a harp",
    "now that is curious and i thought we",
    "have a cat-related object in our state",
    "house collections",
    "and as i began to read more and more",
    "about curious museum collections",
    "i found that many of them had deceased",
    "cats in their inventory",
    "and most of these cats were found within",
    "the walls of buildings",
    "in the museum community they're called",
    "concealed cats",
    "evidence suggests that the custom of cat",
    "concealment began in the 13th century",
    "and continued into the modern era",
    "originating in europe",
    "the practice was brought to north",
    "america by immigrants",
    "but why scholars on the subject offer up",
    "three possible reasons one a foundation",
    "sacrifice two an attempt to scare off",
    "vermin",
    "or three accidental entrapment",
    "now let's take a look at our concealed",
    "cat",
    "this turn-of-the-century shoebox was",
    "found during the renovation of the ohio",
    "state house in the 1990s",
    "the label on the box reads the excelsior",
    "shoe company",
    "fine shoes portsmouth ohio",
    "and pencil riding on the label seems to",
    "indicate that the shoes inside",
    "were an eight and a half only there were",
    "no shoes inside",
    "when this box was pulled from within the",
    "walls of the state house instead",
    "what is contained inside are the",
    "disarticulated",
    "skeletal remains of a cat",
    "[Music]",
    "we must ask ourselves why was this",
    "deceased cat",
    "placed in this shoe box and left at the",
    "ohio state house",
    "if we consult the previously mentioned",
    "list",
    "this is definitely an intentional",
    "placement so",
    "accidental entrapment doesn't count",
    "an attempt to scare off vermin well",
    "as you can see",
    "this hole in the side of the box was",
    "most likely made by",
    "vermin probably a mouse or a rat and",
    "it helped itself to what was left of the",
    "cat",
    "certainly it didn't leave as much to",
    "take a look at",
    "so that only leaves foundation sacrifice",
    "but this cat was not found in the",
    "foundation of the ohio state house in",
    "fact this",
    "curiously concealed cat was found about",
    "as far away from the foundation as you",
    "get",
    "without leaving the building to find",
    "where this concealed cat was placed",
    "we have to go up",
    "[Music]",
    "since 1861 when the ohio state house was",
    "first complete",
    "visitors have climbed these stairs to",
    "get to the observation deck of the",
    "cupola",
    "once arriving at the observation deck",
    "visitors are greeted with a beautiful",
    "view of the city of columbus spreading",
    "out before them",
    "and reaching into the countryside",
    "this is the observation deck of the",
    "cupola",
    "and as i mentioned earlier the shoebox",
    "and remains of the cat were found during",
    "the renovation of the ohio state house",
    "they were actually found on the inside",
    "of this wall",
    "while they were doing ventilation work",
    "but to",
    "really get an idea of what it looks like",
    "within the walls",
    "we need to go up to what we like to call",
    "the tippy top",
    "above us is the skylight of the drum and",
    "below",
    "is the interior of the dome and if you",
    "look down you can see between the walls",
    "and the structure and perhaps",
    "a former worker at the ohio state house",
    "left behind this cat",
    "over a century ago or perhaps a visitor",
    "snuck up the stairs",
    "leaving behind a beloved companion",
    "placing them",
    "between the capitol walls as an honored",
    "resting place for all eternity",
    "for whatever the reason that this",
    "curiously concealed cat from the cupola",
    "was placed here",
    "it still resides within the walls of the",
    "ohio state house",
    "in our museum collections thank you for",
    "joining us",
    "and happy halloween",
    "the ohio state house took 22 years",
    "to build and as such it only makes sense",
    "that each stone would have a story",
    "to tell",
    "the ohio state house completed in 1861",
    "is one of the oldest buildings here in",
    "the city of columbus",
    "with such a long and storied history if",
    "these stones and bricks could talk",
    "they would have many interesting tales",
    "to tell",
    "some stones in particular would have",
    "especially chilling stories",
    "for example these stones that i am",
    "standing on",
    "these particular stones came from the",
    "floor of the columbus",
    "state hospital originally known as the",
    "ohio hospital for the insane",
    "the first institution of its kind the",
    "lunatic asylum of ohio",
    "was completed in 1838 it was located",
    "about a mile from the ohio state house",
    "on east broad street and was designed by",
    "nathan b",
    "kelly who later became the architect of",
    "the capitol",
    "and who was instrumental in designing",
    "the building that we're in today",
    "prison labor was also crucial to the",
    "building of the ohio state house",
    "many of the bricks and the stones that",
    "are around me were worked on",
    "by prisoners of the state of ohio and",
    "many of those same prisoners had",
    "also worked on the lunatic asylum the",
    "two structures share a strong connection",
    "literally the same hands built both",
    "however",
    "unlike the ohio state house the asylum",
    "no longer stands",
    "it was burned down in 1868 on november",
    "18th",
    "in a deadly blaze that killed six",
    "patients",
    "instead of rebuilding on that same east",
    "broad street site",
    "then governor rutherford b hayes",
    "convinced the state to sell that plot",
    "and buy a new one on the west end of",
    "columbus",
    "that plot was purchased from william",
    "sullivan who had originally owned",
    "capitol square",
    "where the state house is located today",
    "the foundation for the new hospital was",
    "laid on july 4th",
    "1870 and the building was completed",
    "exactly seven years later",
    "the columbus hospital for the insane as",
    "the new building was",
    "originally called was built according to",
    "the kirkbride plan",
    "which emphasized large open spaces and",
    "fresh air",
    "originally designed to house 850",
    "patients",
    "by 1935 it held almost three thousand",
    "with almost three times the number of",
    "patients that it was designed for",
    "it would have been impossible for the",
    "spaces to be used as they had been",
    "intended",
    "overcrowding was likely a serious issue",
    "underfunding was likely an issue as well",
    "according to a report from 1895",
    "that year the number of patients had",
    "increased by 25 percent",
    "but funding had remained stagnant death",
    "was a common occurrence",
    "at the columbus state hospital many",
    "patients spent",
    "decades confined to the campus only to",
    "eventually succumb to their mental",
    "illnesses",
    "many others died of communicable",
    "diseases that were common",
    "especially in the early years of the",
    "hospital's history",
    "the spread of disease would have been",
    "exacerbated by the aforementioned",
    "overcrowding issue one medical writer in",
    "the 1890s estimated that 95",
    "of the deaths were due to preventable",
    "illnesses",
    "it must have felt like a nightmare to",
    "watch disease ravage the halls",
    "all while being trapped by walls both",
    "physical and mental",
    "as dr kirkbride himself noted even the",
    "asylums that provided the best",
    "possible care for the time which for",
    "decades included things such as",
    "lobotomies and",
    "harsh electroshock therapy isolation",
    "would have been an",
    "ever-present issue as he said it is",
    "among the most painful features of",
    "insanity",
    "that in its treatment so many are",
    "compelled to leave their families",
    "feelings of isolation depression",
    "confusion",
    "would have been ever-present in the",
    "asylum",
    "by the early 1980s the columbus state",
    "hospital was in such a severe state of",
    "disrepair",
    "that the cost to restore it was",
    "virtually insurmountable",
    "so too had public asylums and hospitals",
    "for the insane",
    "fallen out of favor thus by 1985",
    "the columbus state hospital was closed",
    "and by 1996",
    "it had been completely demolished",
    "however",
    "this floor was saved and brought here to",
    "the ohio state house during the capital",
    "restoration",
    "of the 1990s did spirits",
    "of the more than a century's worth of",
    "patients from the columbus state",
    "hospital",
    "follow along is it merely coincidence",
    "that staff have heard voices and even",
    "their names whisper to them",
    "in this very space i'll leave that to",
    "you to decide",
    "we hope you enjoyed your journey through",
    "the ohio state house",
    "and learned a little of the spooky",
    "history that lurks",
    "within"
  ]
}