window.transcript = {
  "videoId": "Kn6vFoqFlno",
  "title": "State of the Judiciary Address 2020",
  "dateString": "Streamed live on Sep 10, 2020",
  "date": "2020-09-10T00:00:00",
  "timestamps": [
    "00:00",
    "01:56",
    "01:57",
    "02:07",
    "02:08",
    "02:15",
    "02:16",
    "02:28",
    "02:28",
    "02:31",
    "02:33",
    "02:38",
    "02:48",
    "02:55",
    "03:33",
    "03:45",
    "04:40",
    "04:42",
    "06:04",
    "06:09",
    "07:40",
    "07:53",
    "07:54",
    "10:22",
    "10:29",
    "10:32",
    "10:34",
    "10:37",
    "10:39",
    "10:45",
    "10:47",
    "10:50",
    "10:52",
    "10:53",
    "10:56",
    "11:09",
    "11:10",
    "11:13",
    "11:15",
    "11:17",
    "11:19",
    "11:26",
    "11:34",
    "11:44",
    "11:49",
    "11:52",
    "11:54",
    "11:56",
    "11:57",
    "12:00",
    "12:01",
    "12:03",
    "12:06",
    "12:09",
    "12:11",
    "12:12",
    "12:14",
    "12:16",
    "12:18",
    "12:19",
    "12:21",
    "12:24",
    "12:26",
    "12:28",
    "12:30",
    "12:31",
    "12:33",
    "12:35",
    "12:36",
    "12:39",
    "12:42",
    "12:43",
    "12:48",
    "12:51",
    "12:54",
    "12:56",
    "12:58",
    "13:00",
    "13:01",
    "13:03",
    "13:05",
    "13:07",
    "13:09",
    "13:12",
    "13:14",
    "13:15",
    "13:18",
    "13:20",
    "13:21",
    "13:23",
    "13:25",
    "13:28",
    "13:31",
    "13:35",
    "13:37",
    "13:39",
    "13:40",
    "13:43",
    "13:44",
    "13:47",
    "13:48",
    "13:50",
    "13:51",
    "13:53",
    "13:55",
    "13:57",
    "13:59",
    "14:01",
    "14:02",
    "14:06",
    "14:08",
    "14:10",
    "14:13",
    "14:14",
    "14:16",
    "14:18",
    "14:19",
    "14:22",
    "14:25",
    "14:28",
    "14:29",
    "14:32",
    "14:34",
    "14:35",
    "14:38",
    "14:38",
    "14:42",
    "14:45",
    "14:47",
    "14:48",
    "14:51",
    "14:52",
    "14:55",
    "14:58",
    "15:00",
    "15:02",
    "15:03",
    "15:05",
    "15:06",
    "15:08",
    "15:10",
    "15:12",
    "15:15",
    "15:17",
    "15:19",
    "15:22",
    "15:23",
    "15:25",
    "15:26",
    "15:29",
    "15:31",
    "15:34",
    "15:36",
    "15:38",
    "15:41",
    "15:44",
    "15:46",
    "15:47",
    "15:49",
    "15:51",
    "15:54",
    "15:54",
    "15:56",
    "15:58",
    "16:00",
    "16:02",
    "16:04",
    "16:06",
    "16:08",
    "16:10",
    "16:11",
    "16:14",
    "16:16",
    "16:19",
    "16:19",
    "16:22",
    "16:24",
    "16:27",
    "16:29",
    "16:31",
    "16:34",
    "16:36",
    "16:37",
    "16:40",
    "16:42",
    "16:44",
    "16:46",
    "16:48",
    "16:51",
    "16:53",
    "16:55",
    "16:56",
    "17:00",
    "17:03",
    "17:06",
    "17:08",
    "17:09",
    "17:11",
    "17:13",
    "17:16",
    "17:19",
    "17:20",
    "17:22",
    "17:24",
    "17:26",
    "17:27",
    "17:30",
    "17:31",
    "17:32",
    "17:35",
    "17:37",
    "17:39",
    "17:41",
    "17:42",
    "17:44",
    "17:46",
    "17:48",
    "17:50",
    "17:53",
    "17:56",
    "17:57",
    "17:59",
    "18:01",
    "18:02",
    "18:04",
    "18:06",
    "18:09",
    "18:11",
    "18:13",
    "18:14",
    "18:17",
    "18:19",
    "18:20",
    "18:22",
    "18:24",
    "18:27",
    "18:28",
    "18:30",
    "18:33",
    "18:34",
    "18:36",
    "18:39",
    "18:40",
    "18:43",
    "18:45",
    "18:47",
    "18:49",
    "18:51",
    "18:54",
    "18:55",
    "18:57",
    "18:59",
    "19:02",
    "19:04",
    "19:06",
    "19:08",
    "19:09",
    "19:11",
    "19:13",
    "19:17",
    "19:19",
    "19:22",
    "19:24",
    "19:26",
    "19:28",
    "19:30",
    "19:32",
    "19:33",
    "19:35",
    "19:37",
    "19:39",
    "19:41",
    "19:43",
    "19:45",
    "19:47",
    "19:49",
    "19:50",
    "19:53",
    "19:55",
    "19:57",
    "19:59",
    "20:01",
    "20:03",
    "20:04",
    "20:06",
    "20:08",
    "20:09",
    "20:11",
    "20:13",
    "20:16",
    "20:18",
    "20:20",
    "20:21",
    "20:23",
    "20:25",
    "20:27",
    "20:29",
    "20:30",
    "20:32",
    "20:34",
    "20:36",
    "20:38",
    "20:40",
    "20:42",
    "20:43",
    "20:46",
    "20:49",
    "20:51",
    "20:53",
    "20:54",
    "20:57",
    "20:58",
    "21:01",
    "21:02",
    "21:05",
    "21:07",
    "21:10",
    "21:12",
    "21:14",
    "21:17",
    "21:19",
    "21:20",
    "21:22",
    "21:23",
    "21:26",
    "21:28",
    "21:30",
    "21:33",
    "21:35",
    "21:36",
    "21:38",
    "21:40",
    "21:42",
    "21:44",
    "21:45",
    "21:48",
    "21:48",
    "21:51",
    "21:53",
    "21:55",
    "21:56",
    "21:59",
    "22:00",
    "22:03",
    "22:04",
    "22:06",
    "22:08",
    "22:10",
    "22:12",
    "22:15",
    "22:17",
    "22:21",
    "22:23",
    "22:24",
    "22:27",
    "22:28",
    "22:30",
    "22:32",
    "22:35",
    "22:38",
    "22:40",
    "22:42",
    "22:45",
    "22:47",
    "22:50",
    "22:51",
    "22:52",
    "22:54",
    "22:55",
    "22:59",
    "23:02",
    "23:04",
    "23:06",
    "23:07",
    "23:10",
    "23:11",
    "23:13",
    "23:15",
    "23:16",
    "23:18",
    "23:20",
    "23:23",
    "23:25",
    "23:26",
    "23:30",
    "23:30",
    "23:34",
    "23:34",
    "23:38",
    "23:41",
    "23:43",
    "23:46",
    "23:48",
    "23:50",
    "23:52",
    "23:55",
    "23:57",
    "23:58",
    "24:00",
    "24:02",
    "24:05",
    "24:06",
    "24:09",
    "24:10",
    "24:12",
    "24:15",
    "24:16",
    "24:19",
    "24:20",
    "24:22",
    "24:24",
    "24:26",
    "24:27",
    "24:30",
    "24:32",
    "24:33",
    "24:35",
    "24:37",
    "24:40",
    "24:42",
    "24:44",
    "24:47",
    "24:48",
    "24:50",
    "24:53",
    "24:54",
    "24:56",
    "24:58",
    "25:01",
    "25:04",
    "25:06",
    "25:08",
    "25:10",
    "25:11",
    "25:15",
    "25:16",
    "25:18",
    "25:20",
    "25:22",
    "25:25",
    "25:26",
    "25:29",
    "25:31",
    "25:34",
    "25:36",
    "25:38",
    "25:41",
    "25:43",
    "25:45",
    "25:48",
    "25:50",
    "25:52",
    "25:55",
    "25:58",
    "26:01",
    "26:04",
    "26:06",
    "26:09",
    "26:11",
    "26:14",
    "26:16",
    "26:17",
    "26:20",
    "26:20",
    "26:23",
    "26:24",
    "26:26",
    "26:28",
    "26:29",
    "26:31",
    "26:33",
    "26:35",
    "26:36",
    "26:38",
    "26:40",
    "26:41",
    "26:43",
    "26:46",
    "26:48",
    "26:51",
    "26:53",
    "26:55",
    "26:57",
    "26:59",
    "27:01",
    "27:04",
    "27:06",
    "27:08",
    "27:10",
    "27:12",
    "27:14",
    "27:15",
    "27:18",
    "27:20",
    "27:22",
    "27:24",
    "27:24",
    "27:28",
    "27:31",
    "27:32",
    "27:34",
    "27:37",
    "27:38",
    "27:41",
    "27:43",
    "27:45",
    "27:47",
    "27:49",
    "27:50",
    "27:53",
    "27:54",
    "27:56",
    "27:59",
    "28:01",
    "28:03",
    "28:05",
    "28:06",
    "28:08",
    "28:10",
    "28:12",
    "28:13",
    "28:16",
    "28:18",
    "28:20",
    "28:21",
    "28:23",
    "28:25",
    "28:27",
    "28:29",
    "28:30",
    "28:33",
    "28:36",
    "28:38",
    "28:41",
    "28:43",
    "28:44",
    "28:47",
    "28:49",
    "28:52",
    "28:53",
    "28:55",
    "28:57",
    "28:59",
    "29:02",
    "29:04",
    "29:06",
    "29:08",
    "29:10",
    "29:12",
    "29:14",
    "29:16",
    "29:18",
    "29:20",
    "29:23",
    "29:25",
    "29:27",
    "29:29",
    "29:30",
    "29:32",
    "29:34",
    "29:37",
    "29:38",
    "29:41",
    "29:43",
    "29:48",
    "29:50",
    "29:52",
    "29:54",
    "29:55",
    "29:58",
    "30:00",
    "30:03",
    "30:06",
    "30:08",
    "30:11",
    "30:13",
    "30:14",
    "30:16",
    "30:18",
    "30:21",
    "30:23",
    "30:25",
    "30:27",
    "30:29",
    "30:31",
    "30:34",
    "30:36",
    "30:37",
    "30:39",
    "30:41",
    "30:44",
    "30:46",
    "30:47",
    "30:50",
    "30:51",
    "30:54",
    "30:55",
    "30:57",
    "31:00",
    "31:02",
    "31:05",
    "31:07",
    "31:08",
    "31:10",
    "31:11",
    "31:14",
    "31:14",
    "31:17",
    "31:19",
    "31:20",
    "31:22",
    "31:24",
    "31:27",
    "31:30",
    "31:32",
    "31:35",
    "31:37",
    "31:39",
    "31:40",
    "31:42",
    "31:44",
    "31:46",
    "31:48",
    "31:50",
    "31:52",
    "31:55",
    "31:58",
    "31:59",
    "32:02",
    "32:04",
    "32:06",
    "32:08",
    "32:10",
    "32:12",
    "32:13",
    "32:16",
    "32:16",
    "32:18",
    "32:19",
    "32:22",
    "32:23",
    "32:26",
    "32:28",
    "32:30",
    "32:32",
    "32:34",
    "32:36",
    "32:37",
    "32:40",
    "32:42",
    "32:44",
    "32:45",
    "32:48",
    "32:49",
    "32:52",
    "32:55",
    "32:58",
    "32:59",
    "33:02",
    "33:05",
    "33:06",
    "33:08",
    "33:11",
    "33:12",
    "33:15",
    "33:17",
    "33:20",
    "33:21",
    "33:23",
    "33:24",
    "33:27",
    "33:28",
    "33:31",
    "33:32",
    "33:34",
    "33:37",
    "33:39",
    "33:41",
    "33:42",
    "33:45",
    "33:46",
    "33:49",
    "33:51",
    "33:51",
    "33:54",
    "33:56",
    "33:58",
    "34:01",
    "34:02",
    "34:04",
    "34:06",
    "34:09",
    "34:11",
    "34:13",
    "34:16",
    "34:19",
    "34:21",
    "34:23",
    "34:26",
    "34:26",
    "34:28",
    "34:30",
    "34:32",
    "34:34",
    "34:36",
    "34:39",
    "34:41",
    "34:43",
    "34:45",
    "34:47",
    "34:50",
    "34:51",
    "34:55",
    "34:56",
    "34:58",
    "34:59",
    "35:00",
    "35:02",
    "35:04",
    "35:06",
    "35:07",
    "35:09",
    "35:11",
    "35:13",
    "35:17",
    "35:18",
    "35:21",
    "35:23",
    "35:25",
    "35:26",
    "35:29",
    "35:30",
    "35:33",
    "35:35",
    "35:38",
    "35:39",
    "35:41",
    "35:43",
    "35:46",
    "35:47",
    "35:50",
    "35:52",
    "35:55",
    "35:57",
    "35:59",
    "36:00",
    "36:02",
    "36:04",
    "36:06",
    "36:08",
    "36:11",
    "36:12",
    "36:14",
    "36:16",
    "36:20",
    "36:22",
    "36:23",
    "36:25",
    "36:28",
    "36:29",
    "36:31",
    "36:33",
    "36:34",
    "36:38",
    "36:41",
    "36:44",
    "36:47",
    "36:48",
    "36:51",
    "36:52",
    "36:54",
    "36:56",
    "36:57",
    "36:58",
    "37:01",
    "37:03",
    "37:05",
    "37:07",
    "37:09",
    "37:12",
    "37:14",
    "37:16",
    "37:18",
    "37:20",
    "37:22",
    "37:24",
    "37:27",
    "37:27",
    "37:29",
    "37:30",
    "37:33",
    "37:36",
    "37:38",
    "37:38",
    "37:42",
    "37:43",
    "37:45",
    "37:46",
    "37:48",
    "37:50",
    "37:52",
    "37:55",
    "37:57",
    "37:59",
    "38:00",
    "38:01",
    "38:03",
    "38:05",
    "38:08",
    "38:09",
    "38:12",
    "38:14",
    "38:16",
    "38:18",
    "38:19",
    "38:21",
    "38:23",
    "38:25",
    "38:26",
    "38:30",
    "38:34",
    "38:35",
    "38:38",
    "38:38",
    "38:42",
    "38:44",
    "38:46",
    "38:48",
    "38:51",
    "38:53",
    "38:56",
    "38:58",
    "39:00",
    "39:02",
    "39:05",
    "39:06",
    "39:08",
    "39:10",
    "39:12",
    "39:14",
    "39:17",
    "39:18",
    "39:20",
    "39:21",
    "39:24",
    "39:26",
    "39:28",
    "39:30",
    "39:31",
    "39:34",
    "39:35",
    "39:37",
    "39:39",
    "39:40",
    "39:42",
    "39:44",
    "39:47",
    "39:48",
    "39:52",
    "39:54",
    "39:56",
    "39:59",
    "40:02",
    "40:04",
    "40:06",
    "40:07",
    "40:10",
    "40:15",
    "40:18",
    "40:21",
    "40:22",
    "40:24",
    "40:26",
    "40:29",
    "40:30",
    "40:32",
    "40:34",
    "40:37",
    "40:39",
    "40:41",
    "40:42",
    "40:45",
    "40:46",
    "40:48",
    "40:49",
    "40:52",
    "40:53",
    "40:55",
    "40:57",
    "41:00",
    "41:01",
    "41:04",
    "41:06",
    "41:08",
    "41:09",
    "41:12",
    "41:12",
    "41:15",
    "41:17",
    "41:19",
    "41:20",
    "41:23",
    "41:25",
    "41:27",
    "41:31",
    "41:37",
    "42:01",
    "42:14"
  ],
  "transcripts": [
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "laughs",
    "[Music]",
    "you only swear",
    "[Music]",
    "uh",
    "[Music]",
    "so",
    "[Music]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Music]",
    "reinvented in 2008 voted for voter chief",
    "justice in 2010",
    "and re-elected early 2016. she has",
    "served as a private lawyer administrator",
    "which is",
    "agenda foreign chief justice o'connor",
    "has led a significant judicial reform",
    "including the focus on the impact of",
    "fines",
    "and jail practices on the floor and she",
    "continued that cause",
    "and a very strong leader of that",
    "organization and uh",
    "leader on governmental responsiveness to",
    "america's drug addict",
    "so please join me in listening welcoming",
    "achievement",
    "uh",
    "thank you",
    "setting the example",
    "well thank you thank you judge powell i",
    "want to thank you for your service",
    "i also want to thank you for i think it",
    "was two",
    "uh judicial conferences of go of",
    "introducing me to",
    "uh one of the best irish whiskeys i've",
    "ever had redressed so",
    "you re you really have opened broadened",
    "my horizons on occasion so thank you",
    "very much",
    "uh good morning everybody i'm honored to",
    "speak with you today this is my tenth",
    "state of the judiciary",
    "address and all of them have been",
    "delivered of course at the ohio judicial",
    "conference annual meeting",
    "i want to begin by congratulating the",
    "new officers of the ohio judicial",
    "conference that i swore in a few minutes",
    "ago",
    "it's always a pleasure it has been a",
    "pleasure for me to work with you as a",
    "group",
    "and i look forward to our continuing uh",
    "involvement uh uh through the judicial",
    "conference",
    "your uh vision uh your contribution",
    "um your discussion uh your perspective",
    "are always welcome and a great a great",
    "resource i think for the supreme court",
    "praise is warranted for the judicial",
    "conference members and staff as well as",
    "judicial",
    "college of the supreme court for putting",
    "together a very fine",
    "program if this morning's program was",
    "any indication i really enjoyed",
    "the professor and as always very",
    "insightful",
    "and this afternoon should be no",
    "exception recognition goes to the ohio",
    "state bar association for serving as the",
    "remote host",
    "of the programs this year i also want to",
    "recognize my colleagues who",
    "are online like the rest of you",
    "justices kennedy french fisher",
    "justice dewine mike donnelly and justice",
    "melody stewart",
    "normally they would be standing in front",
    "of you but",
    "maybe they can stand in place like the",
    "officers",
    "and the chairs this forum is all about",
    "sharing ideas",
    "and working to advance the judiciary of",
    "our state",
    "the theme of this year's conference",
    "breaking barriers a reference to the",
    "100th anniversary",
    "of the ratification of the 19th",
    "amendment is quite fitting",
    "but of course we all know there",
    "continues to be barriers in our society",
    "one of the most obvious presented itself",
    "when ohio was hit with the pandemic",
    "over six months ago the need to follow",
    "the department of health guidelines",
    "presented a barrier",
    "to business as usual within our court",
    "system",
    "closing courts was not an option if ever",
    "there was an essential activity in ohio",
    "courts and the work we do rises to uh",
    "rises high",
    "on that list definitely below first",
    "responders and medical professionals and",
    "all of the many",
    "many service workers who don't have the",
    "option",
    "or the luxury of working from home like",
    "all of us do technology has made us",
    "the judiciary a pretty fortunate group",
    "of people",
    "during this pandemic in the face of",
    "coven 19",
    "what were judges to do what did we do",
    "and what do we continue to do",
    "to answer that question i will outline",
    "for you today the commitment of the ohio",
    "judiciary",
    "to not only deal with this pandemic but",
    "to go even",
    "further to improve the administration of",
    "justice in our state",
    "we have a health crisis to deal with and",
    "we do not know when it will end",
    "but we also have a long overdue mission",
    "separate from that crisis",
    "that mission is to seek out new and",
    "higher levels",
    "of the fair administration of justice",
    "and access to justice",
    "for all who come before our courts we",
    "must accomplish this mission by creating",
    "new tools and new ways of sharing",
    "information we will commit ourselves to",
    "examining the quality of our work",
    "and we will work to make we will we will",
    "make our work more visible to the public",
    "and improve their confidence in what we",
    "do",
    "before i explain further i want to look",
    "back at the past year and in particular",
    "the past six months the public health",
    "mandates",
    "in our state have been a great but",
    "necessary burden",
    "i'm confident that the court of public",
    "opinion will render a verdict in favor",
    "of our courts when this health crisis",
    "draws to a close",
    "that's because when the pandemic hit our",
    "first order of business was to act",
    "quickly",
    "to act positively and to act wisely the",
    "response of judges in ohio",
    "was remarkable you identified essential",
    "matters",
    "upon which to focus and meet the needs",
    "of those who came before your courts",
    "you released inmates from jail to lessen",
    "the chance of the virus spreading",
    "you set up hearings with remote",
    "participation and adhered to masks",
    "and sanitizing and social distancing",
    "requirements",
    "and you continue to do so you held",
    "proceedings in makeshift courtrooms",
    "many courts constructed plexiglas",
    "shields and configured new ways for",
    "participants to enter",
    "and exit hearing rooms you communicated",
    "your efforts locally",
    "this deadly virus forced all of us to",
    "adapt",
    "and we did ohio course remained open",
    "circumstances forced us to issue tolling",
    "orders and jury trials were delayed",
    "but those interruptions were an effort",
    "to keep people",
    "safe while we followed through on our",
    "obligation to deliver",
    "justice fairly ohio judges",
    "went beyond the call to service and the",
    "public took",
    "notice of our labors the news media",
    "spotlight has been honest",
    "constantly since march and the coverage",
    "has been overall",
    "quite favorable the media and the public",
    "came to understand that the courts were",
    "innovating",
    "on their behalf it's safe to say that",
    "many judges and staff have even",
    "surprised themselves",
    "on how well they've adjusted to this new",
    "reality",
    "when i made six million dollars from our",
    "budget available in march for judges to",
    "purchase remote equipment",
    "for their courtrooms the courts in 87",
    "out of 88 counties responded",
    "immediately applications flew into the",
    "supreme court",
    "where our fiscal staff worked overtime",
    "to validate and approve these technology",
    "grants",
    "our work these past six months has shown",
    "that judges in ohio",
    "are focused on administering justice you",
    "are doing so even when faced with",
    "obstacles that could not have been",
    "predicted",
    "well actually that's not true we do have",
    "one nostradamus on our staff and that's",
    "milt newsom",
    "the former washington county judge who",
    "is director of the judicial services",
    "at the ohio supreme court milk came to",
    "me last year with an idea about",
    "publishing a totally revised",
    "pandem public health guide for courts",
    "milk wanted me",
    "and all of you to be ready for a health",
    "emergency in fact he even used the word",
    "pandemic",
    "i said okay um on my mind at the time",
    "was the training and exposure",
    "that i had when i was director of the",
    "department of public safety for four",
    "years before i joined the court",
    "i had participated in numerous tabletop",
    "exercises",
    "and trainings dealing with the spread of",
    "a fast-moving highly contagious virus",
    "for which there was no vaccine the",
    "visuals presented",
    "left a lasting impression upon me the",
    "short time it took to spread around the",
    "world",
    "and the predictions of infections and",
    "mortalities were sobering",
    "so fast forward to 2020 and the covet 19",
    "pandemic",
    "and now it is no tabletop exercise",
    "it is a reality court staff worked on",
    "the public health guide for courts for",
    "several months",
    "and we sent it to you in january the",
    "pandemic and shoot ensued a few weeks",
    "later",
    "thank you milt for your leadership on",
    "the guides creation",
    "that deliverable had a positive effect",
    "although we did not know a year ago when",
    "we started on the project",
    "it helped us get ready for the pandemic",
    "by providing specific details on the",
    "ways courts could deal with the health",
    "disaster",
    "and the emergencies in general there are",
    "so many judges in our state who stepped",
    "up to the challenge of covet 19",
    "and kept their courts in session and",
    "kept justice flowing",
    "there's simply not enough time here",
    "today to mention",
    "all of them i will point out a few",
    "though while letting you know that i",
    "appreciate",
    "every effort from every judge during",
    "this covet",
    "and during this cobit pandemic licking",
    "county municipal court judge david",
    "stanbury reports that jury trials have",
    "resumed there",
    "both municipal courts have installed",
    "physical barriers between",
    "every juror seat between the rows of",
    "seats and between seats and each council",
    "table",
    "their clear hanging barriers in front of",
    "the his bench and between his seat and",
    "the witness stand in between the witness",
    "stand in the jury box",
    "many courts have taken similar measures",
    "and i must say i've been impressed with",
    "the speed",
    "at which these changes have occurred and",
    "the level of workmanship many courts are",
    "finding that remote video",
    "and audio equipment paid for by the tech",
    "grant is not only",
    "essential during this pandemic but it",
    "will be used",
    "long after the pandemic is behind us as",
    "it should be",
    "we've identified new efficiencies",
    "and ease of operation within the courts",
    "because of the use of technology",
    "franklin county municipal court is using",
    "its equipment to expand",
    "video remote language services they will",
    "now include american sign language",
    "interpreters to accommodate requests",
    "made under the americans with",
    "disabilities act",
    "that is a great idea and an enduring one",
    "our supreme court roster of interpreters",
    "covers 29",
    "languages today and it will grow",
    "remote technology is a great way to",
    "provide this service",
    "when an in-person session is not",
    "possible",
    "lakewood municipal court judge pat",
    "carroll and cuyahoga county domestic",
    "relations judge",
    "diane pelos stepped up when the pandemic",
    "hit",
    "they volunteered to teach courses at the",
    "judicial college webinars about",
    "creative solutions to keep the courts",
    "open",
    "during this crisis as the pandemic",
    "continues",
    "several courts are now live streaming",
    "barbarian municipal",
    "court ottawa county common pleas akron",
    "municipal court common police court of",
    "general division of cuyahoga county",
    "the 10th district court of appeal to",
    "name a few the barberton court in fact",
    "is making use of local public access",
    "tv channels as well this is a low-cost",
    "effective way to keep the public",
    "informed to keep",
    "our courts open another tool for",
    "transparency",
    "that has come about because of the",
    "pandemic but will be with us forever",
    "going forward is a new",
    "ohio virtual courtroom directory",
    "this project allows courts who are live",
    "streaming their proceedings to have that",
    "info and schedule on this directory that",
    "is housed at the supreme court",
    "the public will for example be able to",
    "look at the directory",
    "they'll be able to see when the 10th",
    "district court of appeals is holding",
    "oral arguments",
    "and tune into that argument in real time",
    "every court that is live streaming will",
    "submit their that information to the",
    "supreme court will put it on the",
    "directory",
    "and that can be available uh we of",
    "course have done this at the supreme",
    "court since 2002",
    "but now local courts can do this live",
    "streaming",
    "this type of project is a success in",
    "michigan and i believe that it will be",
    "a success here in ohio think of how it",
    "will enhance your community's knowledge",
    "of the court",
    "in action the people who put you on the",
    "bench",
    "will be able to see you in action that",
    "is an",
    "important feature for the judges",
    "to be able to access please explore how",
    "your court can live stream",
    "and join this directory and if you go to",
    "the website of the garfield municipal",
    "garfield heights municipal court you're",
    "greeted by the image",
    "and the soft voice of an avatar she is a",
    "virtual assistant who asks you to click",
    "on your questions",
    "she then looks you in the eye and",
    "produces an answer",
    "the technology solutions in ohio courts",
    "especially those in the past",
    "six months are the very definition of",
    "innovation",
    "a court's ability to provide proper",
    "access to justice while employing these",
    "technologies",
    "is something new accordingly guidance is",
    "necessary",
    "we have to establish guidance for the",
    "courts the supreme court",
    "just authorized to be out for public",
    "comment",
    "recommended changes to ohio rules of",
    "criminal procedure 11 and 41 that make",
    "clear",
    "if adopted that defendants in a fiance",
    "may appear electronically for plea",
    "hearings and search warrant applications",
    "whenever rules need to be updated to",
    "make clear the new role of technology",
    "and its use in the courts our court will",
    "act",
    "another leap forward is that ohio will",
    "join a pilot project by the national",
    "center for state courts",
    "the project will explore public",
    "perceptions of courts",
    "and how they use remote technologies by",
    "tapping into the collective experiences",
    "of courts across america we will be able",
    "to determine",
    "when we in ohio are venturing down the",
    "right path",
    "and just as importantly when we're not",
    "four of our courts will be part of the",
    "ncsc project",
    "the cuyahoga county domestic relations",
    "court coshocton county juvenile",
    "and probate court fairfield county",
    "juvenile and probate",
    "and montgomery county juvenile court i",
    "thank these courts for taking part",
    "and all of us await the results",
    "another project that the pandemic has",
    "spawned is the creation of the i",
    "court task force i'm charging the task",
    "force with examining how courts have",
    "used technology during the pandemic",
    "what have the experiences been survey",
    "judges and attorneys about their",
    "experience with remote appearances",
    "and trials identified best practices",
    "and technology what are the barriers and",
    "the challenges to the use of technology",
    "and more what do we do going forward",
    "i've asked justice pat dewine to be the",
    "supreme court liaison to this task force",
    "and invitations are out to all of the",
    "stakeholders to be part of this project",
    "stay tuned because i think the report",
    "that would be generated",
    "by this task force will be a guide for",
    "us",
    "in the future in the use of technology",
    "now",
    "switching gears a bit and since it's an",
    "election season i want to tell you that",
    "i've noticed a record",
    "high turnout among judges on judicial",
    "votes count",
    "website i'm talking about judges",
    "submitting their biographies and",
    "answering the questions",
    "for those of you running for office who",
    "haven't done so",
    "you really should judicial",
    "votescount.org is experiencing a record",
    "number of inquiries by the public",
    "and the media and that interest will",
    "only go higher for the next two months",
    "before the election",
    "innovation in ohio courts hasn't been",
    "limited to measures taken",
    "to deal with the pandemic advances in",
    "solving problems for ohioans in the name",
    "of justice continues to grow",
    "judge laura smith and the judges in",
    "fairfield county have brought together",
    "their community justice partners",
    "they have begun training on how to",
    "intervene",
    "with spousal matters and effectively",
    "supervise them",
    "more and more courts and the judges are",
    "using phone apps to get applicants to",
    "court",
    "on time it is a phenomenal tool across",
    "all jurisdictions of courts to remind",
    "people",
    "of their court appointments and to",
    "appear in court and the increase in peer",
    "appearances",
    "uh has skyrocketed the latest is ash to",
    "beauty county juvenile court judge",
    "albert kemp please to use this",
    "technology",
    "the cuyahoga county court of common",
    "police has partnered with",
    "a child advocacy center to train every",
    "judge and magistrate",
    "in the county about how trauma affects",
    "those who come before the court",
    "they're learning how judicial officers",
    "can improve access",
    "and outcomes for them and for their",
    "community",
    "thank you judges for these efforts and",
    "thanks to all of you",
    "whom the constraints of time i do not",
    "have",
    "the ability to acknowledge",
    "we have forged innovation ourselves in",
    "the supreme court this past",
    "year we've established new rules",
    "governing bail bond and pre-trial",
    "release in criminal cases",
    "today ohio courts must use the least",
    "restrictive bond conditions",
    "and the lowest amount of monetary bail",
    "to secure a defendant's court appearance",
    "going forward bond schedules are only to",
    "be used for securing release",
    "when court is not in session we also",
    "recently appointed a task force on",
    "conviction",
    "integrity integrity and convictions are",
    "two words that must always be spoken",
    "in tandem the task force is charged with",
    "analyzing",
    "and recommending meaningful advancements",
    "in procedures regarding",
    "integrity of convictions and the",
    "post-conviction review process",
    "all interested parties have been invited",
    "to participate and contribute to the",
    "success of the report",
    "i'm pleased to say that justice mike",
    "donnelly is the supreme court liaison",
    "and judge gene zamuta is the chair of",
    "the task force",
    "society's problems are laid at our",
    "doorstep and rightfully so",
    "it's hard and sometimes the work we do",
    "can seem demoralizing",
    "sometimes the cases that come before us",
    "make us question if there's even a",
    "solution",
    "for one case let alone the thousands",
    "that are pending in our dockets",
    "and what's the use what's the purpose we",
    "may ask ourselves",
    "am i helping my fellow man when those",
    "times present themselves as judges we",
    "must remember if not us who",
    "who is there to sit on the bench and try",
    "to meet out justice",
    "if not us you've been placed in an",
    "unique",
    "role in society a historic role that has",
    "its origins in",
    "every ancient city civilization that has",
    "ever existed that should inspire us that",
    "should inspire awe",
    "how and why you rose to the bench is not",
    "important but what is important is how",
    "you do your job",
    "how you try to deal with society's",
    "problems and how you tackle",
    "cases not as a case but as a problem",
    "that has greatly",
    "and usually negatively impacted the",
    "lives of those who are before you",
    "how are you going to solve that problem",
    "for people who cannot",
    "solve it for themselves",
    "that's what we do and i believe the god",
    "wouldn't have placed you on the bench if",
    "she hadn't had confidence that you're",
    "the ones that can handle the job",
    "essential to doing that job of a judge",
    "is to value the goal of equal impartial",
    "justice",
    "under the law in america we have risen",
    "to meet that goal",
    "countless times we have failed many",
    "times as well",
    "our obligation is to drive closer to",
    "that goal each hour of every day",
    "in accordance with the constitutions of",
    "our state and our nation",
    "protest and civil unrest this past",
    "spring",
    "and summer were spawned by the death of",
    "george floyd",
    "an unarmed handcuffed black man by the",
    "police in",
    "minneapolis but the resentment of the",
    "protesters towards our governmental",
    "systems",
    "including the judiciary is not the",
    "result of that one",
    "incident alone the history of our nation",
    "is one of immense contradictions we have",
    "founders who have envisioned quality",
    "for all while owning slaves laws and",
    "court decisions discriminated against",
    "fellow americans on the basis of their",
    "race",
    "and their gender barriers enacted by",
    "lawmakers and upheld in courts have",
    "restricted access to",
    "capital and certain neighborhoods based",
    "on skin color",
    "the list of injustices is long and the",
    "effects have reached from one century",
    "into another into another the",
    "inequalities linger",
    "and they persist but our founders",
    "embedded in their hallowed documents the",
    "instruments of change",
    "change for the better is a hallmark of",
    "our system of government",
    "but it requires steadfastness it",
    "requires",
    "protest the suffragists that we honor",
    "this year",
    "on the 100th anniversary of the women's",
    "right to vote",
    "worked on this project across several",
    "generations",
    "and for more than 70 years they took",
    "their protests to the streets",
    "countless times suffragists were the",
    "very first people to demonstrate at the",
    "white house",
    "they held silent vigils with banners and",
    "signs",
    "all the while dressed in white it drove",
    "woodrow wilson crazy",
    "they were spat upon they were harassed",
    "they were threatened",
    "and not just by men but they were",
    "undaunted and for that",
    "i am grateful change for the better is",
    "possible as leaders of the judiciary we",
    "are duty bound to continue finding new",
    "ways to make progress",
    "in the administration of justice",
    "doing so requires tools we have a lot of",
    "tools already",
    "we have our research capabilities we",
    "have bench cards the judicial college",
    "the conference",
    "etc we have our bar associations",
    "judicial organizations and we have each",
    "other but when it comes to fairness from",
    "the bench",
    "and sentencing we still lack the number",
    "one tool",
    "employed by every successful business in",
    "this country",
    "that tool is advanced metrics",
    "measurements",
    "for us this means metrics on sentencing",
    "and the outcome of court proceedings",
    "we gather reams of judicial data the",
    "statistical summaries from the supreme",
    "court of voluminous",
    "but we don't go nearly far enough to",
    "know how fair",
    "and equitable we are or can be when we",
    "make the most important decisions facing",
    "us",
    "as judges our lack of knowledge about",
    "sentencing reverberates in the public as",
    "lack of confidence in you",
    "and me and our judicial system 21 years",
    "ago",
    "then chief justice tom moyer",
    "commissioned a report on racial fairness",
    "that called for comprehensive statewide",
    "sentencing database",
    "nearly every state has a report a",
    "commission a blue ribbon panel",
    "seeking the same thing to no avail",
    "it's difficult to do that's the main",
    "excuse",
    "in our digital age manufacturers can",
    "track",
    "thousands even millions of parts in a",
    "day and ship them directly into the",
    "hands of a specific worker",
    "or or customer once installed they can",
    "follow the quality of these components",
    "and the experiences of their customers",
    "there are many other examples like that",
    "in the business world",
    "so yes establishing a sentencing",
    "database may be hard",
    "but it is not impossible and more",
    "importantly",
    "it is necessary here's what we need to",
    "know",
    "what sentence did courts impose for each",
    "felony offender and what was the record",
    "of the offender",
    "what was the race of the offender how",
    "many people were sentenced to a specific",
    "felony offense this year and at what",
    "level",
    "what number were placed in diversion",
    "programs how many were put on court",
    "ordered community control",
    "and so many more data points our goal is",
    "to answer these questions",
    "and and many more by bringing together",
    "the data of the courts and those of law",
    "enforcement prosecutors probation",
    "officers",
    "correction departments etc this",
    "information",
    "exists but it's not collected and",
    "aggregated and that's the shortcoming",
    "it's inside more than 300 courts in 88",
    "county",
    "silos and agencies and departments",
    "around the state",
    "this information that this is the",
    "information",
    "that we need in order to be able to",
    "make sense and to report what is",
    "happening in our courts",
    "you as a judge are being forced to fly",
    "blind and that's not fair to you",
    "it's important that our judge is",
    "sentenced with consistency",
    "judges and lawyers should have tools to",
    "know what the data shows regarding",
    "sentencing for each offense",
    "statewide given the cost of",
    "incarceration",
    "both monetary and in human terms",
    "consistency and predictability",
    "need to be measured it is a public that",
    "is demanding more equality in the",
    "judicial system",
    "and law enforcement and more",
    "transparency and rightfully so",
    "for the public to be informed and for",
    "truth to win out over",
    "rumor and fiction they must be able to",
    "see justice for",
    "all and understand how it is measured",
    "this is the path to faith in our system",
    "and it is the path that we must pursue",
    "metrics and transparency are on the side",
    "of the public",
    "and it's on our side we simply have to",
    "act",
    "the ohio criminal sentencing commission",
    "and a group of dedicated judges and",
    "court personnel",
    "have worked to make aggregation of",
    "sentencing data a reality",
    "the first deliverable is proposed",
    "uniform sentencing entries",
    "this will be this will set the stage for",
    "data gathering and analysis",
    "by academia the university of cincinnati",
    "ohio state and case western reserve are",
    "already involved",
    "initially a pilot program of one or more",
    "counties will be created",
    "the pilot will allow for the development",
    "and the identification",
    "of what works and what does not and that",
    "pilot",
    "as that pilot moves forward we will",
    "increase the number of counties",
    "participating and we will be asking",
    "for your help your reward will be an",
    "increase in the public's trust in the",
    "judiciary",
    "and a fantastic tool to help you every",
    "day",
    "judges want to be fair we strive to be",
    "fair",
    "this database will give us a foundation",
    "for fairness and objectivity that will",
    "change how we do our jobs",
    "and it will be a change for the better",
    "four years ago we set out to tie",
    "together data and criminal information",
    "across",
    "all kinds of political and",
    "organizational borders",
    "in eight states this included all the",
    "large and small bureaus and agencies",
    "and government branches in all these",
    "states with different laws and practices",
    "we tied them all together with academics",
    "and the federal health officials",
    "and the medical professionals we broke",
    "down barriers",
    "just as the theme of this conference",
    "prescribes",
    "we called it the regional judicial",
    "opioid initiative",
    "our joy it's an eight-state consortium",
    "and it works this that task had never",
    "been untaken",
    "undertaken before but in ohio we led the",
    "effort",
    "and as i said it's a success we did it",
    "other regions around the country have",
    "copied our initiative and there's a",
    "national effort as well",
    "we can apply the same can-do attitude to",
    "this sentencing project",
    "actually we must do so",
    "how can we explain to our citizens that",
    "we knew this database",
    "effort was critical to justice and our",
    "state but we didn't do it",
    "do we say we failed because we didn't",
    "get around to it or because it was too",
    "hard",
    "that's not the spirit of innovation that",
    "you as judges have so ably",
    "demonstrated for years and particularly",
    "the past six months",
    "during this pandemic i believe that we",
    "can do this",
    "i believe that we will do it so once",
    "again i want to thank the osb for",
    "hosting us",
    "and i want to extend best wishes to the",
    "ojc",
    "and hope that you all have a successful",
    "conference",
    "i'm going to close by recognizing two",
    "judges who have lost their lives to",
    "covet 19",
    "two of our judges franklin county",
    "municipal court",
    "judge william paulette died as a result",
    "of covet 19",
    "quite unexpectedly and it was a shock",
    "and retired judge joseph donofrio from",
    "the seventh district court of appeals",
    "also passed away um from covet 19.",
    "our condolences to their families um and",
    "to their colleagues and the people who",
    "knew them they were both wonderful",
    "gentlemen",
    "i also want to close with a",
    "a statement well just a preview",
    "paul pifer asked me last night about",
    "5 30. i think i got the email or the",
    "text",
    "can we do something about cle",
    "requirements this year",
    "for judges in light of the pandemic in",
    "light of",
    "the inability for some judges maybe to",
    "acquire all of their",
    "cle credits for those reporting this",
    "year",
    "i will tell you that there wasn't enough",
    "time between 5",
    "30 last night and and this morning to",
    "investigate it as",
    "thoroughly but i mentioned it to my",
    "colleagues",
    "we will be looking at it i can't promise",
    "you know what direction it will go",
    "i know that the commission uh for",
    "continuing legal education is meeting",
    "on the 18th of this month i've asked",
    "them to look at it",
    "so uh stay tuned we will try and come up",
    "with something",
    "whether it's extending the deadlines for",
    "reporting",
    "whether it's adjusting the number of",
    "credits",
    "etc we will we will not ignore this we",
    "we have been looking at it thinking",
    "about it and we will continue to do so",
    "so",
    "with that um i'm going to close uh i",
    "wish you again a successful conference i",
    "want to thank each and every one of you",
    "please stay well be safe",
    "wear your masks sanitize",
    "and god bless you all",
    "[Music]",
    "you"
  ]
}