window.transcript = {
  "videoId": "wUvyBvKGZFU",
  "title": "Ohio Governor Mike DeWine - COVID-19 Update | October 27, 2020",
  "dateString": "Streamed live on Oct 27, 2020",
  "date": "2020-10-27T00:00:00",
  "timestamps": [
    "00:00",
    "01:58",
    "02:35",
    "03:02",
    "03:03",
    "03:13",
    "03:21",
    "03:32",
    "03:58",
    "04:17",
    "04:22",
    "04:26",
    "04:27",
    "04:30",
    "04:33",
    "04:34",
    "04:36",
    "04:39",
    "04:40",
    "04:43",
    "04:44",
    "04:48",
    "04:49",
    "04:52",
    "04:55",
    "04:56",
    "04:58",
    "05:00",
    "05:01",
    "05:04",
    "05:05",
    "05:07",
    "05:11",
    "05:14",
    "05:15",
    "05:16",
    "05:20",
    "05:22",
    "05:25",
    "05:28",
    "05:32",
    "05:34",
    "05:36",
    "05:39",
    "05:40",
    "05:43",
    "05:44",
    "05:46",
    "05:48",
    "05:51",
    "05:52",
    "05:54",
    "05:56",
    "05:59",
    "06:00",
    "06:04",
    "06:05",
    "06:06",
    "06:08",
    "06:12",
    "06:13",
    "06:15",
    "06:16",
    "06:19",
    "06:21",
    "06:23",
    "06:24",
    "06:25",
    "06:27",
    "06:31",
    "06:32",
    "06:35",
    "06:36",
    "06:38",
    "06:39",
    "06:40",
    "06:42",
    "06:43",
    "06:46",
    "06:48",
    "06:49",
    "06:51",
    "06:51",
    "06:53",
    "06:55",
    "06:58",
    "06:59",
    "07:00",
    "07:01",
    "07:03",
    "07:03",
    "07:05",
    "07:07",
    "07:08",
    "07:10",
    "07:11",
    "07:12",
    "07:14",
    "07:16",
    "07:17",
    "07:20",
    "07:22",
    "07:23",
    "07:24",
    "07:26",
    "07:28",
    "07:30",
    "07:31",
    "07:34",
    "07:35",
    "07:37",
    "07:39",
    "07:40",
    "07:43",
    "07:45",
    "07:47",
    "07:48",
    "07:50",
    "07:52",
    "07:54",
    "07:56",
    "07:57",
    "07:58",
    "07:59",
    "08:01",
    "08:03",
    "08:05",
    "08:07",
    "08:09",
    "08:11",
    "08:11",
    "08:13",
    "08:14",
    "08:17",
    "08:18",
    "08:22",
    "08:23",
    "08:25",
    "08:27",
    "08:28",
    "08:31",
    "08:33",
    "08:35",
    "08:36",
    "08:38",
    "08:39",
    "08:40",
    "08:42",
    "08:45",
    "08:47",
    "08:48",
    "08:50",
    "08:52",
    "08:53",
    "08:56",
    "08:57",
    "08:58",
    "09:00",
    "09:02",
    "09:05",
    "09:06",
    "09:08",
    "09:10",
    "09:12",
    "09:14",
    "09:16",
    "09:17",
    "09:18",
    "09:20",
    "09:22",
    "09:24",
    "09:25",
    "09:27",
    "09:28",
    "09:30",
    "09:30",
    "09:32",
    "09:34",
    "09:36",
    "09:37",
    "09:38",
    "09:39",
    "09:41",
    "09:43",
    "09:43",
    "09:45",
    "09:47",
    "09:48",
    "09:49",
    "09:51",
    "09:53",
    "09:55",
    "09:57",
    "09:59",
    "10:00",
    "10:01",
    "10:03",
    "10:05",
    "10:06",
    "10:07",
    "10:10",
    "10:11",
    "10:13",
    "10:13",
    "10:15",
    "10:17",
    "10:20",
    "10:21",
    "10:23",
    "10:24",
    "10:27",
    "10:28",
    "10:30",
    "10:32",
    "10:34",
    "10:36",
    "10:36",
    "10:39",
    "10:41",
    "10:43",
    "10:45",
    "10:46",
    "10:48",
    "10:50",
    "10:52",
    "10:54",
    "10:56",
    "10:57",
    "10:59",
    "11:00",
    "11:01",
    "11:03",
    "11:04",
    "11:05",
    "11:07",
    "11:08",
    "11:10",
    "11:12",
    "11:13",
    "11:15",
    "11:16",
    "11:19",
    "11:20",
    "11:22",
    "11:23",
    "11:25",
    "11:27",
    "11:28",
    "11:30",
    "11:32",
    "11:34",
    "11:35",
    "11:37",
    "11:39",
    "11:40",
    "11:42",
    "11:43",
    "11:46",
    "11:48",
    "11:51",
    "11:51",
    "11:53",
    "11:55",
    "11:57",
    "11:59",
    "12:00",
    "12:02",
    "12:05",
    "12:07",
    "12:08",
    "12:10",
    "12:12",
    "12:13",
    "12:15",
    "12:16",
    "12:20",
    "12:22",
    "12:24",
    "12:26",
    "12:28",
    "12:31",
    "12:32",
    "12:33",
    "12:36",
    "12:38",
    "12:40",
    "12:42",
    "12:45",
    "12:45",
    "12:47",
    "12:48",
    "12:49",
    "12:50",
    "12:52",
    "12:55",
    "12:57",
    "12:58",
    "13:01",
    "13:02",
    "13:03",
    "13:05",
    "13:08",
    "13:09",
    "13:10",
    "13:12",
    "13:13",
    "13:15",
    "13:16",
    "13:18",
    "13:20",
    "13:22",
    "13:24",
    "13:26",
    "13:29",
    "13:31",
    "13:32",
    "13:35",
    "13:36",
    "13:39",
    "13:41",
    "13:42",
    "13:44",
    "13:45",
    "13:47",
    "13:48",
    "13:51",
    "13:53",
    "13:54",
    "13:56",
    "13:57",
    "13:58",
    "14:00",
    "14:01",
    "14:02",
    "14:04",
    "14:06",
    "14:07",
    "14:09",
    "14:11",
    "14:12",
    "14:14",
    "14:15",
    "14:17",
    "14:19",
    "14:20",
    "14:22",
    "14:23",
    "14:26",
    "14:27",
    "14:28",
    "14:30",
    "14:32",
    "14:33",
    "14:35",
    "14:37",
    "14:37",
    "14:40",
    "14:40",
    "14:42",
    "14:44",
    "14:45",
    "14:47",
    "14:49",
    "14:49",
    "14:51",
    "14:53",
    "14:54",
    "14:55",
    "14:56",
    "14:57",
    "14:59",
    "15:00",
    "15:01",
    "15:03",
    "15:04",
    "15:05",
    "15:06",
    "15:08",
    "15:09",
    "15:11",
    "15:12",
    "15:13",
    "15:15",
    "15:17",
    "15:19",
    "15:21",
    "15:24",
    "15:26",
    "15:27",
    "15:28",
    "15:31",
    "15:33",
    "15:34",
    "15:42",
    "15:45",
    "15:46",
    "15:50",
    "15:53",
    "15:56",
    "15:58",
    "16:02",
    "16:06",
    "16:08",
    "16:08",
    "16:11",
    "16:12",
    "16:14",
    "16:16",
    "16:20",
    "16:22",
    "16:24",
    "16:25",
    "16:28",
    "16:29",
    "16:32",
    "16:33",
    "16:36",
    "16:38",
    "16:41",
    "16:45",
    "16:49",
    "16:53",
    "16:56",
    "16:59",
    "17:02",
    "17:03",
    "17:05",
    "17:06",
    "17:08",
    "17:09",
    "17:11",
    "17:13",
    "17:15",
    "17:18",
    "17:21",
    "17:23",
    "17:27",
    "17:29",
    "17:30",
    "17:34",
    "17:36",
    "17:38",
    "17:39",
    "17:41",
    "17:43",
    "17:45",
    "17:48",
    "17:50",
    "17:52",
    "17:55",
    "17:57",
    "17:59",
    "18:00",
    "18:03",
    "18:04",
    "18:06",
    "18:07",
    "18:10",
    "18:12",
    "18:14",
    "18:16",
    "18:20",
    "18:21",
    "18:27",
    "18:31",
    "18:34",
    "18:35",
    "18:39",
    "18:41",
    "18:42",
    "18:46",
    "18:48",
    "18:50",
    "18:52",
    "18:53",
    "18:57",
    "19:01",
    "19:02",
    "19:04",
    "19:04",
    "19:07",
    "19:08",
    "19:11",
    "19:13",
    "19:16",
    "19:18",
    "19:21",
    "19:23",
    "19:26",
    "19:29",
    "19:32",
    "19:34",
    "19:36",
    "19:38",
    "19:40",
    "19:43",
    "19:45",
    "19:47",
    "19:49",
    "19:52",
    "19:54",
    "19:59",
    "20:01",
    "20:03",
    "20:04",
    "20:05",
    "20:08",
    "20:11",
    "20:13",
    "20:16",
    "20:18",
    "20:20",
    "20:21",
    "20:24",
    "20:27",
    "20:31",
    "20:33",
    "20:37",
    "20:39",
    "20:41",
    "20:42",
    "20:52",
    "20:55",
    "20:56",
    "20:59",
    "21:03",
    "21:04",
    "21:06",
    "21:08",
    "21:10",
    "21:12",
    "21:14",
    "21:17",
    "21:20",
    "21:21",
    "21:26",
    "21:28",
    "21:31",
    "21:36",
    "21:39",
    "21:42",
    "21:45",
    "21:45",
    "21:48",
    "21:50",
    "21:51",
    "21:53",
    "21:56",
    "21:58",
    "21:59",
    "22:02",
    "22:02",
    "22:06",
    "22:07",
    "22:10",
    "22:12",
    "22:16",
    "22:18",
    "22:20",
    "22:22",
    "22:25",
    "22:25",
    "22:29",
    "22:30",
    "22:32",
    "22:33",
    "22:36",
    "22:38",
    "22:41",
    "22:42",
    "22:45",
    "22:47",
    "22:51",
    "22:53",
    "22:55",
    "22:57",
    "22:59",
    "22:59",
    "23:01",
    "23:04",
    "23:05",
    "23:07",
    "23:10",
    "23:11",
    "23:18",
    "23:21",
    "23:24",
    "23:25",
    "23:30",
    "23:33",
    "23:35",
    "23:39",
    "23:44",
    "23:47",
    "23:48",
    "23:51",
    "23:52",
    "23:55",
    "23:56",
    "23:58",
    "23:59",
    "24:03",
    "24:05",
    "24:07",
    "24:08",
    "24:10",
    "24:12",
    "24:14",
    "24:17",
    "24:21",
    "24:27",
    "24:32",
    "24:35",
    "24:38",
    "24:39",
    "24:43",
    "24:46",
    "24:49",
    "24:52",
    "24:53",
    "24:56",
    "24:56",
    "24:59",
    "25:01",
    "25:03",
    "25:05",
    "25:06",
    "25:09",
    "25:12",
    "25:15",
    "25:17",
    "25:19",
    "25:21",
    "25:24",
    "25:27",
    "25:29",
    "25:31",
    "25:34",
    "25:35",
    "25:37",
    "25:38",
    "25:41",
    "25:43",
    "25:45",
    "25:49",
    "25:53",
    "25:56",
    "25:58",
    "26:02",
    "26:05",
    "26:10",
    "26:13",
    "26:15",
    "26:17",
    "26:18",
    "26:20",
    "26:22",
    "26:24",
    "26:25",
    "26:29",
    "26:29",
    "26:32",
    "26:33",
    "26:36",
    "26:38",
    "26:41",
    "26:44",
    "26:45",
    "26:49",
    "26:52",
    "26:54",
    "26:55",
    "26:59",
    "27:00",
    "27:02",
    "27:04",
    "27:06",
    "27:08",
    "27:10",
    "27:11",
    "27:13",
    "27:14",
    "27:17",
    "27:19",
    "27:21",
    "27:22",
    "27:24",
    "27:26",
    "27:29",
    "27:32",
    "27:34",
    "27:35",
    "27:41",
    "27:44",
    "27:46",
    "27:49",
    "27:50",
    "27:52",
    "27:54",
    "27:55",
    "27:58",
    "27:59",
    "28:02",
    "28:03",
    "28:06",
    "28:07",
    "28:09",
    "28:11",
    "28:13",
    "28:14",
    "28:18",
    "28:22",
    "28:25",
    "28:27",
    "28:29",
    "28:30",
    "28:32",
    "28:34",
    "28:36",
    "28:39",
    "28:41",
    "28:42",
    "28:44",
    "28:45",
    "28:48",
    "28:48",
    "28:52",
    "28:52",
    "28:54",
    "28:56",
    "28:58",
    "28:59",
    "29:03",
    "29:05",
    "29:07",
    "29:10",
    "29:11",
    "29:14",
    "29:16",
    "29:17",
    "29:20",
    "29:22",
    "29:24",
    "29:27",
    "29:28",
    "29:30",
    "29:32",
    "29:33",
    "29:36",
    "29:37",
    "29:40",
    "29:42",
    "29:44",
    "29:47",
    "29:48",
    "29:50",
    "29:51",
    "29:54",
    "29:57",
    "29:58",
    "30:00",
    "30:02",
    "30:04",
    "30:06",
    "30:06",
    "30:09",
    "30:11",
    "30:13",
    "30:15",
    "30:19",
    "30:22",
    "30:23",
    "30:26",
    "30:27",
    "30:29",
    "30:30",
    "30:33",
    "30:36",
    "30:38",
    "30:38",
    "30:42",
    "30:44",
    "30:45",
    "30:48",
    "30:51",
    "30:54",
    "30:57",
    "30:59",
    "31:02",
    "31:05",
    "31:05",
    "31:08",
    "31:10",
    "31:13",
    "31:14",
    "31:16",
    "31:17",
    "31:20",
    "31:22",
    "31:24",
    "31:25",
    "31:26",
    "31:29",
    "31:32",
    "31:34",
    "31:36",
    "31:37",
    "31:39",
    "31:40",
    "31:41",
    "31:43",
    "31:47",
    "31:49",
    "31:51",
    "31:52",
    "31:56",
    "31:59",
    "31:59",
    "32:02",
    "32:04",
    "32:12",
    "32:14",
    "32:15",
    "32:18",
    "32:19",
    "32:21",
    "32:22",
    "32:25",
    "32:27",
    "32:29",
    "32:32",
    "32:34",
    "32:37",
    "32:39",
    "32:40",
    "32:43",
    "32:46",
    "32:47",
    "32:50",
    "32:52",
    "32:54",
    "32:56",
    "32:58",
    "33:00",
    "33:01",
    "33:03",
    "33:05",
    "33:07",
    "33:09",
    "33:10",
    "33:14",
    "33:15",
    "33:18",
    "33:20",
    "33:22",
    "33:23",
    "33:26",
    "33:28",
    "33:30",
    "33:31",
    "33:33",
    "33:35",
    "33:38",
    "33:40",
    "33:42",
    "33:44",
    "33:46",
    "33:48",
    "33:50",
    "33:53",
    "33:55",
    "33:56",
    "33:59",
    "34:00",
    "34:02",
    "34:03",
    "34:05",
    "34:07",
    "34:11",
    "34:13",
    "34:14",
    "34:17",
    "34:18",
    "34:19",
    "34:22",
    "34:24",
    "34:24",
    "34:28",
    "34:29",
    "34:31",
    "34:32",
    "34:34",
    "34:38",
    "34:40",
    "34:42",
    "34:43",
    "34:45",
    "34:47",
    "34:48",
    "34:51",
    "34:53",
    "34:55",
    "34:56",
    "34:59",
    "35:01",
    "35:02",
    "35:04",
    "35:06",
    "35:08",
    "35:11",
    "35:13",
    "35:14",
    "35:17",
    "35:18",
    "35:20",
    "35:21",
    "35:25",
    "35:26",
    "35:29",
    "35:30",
    "35:33",
    "35:35",
    "35:38",
    "35:40",
    "35:42",
    "35:45",
    "35:46",
    "35:47",
    "35:49",
    "35:52",
    "35:53",
    "35:55",
    "35:57",
    "35:58",
    "36:01",
    "36:03",
    "36:04",
    "36:07",
    "36:09",
    "36:11",
    "36:14",
    "36:17",
    "36:20",
    "36:23",
    "36:24",
    "36:26",
    "36:27",
    "36:29",
    "36:30",
    "36:32",
    "36:34",
    "36:36",
    "36:38",
    "36:42",
    "36:44",
    "36:45",
    "36:47",
    "36:49",
    "36:51",
    "36:55",
    "36:58",
    "37:00",
    "37:03",
    "37:06",
    "37:08",
    "37:11",
    "37:13",
    "37:14",
    "37:18",
    "37:21",
    "37:23",
    "37:25",
    "37:30",
    "37:31",
    "37:34",
    "37:38",
    "37:41",
    "37:43",
    "37:45",
    "37:47",
    "37:48",
    "37:51",
    "37:54",
    "37:55",
    "37:58",
    "37:59",
    "38:01",
    "38:03",
    "38:06",
    "38:09",
    "38:10",
    "38:13",
    "38:14",
    "38:15",
    "38:17",
    "38:18",
    "38:19",
    "38:22",
    "38:23",
    "38:24",
    "38:27",
    "38:30",
    "38:32",
    "38:34",
    "38:36",
    "38:39",
    "38:39",
    "38:42",
    "38:44",
    "38:47",
    "38:48",
    "38:50",
    "38:54",
    "38:56",
    "38:57",
    "39:00",
    "39:01",
    "39:03",
    "39:04",
    "39:06",
    "39:08",
    "39:10",
    "39:12",
    "39:14",
    "39:15",
    "39:17",
    "39:19",
    "39:20",
    "39:22",
    "39:26",
    "39:28",
    "39:30",
    "39:33",
    "39:36",
    "39:38",
    "39:40",
    "39:42",
    "39:45",
    "39:46",
    "39:48",
    "39:51",
    "39:52",
    "39:54",
    "39:56",
    "39:58",
    "40:00",
    "40:02",
    "40:03",
    "40:06",
    "40:08",
    "40:09",
    "40:11",
    "40:13",
    "40:16",
    "40:18",
    "40:21",
    "40:24",
    "40:26",
    "40:28",
    "40:30",
    "40:33",
    "40:35",
    "40:37",
    "40:39",
    "40:41",
    "40:43",
    "40:46",
    "40:49",
    "40:51",
    "40:53",
    "40:54",
    "40:56",
    "40:58",
    "41:00",
    "41:02",
    "41:03",
    "41:04",
    "41:06",
    "41:07",
    "41:11",
    "41:14",
    "41:15",
    "41:19",
    "41:21",
    "41:22",
    "41:25",
    "41:27",
    "41:29",
    "41:31",
    "41:33",
    "41:35",
    "41:37",
    "41:39",
    "41:41",
    "41:43",
    "41:46",
    "41:50",
    "41:51",
    "41:53",
    "41:55",
    "41:58",
    "41:59",
    "42:01",
    "42:03",
    "42:07",
    "42:09",
    "42:12",
    "42:14",
    "42:16",
    "42:19",
    "42:22",
    "42:25",
    "42:26",
    "42:29",
    "42:30",
    "42:32",
    "42:34",
    "42:36",
    "42:38",
    "42:41",
    "42:45",
    "42:47",
    "42:49",
    "42:52",
    "42:53",
    "42:55",
    "42:58",
    "43:00",
    "43:01",
    "43:04",
    "43:06",
    "43:10",
    "43:11",
    "43:14",
    "43:17",
    "43:18",
    "43:21",
    "43:24",
    "43:24",
    "43:28",
    "43:30",
    "43:31",
    "43:35",
    "43:38",
    "43:40",
    "43:42",
    "43:44",
    "43:45",
    "43:48",
    "43:50",
    "43:51",
    "43:53",
    "43:55",
    "43:57",
    "43:59",
    "44:01",
    "44:03",
    "44:04",
    "44:07",
    "44:08",
    "44:11",
    "44:12",
    "44:16",
    "44:16",
    "44:19",
    "44:20",
    "44:22",
    "44:24",
    "44:27",
    "44:28",
    "44:32",
    "44:35",
    "44:36",
    "44:37",
    "44:39",
    "44:42",
    "44:44",
    "44:47",
    "44:48",
    "44:50",
    "44:52",
    "44:54",
    "44:55",
    "44:56",
    "44:59",
    "45:01",
    "45:02",
    "45:04",
    "45:06",
    "45:08",
    "45:12",
    "45:14",
    "45:15",
    "45:17",
    "45:19",
    "45:21",
    "45:23",
    "45:24",
    "45:26",
    "45:29",
    "45:30",
    "45:31",
    "45:33",
    "45:35",
    "45:38",
    "45:40",
    "45:41",
    "45:43",
    "45:45",
    "45:48",
    "45:51",
    "45:52",
    "45:53",
    "45:56",
    "46:00",
    "46:02",
    "46:04",
    "46:05",
    "46:08",
    "46:10",
    "46:13",
    "46:14",
    "46:16",
    "46:18",
    "46:20",
    "46:23",
    "46:27",
    "46:30",
    "46:31",
    "46:35",
    "46:37",
    "46:39",
    "46:39",
    "46:41",
    "46:43",
    "46:45",
    "46:46",
    "46:48",
    "46:50",
    "46:53",
    "46:57",
    "47:00",
    "47:03",
    "47:05",
    "47:07",
    "47:09",
    "47:11",
    "47:12",
    "47:15",
    "47:17",
    "47:19",
    "47:21",
    "47:24",
    "47:27",
    "47:32",
    "47:33",
    "47:35",
    "47:37",
    "47:39",
    "47:41",
    "47:42",
    "47:44",
    "47:46",
    "47:48",
    "47:50",
    "47:54",
    "47:57",
    "47:57",
    "48:01",
    "48:02",
    "48:04",
    "48:07",
    "48:09",
    "48:09",
    "48:11",
    "48:12",
    "48:14",
    "48:16",
    "48:17",
    "48:19",
    "48:20",
    "48:23",
    "48:24",
    "48:27",
    "48:31",
    "48:33",
    "48:34",
    "48:36",
    "48:38",
    "48:41",
    "48:42",
    "48:44",
    "48:46",
    "48:48",
    "48:50",
    "48:51",
    "48:53",
    "48:54",
    "48:57",
    "48:59",
    "49:02",
    "49:04",
    "49:06",
    "49:09",
    "49:10",
    "49:12",
    "49:14",
    "49:15",
    "49:17",
    "49:19",
    "49:21",
    "49:22",
    "49:25",
    "49:28",
    "49:29",
    "49:31",
    "49:32",
    "49:35",
    "49:36",
    "49:39",
    "49:40",
    "49:41",
    "49:43",
    "49:45",
    "49:48",
    "49:50",
    "49:52",
    "49:54",
    "49:55",
    "49:58",
    "49:58",
    "50:01",
    "50:02",
    "50:03",
    "50:05",
    "50:06",
    "50:08",
    "50:12",
    "50:13",
    "50:16",
    "50:19",
    "50:20",
    "50:23",
    "50:26",
    "50:27",
    "50:29",
    "50:29",
    "50:31",
    "50:34",
    "50:36",
    "50:37",
    "50:39",
    "50:40",
    "50:44",
    "50:46",
    "50:47",
    "50:50",
    "50:51",
    "50:52",
    "50:55",
    "50:57",
    "50:59",
    "51:01",
    "51:03",
    "51:05",
    "51:07",
    "51:09",
    "51:11",
    "51:14",
    "51:14",
    "51:18",
    "51:18",
    "51:21",
    "51:22",
    "51:23",
    "51:25",
    "51:27",
    "51:29",
    "51:31",
    "51:32",
    "51:34",
    "51:35",
    "51:37",
    "51:40",
    "51:40",
    "51:42",
    "51:45",
    "51:48",
    "51:51",
    "51:53",
    "51:54",
    "51:58",
    "52:00",
    "52:02",
    "52:04",
    "52:06",
    "52:08",
    "52:11",
    "52:14",
    "52:15",
    "52:18",
    "52:18",
    "52:21",
    "52:22",
    "52:25",
    "52:26",
    "52:28",
    "52:32",
    "52:33",
    "52:38",
    "52:41",
    "52:44",
    "52:46",
    "52:47",
    "52:49",
    "52:50",
    "52:52",
    "52:54",
    "52:55",
    "52:57",
    "52:59",
    "53:00",
    "53:02",
    "53:03",
    "53:05",
    "53:09",
    "53:10",
    "53:13",
    "53:16",
    "53:17",
    "53:19",
    "53:21",
    "53:22",
    "53:25",
    "53:27",
    "53:29",
    "53:30",
    "53:32",
    "53:33",
    "53:47",
    "53:50",
    "53:52",
    "53:54",
    "53:55",
    "53:58",
    "54:01",
    "54:03",
    "54:05",
    "54:06",
    "54:08",
    "54:11",
    "54:12",
    "54:15",
    "54:17",
    "54:20",
    "54:22",
    "54:24",
    "54:25",
    "54:27",
    "54:30",
    "54:33",
    "54:35",
    "54:37",
    "54:39",
    "54:41",
    "54:43",
    "54:44",
    "54:48",
    "54:50",
    "54:52",
    "54:53",
    "54:55",
    "54:58",
    "55:00",
    "55:01",
    "55:05",
    "55:07",
    "55:09",
    "55:10",
    "55:13",
    "55:14",
    "55:16",
    "55:18",
    "55:21",
    "55:22",
    "55:24",
    "55:27",
    "55:30",
    "55:31",
    "55:33",
    "55:35",
    "55:37",
    "55:40",
    "55:41",
    "55:44",
    "55:45",
    "55:47",
    "55:49",
    "55:51",
    "55:53",
    "55:55",
    "55:55",
    "55:58",
    "56:00",
    "56:01",
    "56:02",
    "56:04",
    "56:04",
    "56:06",
    "56:08",
    "56:09",
    "56:14",
    "56:16",
    "56:18",
    "56:21",
    "56:24",
    "56:25",
    "56:28",
    "56:30",
    "56:32",
    "56:33",
    "56:35",
    "56:39",
    "56:43",
    "56:46",
    "56:48",
    "56:49",
    "56:51",
    "56:52",
    "56:53",
    "56:56",
    "56:58",
    "57:00",
    "57:02",
    "57:04",
    "57:07",
    "57:09",
    "57:10",
    "57:14",
    "57:18",
    "57:21",
    "57:25",
    "57:27",
    "57:28",
    "57:32",
    "57:35",
    "57:35",
    "57:37",
    "57:39",
    "57:41",
    "57:43",
    "57:43",
    "57:45",
    "57:47",
    "57:50",
    "57:53",
    "57:55",
    "57:56",
    "57:59",
    "58:00",
    "58:02",
    "58:04",
    "58:06",
    "58:08",
    "58:10",
    "58:11",
    "58:13",
    "58:15",
    "58:19",
    "58:21",
    "58:25",
    "58:28",
    "58:29",
    "58:32",
    "58:33",
    "58:36",
    "58:37",
    "58:39",
    "58:40",
    "58:42",
    "58:43",
    "58:45",
    "58:47",
    "58:48",
    "58:50",
    "58:54",
    "58:56",
    "58:58",
    "59:00",
    "59:02",
    "59:02",
    "59:04",
    "59:06",
    "59:07",
    "59:08",
    "59:10",
    "59:13",
    "59:14",
    "59:16",
    "59:17",
    "59:20",
    "59:22",
    "59:24",
    "59:24",
    "59:27",
    "59:29",
    "59:33",
    "59:34",
    "59:37",
    "59:40",
    "59:42",
    "59:43",
    "59:44",
    "59:46",
    "59:48",
    "59:50",
    "59:52",
    "59:56",
    "59:58",
    "59:59",
    "60:03",
    "60:05",
    "60:07",
    "60:08",
    "60:09",
    "60:12",
    "60:13",
    "60:15",
    "60:17",
    "60:19",
    "60:22",
    "60:23",
    "60:26",
    "60:28",
    "60:30",
    "60:31",
    "60:33",
    "60:36",
    "60:36",
    "60:38",
    "60:40",
    "60:43",
    "60:45",
    "60:48",
    "60:51",
    "60:52",
    "60:54",
    "60:56",
    "60:58",
    "60:59",
    "61:00",
    "61:01",
    "61:02",
    "61:04",
    "61:05",
    "61:07",
    "61:08",
    "61:10",
    "61:12",
    "61:13",
    "61:16",
    "61:17",
    "61:18",
    "61:20",
    "61:22",
    "61:23",
    "61:25",
    "61:27",
    "61:30",
    "61:32",
    "61:35",
    "61:37",
    "61:39",
    "61:40",
    "61:42",
    "61:44",
    "61:47",
    "61:50",
    "61:53",
    "61:54",
    "61:58",
    "62:02",
    "62:02",
    "62:06",
    "62:08",
    "62:18",
    "62:20",
    "62:37",
    "62:41"
  ],
  "transcripts": [
    "[Music]",
    "[Music]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Music]",
    "[Music]",
    "[Music]",
    "so",
    "good afternoon everyone",
    "the ohio mass today was sent to me by",
    "cynthia",
    "symphony cynthia matthias and",
    "we appreciate that very much and people",
    "are just coming up with all kinds of",
    "designs i think this she said this is a",
    "joanne fabrics design the time we're in",
    "today is",
    "is ohio university's heritage college of",
    "osteopathic medicine",
    "so we we thank all the folks who are",
    "there",
    "and all the graduates and professors",
    "who help our health care system in the",
    "state of ohio",
    "let me start by thanking senate",
    "president abhof speaker cup",
    "members of the general assembly for",
    "their leadership and assistance",
    "in the controlling board's recent",
    "approval of 419",
    "000 419 million dollars",
    "in cares act funding to help our fellow",
    "ohioans",
    "this money will be used for small",
    "business grants 160 125 million",
    "rent and utility assistance that's 50",
    "million grants to bars in",
    "restaurants 37.5 million",
    "help for our hospitals 62 million",
    "in our colleges and universities that's",
    "100 million and support for ohio's",
    "world-class art organizations as well as",
    "non-profits",
    "and that's a total of 25 million again i",
    "thank them",
    "all the members the controlling board",
    "for getting this approved",
    "it will do a lot of good one week from",
    "today is",
    "election day and so we have the",
    "secretary of state",
    "ready to talk to us and give us kind of",
    "a report",
    "frank larose mr secretary i can see it",
    "looks like you're in your office with a",
    "view of the",
    "state house there that's a pretty nice",
    "view tell us where we are a week out",
    "well thank you so much governor you're",
    "right it is a week before",
    "election day but of course we're three",
    "weeks into election month in ohio",
    "and we've already seen record-breaking",
    "numbers of ohioans taking advantage of",
    "early",
    "and absentee voting you can see the",
    "countdown clock behind me six days",
    "17 hours 29 minutes and 40 seconds until",
    "the polls open",
    "on the morning of tuesday november 3rd",
    "and there are a couple things i just",
    "wanted to talk about today governor i",
    "really appreciate you giving me the",
    "opportunity",
    "uh to to discuss a few of these things",
    "of course way back in the spring",
    "we faced an unprecedented challenge and",
    "ohio's elections officials",
    "rolled up their sleeves to make sure",
    "that we were ready we launched what we",
    "called the",
    "ready for november task force where we",
    "had a weekly meeting that was shared",
    "here on the ohio channel we set a few",
    "key objectives",
    "of course one thing that we wanted to do",
    "is make sure that we got plenty of",
    "people registered to vote because it's",
    "hard to get",
    "voter registration done in the",
    "traditional ways and i'm happy to report",
    "that we surpassed",
    "eight million registered voters in the",
    "state of ohio that's something that",
    "we're really proud of",
    "we also knew that we needed to launch an",
    "unprecedented effort to recruit plenty",
    "of poll workers",
    "i'm happy to say that over 140 000",
    "ohioans came to our website and signed",
    "up to be poll workers and as we stand",
    "today",
    "well over 50 000 of them have been",
    "trained and are ready to go to open our",
    "polling locations in a safe and",
    "accessible way",
    "on tuesday morning november 3rd one of",
    "the other things that we really focused",
    "on was trying to maximize early and",
    "absentee voting and i'll tell you that",
    "has been a humongous success",
    "we have seen a doubling in the number of",
    "absentee ballots that we've seen in past",
    "years and we've seen it triple as far as",
    "early voting goes",
    "and so by all accounts this has been a",
    "very successful effort and of course",
    "we had to make sure that right health",
    "and safety protocols were put in place",
    "so we worked with the ohio department of",
    "health",
    "and the united states centers for",
    "disease control to put in place a",
    "61-point checklist",
    "so that every voter and every poll",
    "worker can feel safe and comfortable",
    "coming to participate in early in-person",
    "voting as well as an election day voting",
    "now",
    "the bottom line is this there have been",
    "some some folks wondering",
    "uh will election day happen as scheduled",
    "it of course will",
    "election day is unchangeable the first",
    "tuesday after the first monday in",
    "november is set",
    "in both state and federal law it has",
    "been unchanged",
    "since 1843. you can contrast that with",
    "primary elections which routinely do",
    "move over the years and we know",
    "that as a result of the pandemic some",
    "adjustments had to be made to the way",
    "that ohio",
    "conducted the primary back in march and",
    "of course concluding at the end of april",
    "but the general election day is set and",
    "it will not change the polls will open",
    "at 6 30 a.m",
    "on november 3rd and that's important for",
    "people to know they'll be open until 7",
    "30 that night",
    "now just like i said we're all excited",
    "about election day but you don't have to",
    "wait for election day because",
    "in ohio we have election month in fact",
    "voting continues today",
    "voting continues tomorrow voting will be",
    "happening on thursday",
    "friday and as well as saturday and",
    "sunday we're one of very few states in",
    "the nation that offers weekend",
    "early voting ohio has that we have",
    "saturday early voting we've got sunday",
    "early voting we've got convenient",
    "evening hours",
    "this week in fact on monday the day",
    "before the election early voting",
    "continues until two that day and it's",
    "something that ohioans",
    "are taking advantage of in really",
    "massive numbers now i talked about that",
    "health and safety plan that we put",
    "together",
    "we launched this two months ago a",
    "61-point checklist",
    "every board of elections is required to",
    "follow that checklist what that'll make",
    "sure of",
    "is that again if you feel comfortable",
    "going to the grocery store you should",
    "feel comfortable coming to your polling",
    "location",
    "a lot of the same precautions are in",
    "place you're going to see six feet of",
    "social distancing",
    "you're going to see personal protective",
    "equipment being warned by both voters",
    "and of course our poll workers any",
    "elections observers that may be there",
    "as well you're going to see common sense",
    "things like having a door in",
    "separate from a door out where that's",
    "possible you're going to see something",
    "as simple as a door stop",
    "so that people aren't touching the door",
    "handle all day long of course wiping",
    "down of surfaces",
    "we've been able to field massive",
    "quantities of personal protective",
    "equipment because of patriotic ohio",
    "companies",
    "that have stepped up and answered the",
    "call and donated tpe",
    "but we also took uh the vast majority of",
    "our federal dollars and pushed them out",
    "to this to the counties",
    "so that they could spend those dollars",
    "to procure the necessary ppe to make",
    "sure that it's safe",
    "i talked about us wanting to maximize",
    "early and absentee voting that's been a",
    "humongous success governor and i",
    "actually have new numbers to report as",
    "of today",
    "3.2 million voters have already",
    "requested an emsty bound",
    "3.2 million ohioans have already",
    "requested empty ballot now contrast that",
    "to four years ago",
    "the number was 1.6 million so we've",
    "clearly seen a doubling",
    "in absentee voting in ohio the bottom",
    "line is this today",
    "is effectively the last day the law says",
    "you could wait until saturday but that's",
    "a bad idea today is effectively the last",
    "day",
    "to request your absolute balance so if",
    "you want to be one of those millions of",
    "ohioans",
    "who is voting from the safety and",
    "comfort of home today is the day to do",
    "so",
    "you can do it easily by returning the",
    "absolute ballot request form that we",
    "sent to all",
    "8 million ohio registered voters or if",
    "you lost that or don't have it",
    "you can go to voteohio.gov and on that",
    "website you can print",
    "the absentee ballot request form heck if",
    "you don't have a printer you can even",
    "make your own just using a plain",
    "piece of notebook paper and we give you",
    "all the instructions right there at",
    "voteohio.gov",
    "we've also seen 1.5 million ohioans who",
    "have already returned their absentee",
    "ballot but here's a reminder",
    "if you requested an absolute ballot and",
    "it's sitting there on your kitchen table",
    "what are you waiting for go ahead and",
    "fill it out do just like what lauren and",
    "i did fill out your afsd",
    "ballot put the appropriate postage in on",
    "it and mail it in today and once you do",
    "you can go to voteohio.gov and track",
    "your ballot",
    "to make sure that it's received by your",
    "county board of elections now we've seen",
    "over 750",
    "000 ohioans that have taken advantage of",
    "early voting that's",
    "2.5 times the number that we saw in",
    "2016. ohioans are clearly enthusiastic",
    "now you may have seen some lines over",
    "the weekend of course our",
    "elections work to keep those socially",
    "distanced so it may look like a longer",
    "line than it actually is",
    "but those lines move quickly and that's",
    "a sign of enthusiasm",
    "ohioans have 216 hours of early voting",
    "and ohioans are taking advantage of that",
    "enthusiastically and so if you like that",
    "in-person voting experience don't wait",
    "go to voteohio.gov to find",
    "the hours and locations for early voting",
    "in your county the location for early",
    "voting in your county",
    "and make sure to make your voice heard",
    "we've also seen ohioans that have",
    "cast their ballot in huge numbers 2.2",
    "million as i already said",
    "and we also know that 840 000 ballots",
    "are still",
    "out there so again if you're sitting on",
    "that make sure to get it returned right",
    "away",
    "something else i want to address",
    "governor there's been",
    "no share no shortage of disinformation",
    "and misinformation out there now ohioans",
    "won't be fooled",
    "ohioans know that the trustworthy source",
    "for elections information",
    "is your county board of elections",
    "website for the ohio secretary of state",
    "website voteohio.gov but there are folks",
    "out there that want to spread false",
    "information",
    "if you believe that you're seeing false",
    "information",
    "intentional disinformation about",
    "elections report it",
    "we don't tolerate that in ohio we don't",
    "tolerate voter intimidation",
    "we don't tolerate disinformation the way",
    "to report that is on",
    "our email system it's report ohio",
    "sos.gov that's monitored 24 hours a day",
    "report ohio sos.gov and i've got a",
    "success story",
    "because of a thoughtful ohio that",
    "reported to us",
    "an incident of voter intimidation that",
    "was targeted particularly at the",
    "minority community a really",
    "ugly and pernicious act of voter",
    "disinformation",
    "there's a cleveland grand jury today",
    "that actually",
    "just indicted two bad guys who are going",
    "to face justice for it our office played",
    "a role in helping to make sure that",
    "these people face justice because they",
    "were trying to confuse and intimidate",
    "voters",
    "we won't tolerate it anybody that thinks",
    "that they're going to get away with that",
    "kind of thing has another thing coming",
    "we don't tolerate that in ohio ohioans",
    "know it's easy to vote",
    "it's easy to vote in the buckeye state",
    "and now the bottom line is this",
    "make your voice heard there's no excuse",
    "for not voting you've got",
    "a whole month of early voting a whole",
    "month of absentee voting and you've got",
    "in-person election day voting",
    "and when this is all over governor",
    "ohioans will know it was a fair and",
    "honest contest now one last thing about",
    "how we report",
    "election night results we always report",
    "an unofficial result on election night",
    "now what does that mean",
    "that means we report every early vote",
    "every absentee vote",
    "and every in-person election they vote",
    "that's come in so far but it's never the",
    "final story because ohio boards of",
    "elections have",
    "10 days to receive ballots as long as",
    "they were cast",
    "as long as they were mailed by monday",
    "november 2nd",
    "as long as it's a legal ballot it",
    "deserves to be counted and so when we",
    "have that unofficial result on election",
    "night",
    "it's going to be a snapshot in time the",
    "official result a few weeks later",
    "is the one that really counts but here's",
    "something that we're doing that's",
    "getting a lot of attention around the",
    "nation",
    "we're also on election night going to",
    "report the number of outstanding",
    "absolute ballots",
    "that's a number that'll tell us how many",
    "ballots are still out there in the",
    "postal system that are waiting to come",
    "back",
    "and that'll give ohioans a good sense of",
    "whether that's a conclusive result",
    "they're seeing on election night or not",
    "again the bottom line is this if you got",
    "a ballot mail it in",
    "if you want to vote absentee request",
    "that absolute ballot today",
    "whichever method you choose make sure",
    "you vote ohio thanks so much governor",
    "secretary thank you very much and thanks",
    "to all the poll workers who are going to",
    "be there",
    "next tuesday and thanks to everybody at",
    "the board of elections uh today that",
    "are working hard to see that people can",
    "vote today",
    "thank you very much we appreciate it",
    "well sadly the red tide of the virus",
    "continues to spread throughout",
    "ohio into every every corner of this",
    "state there is no there's no escaping it",
    "82 of our counties 82 of our counties",
    "are now classified as high",
    "incident spread counties only six",
    "that are not every ohio needs to have an",
    "understanding of exactly what is going",
    "on",
    "in their own community they need to",
    "understand",
    "what the data is what's happened in the",
    "last two weeks with cases",
    "hospitalizations etc",
    "they need to understand the extent of",
    "the spread in their community that's why",
    "we continue to do these press",
    "conferences that's why uh we post this",
    "information",
    "uh up online every day so with that in",
    "mind let's",
    "look at the numbers uh for today",
    "as we look at these numbers i think",
    "every ohioan needs to be alarmed by what",
    "we are seeing",
    "as you can see over 2500",
    "new cases again",
    "22 new deaths 198",
    "new hospitalizations and 20",
    "new icu admissions it was not that long",
    "ago",
    "it was not that long ago when this",
    "number as you recall",
    "uh three weeks ago three and a half",
    "weeks ago",
    "it was hovering around a thousand and we",
    "thought it was going to drop",
    "and stay below a thousand so this is",
    "dramatically as you can see dramatically",
    "gone up let's look at our 88 counties",
    "now",
    "88 counties in order all the way down",
    "again this is the highest spread to the",
    "lowest spread",
    "and again this week we have colored in",
    "blue all the counties that are high",
    "incident counties",
    "these are counties that have a high",
    "incidence and",
    "again you will see that just a handful",
    "six counties at the bottom",
    "do not have high incidence levels",
    "again evidence that this is just",
    "absolutely",
    "everywhere high incidence",
    "means the county has had more than a",
    "hundred cases per hundred thousand",
    "residents",
    "over the last two weeks this number is",
    "the distinction",
    "that the cdc makes between a county with",
    "a moderately high",
    "level of spread and a high level of",
    "spread",
    "we know that a high level of cases in",
    "the community just makes it",
    "more dangerous um and increases the risk",
    "of catching",
    "this infection from someone else",
    "let's go to the top uh 20 counties slide",
    "again these are the the top 20 all areas",
    "of the state",
    "um continue to see this increase but",
    "if you look at our top counties again",
    "you'll see",
    "that you know the first 10 counties are",
    "you know some of the smaller counties of",
    "of the state",
    "you'll see some of the counties with you",
    "know this is eight",
    "over eight times the high incidence rate",
    "this is you know five times four times",
    "so you can just see that some of the",
    "very very high incident counties are",
    "just",
    "literally literally off off the charts",
    "and that is",
    "certainly very concerning eric let's",
    "look at the hospitalization",
    "map as well and again this tracks the",
    "entire period from back in april",
    "uh to to the present and one of the",
    "things that you will see",
    "you'll see this color the light blue",
    "is total hospitalization",
    "people in the hospital icu with people",
    "in icu",
    "vent that's the yellow and that's people",
    "who are on ventilators so you can see",
    "how those numbers are moving",
    "again this is a snapshot of how many",
    "people are in the in the hospital",
    "so what you're seeing of course is a",
    "much steeper curve",
    "than we saw than we saw in in june",
    "certainly a steeper curve than we saw",
    "before",
    "we have seen peaks in the",
    "hospitalization before once in the",
    "spring",
    "and again this summer the current",
    "increase in utilization is noticeably",
    "sharper steeper than the increase we saw",
    "during the summer peak",
    "based on the trajectory of other",
    "early indicators we've likely not yet",
    "reached the top we have no indication",
    "that we've",
    "plateaued out at all coveted positive",
    "utilization has basically doubled",
    "from i see excuse me positive icu",
    "utilization has doubled",
    "from the beginning of october and that",
    "is very concerning as well again we're",
    "not to the point where any of our",
    "hospitals are overflowing",
    "but the trend lines are not not good",
    "as you can see this virus is spreading",
    "and it is",
    "everywhere in ohio",
    "it is community spread that is driving",
    "this",
    "when you see numbers as high as we just",
    "looked at that indicates",
    "that virtually every county has except",
    "six 82 counties",
    "have this high high spread which means",
    "it's out in the community",
    "the community spread endangers our",
    "schools",
    "our nursing homes and our hospitals",
    "take a look at the slide that we have",
    "right here",
    "is a cause and effect",
    "community spread caused by these things",
    "and other things",
    "lead to problems in nursing homes our",
    "schools",
    "and in our hospitals it is cause and",
    "effect as the virus spreads in the",
    "community from gatherings where people",
    "aren't wearing masks or",
    "aren't social distancing it is directly",
    "impacting our ability to keep our",
    "schools open",
    "directly impacting our ability to",
    "protect",
    "our elderly and those who are ill who",
    "are in our nursing homes",
    "and it directly impacts ultimately our",
    "hospitals",
    "and if it continues and we possibly can",
    "see our hospitals overrun",
    "things that we've seen on tv but have",
    "not yet experienced in ohio",
    "and something that we certainly do not",
    "want to",
    "experience again these are some of the",
    "things that",
    "are causing our community spread no mask",
    "people not",
    "keeping a distance game day watch",
    "parties now",
    "large wedding receptions crowded bars",
    "house parties",
    "extended family uh gathered gathering",
    "gatherings with extended family",
    "um these ultimately",
    "if you worry about your your grandmother",
    "in the nursing home",
    "this community spread is how we can",
    "control it keeping that down when it",
    "goes up",
    "the odds of it getting into a nursing",
    "home goes up when it goes up and it's as",
    "high levels as we're seeing in many",
    "counties today",
    "it threatens our k-12 schools when it",
    "goes up",
    "it threatens ultimately our hospitals",
    "so what do we do about this",
    "in the words of two great ohio state",
    "coaches",
    "um and let me quote from them",
    "we do need to stick to our game plan",
    "because we know it works",
    "ohio when we stick together we always",
    "win they said it very very well",
    "this is a game that we must win and to",
    "do that",
    "we have to get back to basics we have to",
    "get back",
    "to the fundamentals wear a mask when",
    "you're out in public",
    "when you go to a store when you're with",
    "friends",
    "keep your distance wash your hands often",
    "work on the ventilation so you're",
    "bringing in more air from the outside in",
    "your in your home",
    "or in the public building that you're in",
    "charge of",
    "if you're one of the 82 counties you",
    "live in one of the 82 counties",
    "that is now a high incident county",
    "let's be more specific",
    "please reconsider reconsider hosting or",
    "attending gatherings of any size",
    "this includes with friends and extended",
    "family people who don't live",
    "in your in your household two",
    "think about canceling events",
    "certainly don't go to halloween parties",
    "three were masked inside and outside",
    "when you cannot",
    "social distance above the nose over the",
    "mouth",
    "secure under the chin stay home if",
    "you're not well",
    "cooperate with your local public health",
    "officials if you're diagnosed with coven",
    "19",
    "or exposed to somebody who has coven 19",
    "work remotely from home if you can and",
    "we need help from our businesses",
    "uh allow employees to work from home",
    "when possible",
    "a lot of people did that if you can",
    "still do that if that works",
    "it's better two send your employees",
    "communications urging them to take",
    "personal precautions to",
    "prevent the spread of covet 19 not just",
    "during",
    "their time at work but when they're home",
    "when they're out",
    "and about three",
    "for retail establishments require",
    "customers to wear masks",
    "unless there is some specific exemption",
    "our problem is community spread",
    "because 82 of our counties are high",
    "incidence counties",
    "i am today asking leaders",
    "in every single county",
    "to redouble your efforts uh we've seen",
    "a lot of great leadership come out of",
    "mayors county commissioners",
    "business community those in labor we've",
    "seen",
    "people uh in our lot of leadership",
    "around the state",
    "on this issue and so thank you very very",
    "much",
    "now though is the time to reevaluate in",
    "each",
    "single community every county exactly",
    "what",
    "you are doing and so i'm asking you to",
    "pull together",
    "that group of leaders in the community",
    "drawn from all different all different",
    "parts",
    "of the community each community",
    "really needs to reassess right now",
    "what it is doing and what it can do in",
    "the future",
    "we are at a critical stage review",
    "certainly should include county",
    "commissioners mayors",
    "health commissioners school and hospital",
    "leaders college leaders",
    "community other community leaders",
    "including those from the faith-based",
    "community",
    "from business and from the non-profit",
    "sector",
    "one of the great things about our state",
    "is the great communities",
    "and how people pull together whether",
    "it's a large",
    "county or a small county that people",
    "come together to solve",
    "problems we are all in this together",
    "what each person does or does not do",
    "will determine how well we do over the",
    "next few months",
    "before the vaccine arrives",
    "i'm going to start meetings today as",
    "soon as this",
    "press conference is over uh",
    "and we're going to start first with the",
    "three counties that are on",
    "the watch list we'll do two of those",
    "counties today one tomorrow",
    "then i will move to the highest of the",
    "high",
    "incidence counties and again you know",
    "we'll start with these counties",
    "and start working our way down um and",
    "again",
    "we'll do a zoom call we'll bring people",
    "together",
    "and we'll just kind of talk and we'll",
    "exchange ideas",
    "um i'll be there my team will be there",
    "to listen to your concerns listen to",
    "where you need us to help you we'll tell",
    "you where we can",
    "help you but these kind of meetings i",
    "think are",
    "are very very important now it's going",
    "to take me a while to",
    "get down through the list uh but we're",
    "going to do them as fast as we can but",
    "obviously in the meantime we would ask",
    "you to",
    "pull together uh set up a meeting",
    "yourselves",
    "uh get on the phone get on zoom get on",
    "whatever",
    "however you can do it uh and pull people",
    "together",
    "in in the community because it's",
    "communities working together",
    "that's going to make the difference this",
    "is how we're going to beat",
    "this enemy we have a common enemy",
    "we have a common enemy and that is this",
    "virus and it's a virus",
    "that will not the trend lines will not",
    "change",
    "unless we change them if we continue to",
    "do the same things we've been doing",
    "we're going to end up getting the same",
    "results so although",
    "many people are wearing masks many",
    "people are being very very careful",
    "we need just to get that our game up uh",
    "and we need to get more and more people",
    "who are doing that",
    "and this ground game this grassroots",
    "effort",
    "uh i think is really uh the key to",
    "getting",
    "this done so i look forward uh",
    "myself to being on these on these calls",
    "i look forward to",
    "talking with with each and every one of",
    "you",
    "uh but i would ask you again to get get",
    "started on that",
    "right away um",
    "we have the ability working with local",
    "leaders",
    "to offer some state support and a lot of",
    "this we've already",
    "talked about and extended things such as",
    "increased rapid and rapid testing",
    "additional",
    "personal protection equipment help with",
    "contact tracing so people can quarantine",
    "and stop the spread in its tracks",
    "helping guidance with air ventilation",
    "buildings and other things",
    "look we are ohioans we always come",
    "together",
    "uh in a time of flood along the ohio",
    "river or",
    "one of our other uh rivers uh in the",
    "state",
    "uh where there's been bad fires uh",
    "when there has been tornadoes we rally",
    "together our communities just come",
    "together",
    "uh like that so we've got to do that",
    "in regard to this virus we've got to",
    "come together and",
    "go after uh this invader because we",
    "truly have in fact been",
    "invaded",
    "if you're a county eric let's look at",
    "that slide again",
    "if you're a county with a high incidence",
    "if you're up here set a goal let's say",
    "you're",
    "let's say you're mercer at 478 or you're",
    "at homes with 398.",
    "you know set the goal to to knock it",
    "down 100.",
    "set a goal to knock it down 200.",
    "whatever that goal",
    "is work in that community to get",
    "that done because when you take the",
    "cases down",
    "you're going to take the",
    "hospitalizations down and you're going",
    "to ultimately take the deaths down",
    "it's really as simple as simple as that",
    "our goal in the state should be to get",
    "every county every county should have an",
    "ultimate goal",
    "of getting under 100. now that's the",
    "high incidence",
    "we certainly we certainly have the",
    "ability to to do that",
    "and let's each one of us uh recommit",
    "uh let's look at our county and say",
    "here's where we can block this virus",
    "from spreading more",
    "we can take this action we can do that",
    "the ability to do that lies uniquely",
    "with",
    "you as the leaders in each one of our of",
    "our counties",
    "[Music]",
    "let me now turn to the lieutenant",
    "governor",
    "john thank you governor yeah i just want",
    "to reiterate",
    "uh i think that these calls that we're",
    "going to be doing are",
    "are essential uh because we need",
    "to have a local strategy a localized",
    "strategy to get at this is we see the",
    "virus spreading uh dramatically in every",
    "county in the state",
    "as you articulated well this is this",
    "this virus is spreading at the community",
    "level and the things that we do in our",
    "own personal time",
    "we need we need people basically to",
    "take ownership of the prop of the",
    "problem at the local level take action",
    "on the solutions at the local level and",
    "and it's going to take a community",
    "effort to get that done and",
    "i believe that it's going to happen i",
    "believe as you said people are going to",
    "rally to the cause they're going to set",
    "a goal they're going to be determined",
    "and we're going to begin to to move this",
    "trend in the other direction",
    "soon but it's it's not going to change",
    "without that effort",
    "uh i i would as i like to do i always",
    "like to try to give",
    "some component of our economic recovery",
    "uh as we fight the virus and the",
    "economic consequences of the virus i",
    "want to",
    "set a reminder for people look",
    "i know that they're the technology and",
    "the virus are changing the economy",
    "quickly and people need to",
    "to get retrained this is a perfect time",
    "to do it",
    "and through techcred we have the",
    "opportunity for employers of this state",
    "to upskill their employees",
    "uh to upskill somebody perhaps that they",
    "want to hire",
    "into one of these new positions as",
    "technology's changing the role of those",
    "of those jobs we will pay up to 2 000",
    "of a person's industry credentials some",
    "of these industry credentials",
    "credentials come with college credits",
    "associated with them",
    "uh this is a great opportunity for you",
    "to to engage",
    "so if you're an employer and you want to",
    "upskill one of your employees",
    "go to techcred.ohio.gov the deadline for",
    "the latest round of applications is on",
    "friday",
    "we need to get this going we talk about",
    "unemployment statistics at the macro",
    "level",
    "but we know that the impact the economic",
    "and social impact is at the individual",
    "level",
    "about everybody uh being empowered to",
    "better prepare for",
    "their futures and to help your company",
    "and to help themselves",
    "in the economy and this is one way to do",
    "it techcred.ohio.gov",
    "enroll before friday 3 p.m deadline",
    "thanks governor",
    "we're ready for questions thanks",
    "lieutenant governor governor your first",
    "question today is from adrian robbins at",
    "wcmh",
    "in columbus hi governor thank you for",
    "taking questions today",
    "uh earlier today president trump tweeted",
    "fake news media",
    "is going full on covid coveted kobet we",
    "are rounding the turn",
    "now you've been in a pretty grim picture",
    "today who should ohioans be listening",
    "to when the president say we're rounding",
    "a turn and you're asking people to",
    "double down",
    "well i can only speak what i see in ohio",
    "and",
    "what we see in ohio is um we're not",
    "we're not headed the right direction",
    "we're headed the wrong direction uh it",
    "doesn't mean we can't turn",
    "around look i i i give the president a",
    "lot of credit",
    "uh for putting the money in very very",
    "early",
    "uh to develop the vaccine we're going to",
    "have a vaccine",
    "and cavalry is coming to the rescue or",
    "whatever your analogy you want you want",
    "to have so there's hope out there",
    "we're going to get through this uh we're",
    "going to get those vaccines it's going",
    "to take a while to get it all out and",
    "get enough people",
    "um vaccinated but you know",
    "we can do that but we've got to get",
    "through the next few months",
    "and to get through the next few months",
    "and keep businesses open",
    "keep kids in school keep things going",
    "we've got to do the things that i talked",
    "about today",
    "that's that's the we we know the recipe",
    "as our two coaches said we know what",
    "works we've got the game plan",
    "let's just execute on it next question",
    "is from christa frost at wbns in",
    "columbus",
    "yeah so at the beginning of the pandemic",
    "many things were shut down so we could",
    "flatten the curve and we're seeing a",
    "spike",
    "now obviously so what's the difference",
    "from",
    "then to right now should people expect",
    "to see another shutdown",
    "yeah uh here's the here's the difference",
    "uh we already did that once",
    "and we saved a lot of lives and ohio",
    "high ones should be very proud of where",
    "they are",
    "or what they've done in the past twice",
    "they have been able to knock this virus",
    "down",
    "but we know that a complete shutdown",
    "will have other consequences that are",
    "not good",
    "and so you know we had kids who lost",
    "march april lost a few months",
    "they had remote but uh they were",
    "certainly not in class",
    "you know we we had businesses that were",
    "shut down",
    "uh we had other other bad things come",
    "uh mental health problems etc",
    "so we don't want to shut down again",
    "we've done it once",
    "um we just can't do it twice",
    "or we certainly don't want to do it",
    "twice we want to avoid doing it twice",
    "and so the game plan i've outlined today",
    "very short very simple very easy will",
    "get us out of this",
    "and we will not have to shut down but if",
    "we don't do this and if we don't fight",
    "this battle",
    "county by county city by city village",
    "by village if we do not fight in that",
    "way",
    "we will one way or the other be shut",
    "down",
    "and we will be shut down because the",
    "spread will be so bad",
    "so look we we have thanksgiving looming",
    "we have christmas coming up uh it is",
    "getting darker",
    "uh in the sense that we're losing light",
    "and um",
    "you know look people are inside more",
    "just because of the cold and because of",
    "the",
    "uh when it gets dark so people are",
    "inside a lot more and we know it's it it",
    "can be a very dangerous time for the",
    "spread",
    "uh of of this virus so we gotta",
    "make a correction really quick um",
    "that's what we got to do but we know how",
    "to do it we've done it twice before",
    "i'm asking ohioans to do it again",
    "governor if i could if i could add to",
    "that",
    "answer the the place that the the",
    "governor highlighted earlier today",
    "the spread is not coming from businesses",
    "it's coming from what people are doing",
    "on their own personal time",
    "and so a shutdown doesn't affect that",
    "we're trying to target the solutions to",
    "get people to own it",
    "at the personal level because that's",
    "where the solutions lie",
    "is what we do on our own personal time",
    "businesses have shown that they",
    "they can create a safe environment and",
    "and they're doing that across the state",
    "and and we need to we need to focus the",
    "solutions on where the problem is",
    "some of my best friends in the",
    "legislature talk about personal",
    "responsibility i'm a big believer in",
    "personal responsibility too i know they",
    "are",
    "this is about personal responsibility",
    "and what each and every one of us can do",
    "next question is from scott hallas at",
    "the zenith daily gazette",
    "hey scott hey governor how are you",
    "i'm good uh just a question",
    "we've got uh winter sports coming up in",
    "ohio teams are starting to try out",
    "they're picking their teams and i know",
    "um there's limits you know as far as",
    "there was limits for volleyball how many",
    "people can be in a gym or whatever",
    "has there been any thought given yet to",
    "what's going to happen",
    "in the winter when you have wrestling",
    "basketball inside",
    "swimming you know bowling all inside the",
    "same places are there going to be",
    "more stricter limits because of the",
    "community spread because people are",
    "inside more now",
    "i had a superintendent today this",
    "morning email me and say",
    "recommend that we you know postpone",
    "sports winter sports uh",
    "into into january to see where we are i",
    "don't know the answer to scott",
    "but i know what i can tell",
    "you and everyone else is despite we are",
    "seeing this",
    "what we're seeing threatens everything",
    "that we want to do",
    "we've got to get control over it",
    "next question is from alex ebert at",
    "bloomberg",
    "for taking our questions governor billy",
    "this spring dr amy acton",
    "said that projections showed there would",
    "be about 10 000 news cases per day",
    "then later after um steps were taken",
    "we saw that that projection decreased to",
    "about 1 600 cases per day",
    "we've now blown past that sort of",
    "projection on a daily case basis",
    "what are the current projections and",
    "your health experts saying we could see",
    "as far as a peak of new cases per day",
    "goes in ohio",
    "if things continue the way they're",
    "headed thanks for your time yeah we",
    "reviewed a",
    "a a projection yesterday",
    "um it didn't come from ohio uh so i'm",
    "going back to our ohio",
    "folks and take a look at it but it was",
    "it was this projection was stunningly",
    "high",
    "uh it was so high that i said you know",
    "we got to go look at",
    "let's try our ohio folks see what they",
    "say so i don't have an answer today",
    "i'm going back to some of the folks that",
    "do modeling",
    "at our universities here in ohio and",
    "kind of see what they look",
    "what they come up with you know again i",
    "think the caution always",
    "on this is what assumptions are you",
    "are you using you know what",
    "and one of the one of the key",
    "ingredients i will tell everybody as we",
    "talk to modelers",
    "is what percentage of people are wearing",
    "masks",
    "that's that's always one of the key",
    "inputs",
    "into that so we know from them and",
    "and from what we've seen in ohio that",
    "worry mask is fundamentally important",
    "uh it is back and that is as i said at",
    "the beginning back to basics",
    "so there are things that we know will",
    "will change the outcome",
    "next question is from dan derose at wo",
    "in cleveland",
    "good afternoon governor how are you i'm",
    "good thank you",
    "so i know you're not a fan of the uh",
    "phrase herd immunity you prefer",
    "community immunities so my question is",
    "sort of along that line",
    "when you look at 202",
    "when you look at 202 positive 202",
    "000 positive cases in the state of ohio",
    "that represents about",
    "1.6 of the state that's actually tested",
    "positive",
    "granted we know that to be much higher",
    "not everybody got tested early on",
    "that had symptoms and probably had it so",
    "experts are saying",
    "maybe around five percent at least here",
    "in cuyahoga county",
    "are we seeing higher numbers now because",
    "we did such a good job",
    "early on uh and we did close down early",
    "and we did wear masks in july is this",
    "just",
    "sort of the vaccine not going away",
    "and we're not ever going to be able to",
    "avoid",
    "getting above one and a half percent or",
    "five percent people getting infected",
    "well clearly",
    "the more people you have infected um",
    "you know assuming that",
    "this immunity lasts and we've seen some",
    "cases where someone got it again",
    "so i'm not i don't pretend to be the",
    "medical expert",
    "but obviously if you've had more people",
    "get it then",
    "if they do have immunity you would",
    "assume there's fewer people who can get",
    "it in the future",
    "but you know that would be a horrible",
    "horrible strategy",
    "it would be a strategy that basically",
    "said let's everybody get everybody",
    "exposed",
    "and there's no there's no reputable",
    "scientist",
    "that i'm aware in the world who thinks",
    "we could reach",
    "herd immunity in any close proximity of",
    "time",
    "i've heard numbers from 60 to 70 75",
    "percent",
    "you need to get the hurt immunity again",
    "i'm not the scientist",
    "but we're not even beginning down that",
    "pathway",
    "so you know",
    "we are seeing the spread because it's",
    "spreading",
    "and because we're not doing the",
    "interventions that we need",
    "and we know the things today you know we",
    "know a lot more than we knew in march",
    "in february we know these masks are",
    "phenomenally effective",
    "not perfect but they're phenomenally",
    "effective",
    "so you know the idea that we get hurt",
    "immunity community immunity whatever you",
    "want to call it",
    "it's just it's been a discredited theory",
    "uh in regard to the coronavirus because",
    "no one thinks we can get it in a",
    "reasonable period of time",
    "the other thing i would say is that by",
    "saving lives early",
    "um you know in in in",
    "we not only are saving lives but if",
    "someone",
    "i mean i said early on at one of these",
    "press conferences if you had a choice of",
    "getting it in february or getting it in",
    "in november you'd be better off getting",
    "it in november we don't want anybody to",
    "get it",
    "but doctors are no more and they know",
    "how to treat it more",
    "still not curable still losing people",
    "every single day but they certainly",
    "they certainly know more so the idea",
    "that we can herd immunity our way out of",
    "this is is been discredited by everybody",
    "the only way you get the hurt immunity",
    "or community immunity is we're going to",
    "get it is through",
    "vaccine next question",
    "and it will come next question is from",
    "andy chow at ohio public radio and",
    "television",
    "andy hi governor um",
    "back in may there were leaders",
    "in the legislature that wanted you to",
    "start addressing the pandemic county by",
    "county",
    "rather than a statewide perspective now",
    "it sounds like the game plan is going to",
    "more of a county by county level what's",
    "the explanation",
    "for the game plan there and then do you",
    "also expect",
    "possibly counties to be shutting down",
    "businesses on a county level",
    "well let me talk about that for a moment",
    "you know we made the decision uh early",
    "on",
    "uh to treat the state as one unit",
    "a part of that was legal uh we believe",
    "that for example in regard to bars you",
    "have to",
    "treat it late you have to treat it",
    "equally we know that",
    "legally if there's any discrepancy",
    "between one county another",
    "you know the burden's upon you to show",
    "why you're making a distinction but",
    "but that had to do with shutdown um",
    "what we're talking about now is really",
    "taking community work up to a",
    "higher level we've got",
    "a lot of great mayors a lot of great",
    "commissioners a lot of great",
    "health commissioners a lot of great",
    "leaders in the faith-based community who",
    "are doing a bang-up job",
    "all we're saying really today is let's",
    "reconcentrate our efforts",
    "because whatever your county was before",
    "it's higher today",
    "and for those counties in the spring",
    "where it was clearly in the",
    "in the urban areas",
    "if you lived in a rural area you were",
    "not having much impact",
    "now no matter where you are you've got",
    "to go deal with it so what we're simply",
    "saying particularly to the smaller",
    "counties",
    "who had avoided this for a long time",
    "we're simply saying hey",
    "we gotta we need you we need you to come",
    "in we need you to rally",
    "um and and to do that but this is not",
    "the state backing off nor is it nor is",
    "it",
    "am i saying i shirk any responsibility",
    "i'm just i'm just saying we need more",
    "players on the field",
    "we need more troops on the ground uh we",
    "got to all be in and for the counties",
    "that",
    "could get by in the spring and not be in",
    "i understand that",
    "they weren't seeing it today they're",
    "seeing it today their nursing homes are",
    "threatened",
    "so their hospitals are threatened and",
    "their schools are threatened",
    "that's the difference next question is",
    "from jeff",
    "redick at wsyx in columbus",
    "good afternoon governor the",
    "big 10 continues to have its games",
    "obviously",
    "here in columbus local health experts",
    "are worried about the house parties",
    "the um the unofficial tailgating going",
    "on in neighborhoods",
    "they've asked the big ten to reconsider",
    "having night games",
    "or cable games because not everyone has",
    "access they have to crowd together to be",
    "able to watch the game",
    "but they feel they're being ignored by",
    "the big ten",
    "would you reach out on their behalf have",
    "you been approached about doing so",
    "does this worry you",
    "well to answer the second the one",
    "question uh i not thought about that",
    "as far as when the games were scheduled",
    "or where the games were",
    "what they were available on so we",
    "certainly can take it take a look at",
    "that",
    "my concern about big ten football has",
    "always been not what goes on the field",
    "you know they're following very strict",
    "protocols it doesn't mean you can't have",
    "spread they certainly could",
    "but i i do believe that the athletes who",
    "are under that protocol",
    "who have a great great great desire to",
    "play uh",
    "probably are certainly safe and maybe",
    "safer than",
    "it's just an average student um but what",
    "i've always worried about and continue",
    "to worry about i'm",
    "just talking to amir ginther today and",
    "talking to some other mayors",
    "uh is simply what do people do",
    "you know they're watching the game you",
    "know uh and they got and they bring a",
    "bunch of people together and that's why",
    "you know",
    "again this is what i said earlier on you",
    "know",
    "really reconsider those you know i know",
    "it's more fun watching ohio state when",
    "you got",
    "you know a bunch of people and you're",
    "drinking beer or you're eating something",
    "and pizza or",
    "drinking pop whatever but um",
    "let's enjoy the season let's enjoy the",
    "game but let's don't get",
    "the virus because of it",
    "next question is from danny eldridge at",
    "hannah news service",
    "hello governor um so uh i know when",
    "people ask you about the president you",
    "like to say you want to focus on ohio",
    "well",
    "the president came to circleville in",
    "central ohio and you greeted him",
    "at the airport you know tacitly",
    "endorsing",
    "this huge event that he was holding in",
    "ohio during",
    "you know a time that's really bad",
    "what does that send how do you justify",
    "that",
    "i justify it this way i'm the governor",
    "of the state of ohio the president of",
    "the united states",
    "comes here i want to greet him",
    "it's important for the governor of ohio",
    "to have a relationship",
    "with the president of the united states",
    "and i think that is that is important i",
    "was not at the rally",
    "look i've made it very very clear that",
    "whether you're at a rally whether you're",
    "a protest",
    "whether you're at a football watching",
    "party",
    "gathering together without mask with",
    "virus",
    "that has spread as deeply as it has into",
    "every",
    "crevice in the state of ohio is a",
    "mistake",
    "and so you know i again would urge",
    "people",
    "wear masks whatever you whatever you're",
    "doing and those",
    "particularly if you're close to someone",
    "else and you can't you can't do the",
    "social distancing",
    "so don't please understand exactly what",
    "it was",
    "it was the governor of ohio greeting the",
    "president of the united states",
    "and i've also endorsed him and i",
    "continue to endorse him",
    "next question is from laura bischoff at",
    "the dayton daily news",
    "hey laura hey governor um so 82 counties",
    "are this high incidence of red or orange",
    "none are at purple is your",
    "administration not categorizing",
    "counties as purple until after the",
    "election",
    "no no no no oh no this is all on data",
    "or data people tell me what it is on on",
    "wednesday",
    "uh or usually it's late uh late",
    "wednesday",
    "uh sometimes early thursday uh they",
    "confirm it again",
    "right before the the press on the press",
    "event at two o'clock on thursday and i",
    "report whatever they tell me to report",
    "no no this is on data basically on data",
    "we've got three counties",
    "that could go um purple",
    "but remember under the criteria",
    "they have to continue you know they",
    "can't just still be",
    "they've got to see the increase continue",
    "to go for that last week",
    "so they've got to do it two weeks in a",
    "row they've got to have that growth that",
    "significant growth for two straight",
    "weeks",
    "i mean we could have shown that's the",
    "way we set it up it takes two weeks in a",
    "row to do that",
    "so this would be the second week for",
    "those three counties and i don't know",
    "whether they're going to hit that or not",
    "they hit it we'll call it",
    "next question is from max philby at the",
    "columbus dispatch",
    "afternoon governor i know you've said",
    "that you would like to avoid",
    "another economic shutdown like we had",
    "earlier this year so with that being",
    "said could we see",
    "more along the lines of uh capacity",
    "limits and things like that at bars",
    "restaurants and stores maybe more so",
    "than just the six",
    "foot distancing that we have in place",
    "now",
    "yeah i'm really",
    "i mean they've they've got to those",
    "those outliers have got to",
    "do what they should be doing and if they",
    "don't there needs to be consequences and",
    "there will be in fact be consequences",
    "but answer your question i'm not i'm not",
    "taking anything off the table please",
    "don't misunderstand",
    "you know as governor of the state i'm",
    "going to do what i have to do",
    "but i know as john houston said and he's",
    "spot on",
    "that where we're seeing the spread the",
    "big spread at least",
    "uh generally is in people's own personal",
    "lives",
    "that's why we ask business to jump in",
    "and tell you talk to your employees",
    "about being safe when they go home",
    "um you know that's that's why uh we're",
    "talking to any community leaders to talk",
    "to people about that because",
    "that is an area that you know we don't",
    "have any any really control over what",
    "people do in their own home",
    "uh you know what they do in their in",
    "their personal time",
    "those things um that's where personal",
    "responsibility has got to come in",
    "and that's what will really make the",
    "difference but no i'm not taking",
    "anything off the table",
    "we'll do what we have to do",
    "next question is from amanda van allen",
    "at wews",
    "in cleveland hey governor",
    "um i know you talked about this a little",
    "bit a couple questions ago but i wanted",
    "to clarify something",
    "um i know that the counties usually",
    "change over color",
    "every thursday i mean you talked about",
    "three counties potentially going purple",
    "i'm most concerned about cuyahoga county",
    "um over here in cleveland is that one of",
    "the three counties",
    "yeah i mean they're you know and this is",
    "not a news today i mean this is",
    "their three counties were on the watch",
    "list last thursday",
    "what that simply means is they hit the",
    "criteria last thursday",
    "but under our way we set this up months",
    "ago",
    "they've got to hit that twice in a row",
    "and so we're going to see",
    "you know thursday what they hit whether",
    "or not they hit they become purple or",
    "they don't become perfect",
    "again i would just caution everyone you",
    "know you got to look at two things look",
    "at",
    "look at how much spread you've had how",
    "many new cases you've had in the last",
    "two weeks",
    "per hundred thousand that's very very",
    "important the other thing is look at the",
    "color",
    "and when you get to purple what that's",
    "indicating is you got potential problems",
    "in your hospitals",
    "that's why purple is so so important",
    "next question is from jesse ballmer at",
    "the cincinnati enquirer",
    "jesse hello governor um",
    "my question is about like the size of",
    "events like the",
    "rally in circle bill this weekend i",
    "guess will you ask presidential",
    "candidates to limit the size of their",
    "events similar to the ask",
    "that you're making to people attending",
    "football parties this weekend",
    "look we're asking people",
    "consistently to wear a mask",
    "you could have a football party if you",
    "wore a mask",
    "uh i mean you have to be careful you'd",
    "have to you know you've got to make that",
    "judgment call",
    "but wearing the mask is what we're",
    "asking people to do",
    "you know i wouldn't suggest they do a",
    "big party for a football game",
    "uh if they can be outside and wearing",
    "masks and watching a screen",
    "that may make some sense i mean every",
    "situation is",
    "is different and so i did ask",
    "last week in anticipation of the rally",
    "in circleville everyone to to wear",
    "a mask and i will",
    "you know continue uh to to do that there",
    "was an event",
    "there was an event uh a an event",
    "uh a trump event in youngstown i picked",
    "up the phone",
    "the morning it was going to occur and",
    "called into the radio station",
    "and talk talked on the dan river show",
    "the reason i called in is i wanted to",
    "say",
    "please we're you know we're a mask if",
    "you're going to this event",
    "so i think you know i think i'm",
    "consistent in that",
    "next question is from josh roltenberg at",
    "spectrum news",
    "hi governor how are you josh you just",
    "said about",
    "20 minutes ago if we don't fight this",
    "county by county village by village we",
    "will one way or another be shut down",
    "because spread will be so bad",
    "so at what point will we be shut down is",
    "it when",
    "counties reach purple what what is that",
    "exactly",
    "josh i i've said this before and let me",
    "let me kind of try to articulate it",
    "maybe better",
    "what will happen is what we're already",
    "starting to see happen in",
    "some communities where the schools have",
    "to go remote",
    "but they don't want to go remote or",
    "where they planned on",
    "coming out a remote and they stay remote",
    "because",
    "they're seeing spread we're seeing",
    "schools that are have been",
    "totally open five days a week that have",
    "had to pull back for a couple weeks",
    "why because they had an outbreak in",
    "their school",
    "you'll see it in in nursing homes",
    "the spread in nursing homes comes from",
    "people generally who are",
    "going in out the door and most of those",
    "people work there or they bring supplies",
    "there",
    "so when you've got broad spread in the",
    "community you're going to see broad",
    "spread in the in",
    "eventually you're going to see spread in",
    "the nursing home no matter how",
    "how much they try same with hospitals i",
    "mean you",
    "will start to see things happen in",
    "hospitals",
    "where they'll say we're not going to do",
    "uh elective surgeries or we're going to",
    "pull back from this or pull back from",
    "that",
    "so look we're watching it we look at the",
    "data every single day",
    "but to this point we still have it",
    "within our control",
    "it's still within the control",
    "we can have it within our control",
    "and that is if the people of county",
    "after county get mad",
    "and say we're not going to put up with",
    "this virus anymore we're going to go",
    "beat it",
    "that's what we need to have happen and",
    "we've got to do it",
    "and we can do it governor next question",
    "is the last question for today and it",
    "belongs to john london",
    "at wlwt in cincinnati hey john",
    "the governor you uh said a moment ago",
    "the heaviest lift is with uh personal",
    "lives and",
    "that you're going to meet with the watch",
    "list counties and start that right after",
    "this briefing",
    "hamilton county being one of course i'm",
    "interested to know who you will meet",
    "with and and what do you want",
    "in place governor besides uh better",
    "messaging",
    "and encouraging mass square yeah i",
    "i think that you know particularly with",
    "smaller counties",
    "i i think there needs to be an",
    "acceptance that we got to go win",
    "uh that this is a battle worth fighting",
    "uh",
    "and we need all the county commissioners",
    "uh frankly",
    "uh or or county executives uh in case of",
    "cuyahoga county for example",
    "summit county uh uh you know we need",
    "all the all the opinion leaders um yeah",
    "we need everybody in",
    "in the game so i'm looking generally for",
    "about 10 people on these calls",
    "and and look it's going to be an",
    "exchange i'm not going to sit there and",
    "tell them what to do it's going to be an",
    "exchange",
    "we're going to make sure they understand",
    "what resources we have that we can bring",
    "in",
    "i've always found talking with people",
    "communication is good",
    "we've had a lot of communication during",
    "this but we're going to make this more",
    "formal",
    "and so we just we'll go go right down",
    "down",
    "down the line i mean i i talked to you",
    "know mira cranley",
    "twice a week at least and i talked to",
    "mayors and commissioners",
    "all over the state but we're going to do",
    "this more formally and just",
    "methodically do it",
    "let me close by saying uh on this date",
    "in 1858 our 26th president theodore",
    "roosevelt was born",
    "and let me say something that from his",
    "1905",
    "inaugural address which i think is",
    "pertinent to what's going on today",
    "and i quote from theodore roosevelt much",
    "has been given us and much will",
    "rightfully be expected from us we have",
    "duties",
    "to others and duties to ourselves",
    "and we can shirk neither it's time for",
    "us",
    "to to go to battle and uh to go defeat",
    "the virus",
    "we'll see y'all in a couple days thank",
    "you",
    "[Music]",
    "[Applause]",
    "you"
  ]
}