window.transcript = {
  "videoId": "x5YtgOL5iB4",
  "title": "August 6, 2020 - Governor Mike DeWine Announcement",
  "dateString": "Streamed live on Aug 6, 2020",
  "date": "2020-08-06T00:00:00",
  "timestamps": [
    "00:00",
    "00:33",
    "00:42",
    "00:56",
    "00:57",
    "00:58",
    "00:58",
    "01:06",
    "01:07",
    "01:15",
    "01:15",
    "01:24",
    "01:27",
    "01:28",
    "01:38",
    "01:39",
    "02:20",
    "02:22",
    "03:36",
    "04:42",
    "04:47",
    "06:52",
    "06:53",
    "09:37",
    "09:58",
    "10:02",
    "10:04",
    "10:16",
    "10:24",
    "10:27",
    "10:31",
    "10:34",
    "10:37",
    "10:38",
    "10:41",
    "10:43",
    "10:46",
    "10:47",
    "10:49",
    "10:51",
    "10:55",
    "10:57",
    "10:59",
    "11:03",
    "11:05",
    "11:07",
    "11:09",
    "11:10",
    "11:14",
    "11:17",
    "11:19",
    "11:20",
    "11:24",
    "11:24",
    "11:28",
    "11:31",
    "11:33",
    "11:38",
    "11:42",
    "11:45",
    "11:45",
    "11:48",
    "11:49",
    "11:53",
    "11:57",
    "11:59",
    "12:01",
    "12:03",
    "12:05",
    "12:07",
    "12:08",
    "12:11",
    "12:12",
    "12:15",
    "12:15",
    "12:18",
    "12:19",
    "12:22",
    "12:24",
    "12:25",
    "12:27",
    "12:29",
    "12:30",
    "12:32",
    "12:34",
    "12:37",
    "12:39",
    "12:42",
    "12:42",
    "12:44",
    "12:46",
    "12:48",
    "12:49",
    "12:51",
    "12:52",
    "12:55",
    "12:58",
    "12:59",
    "13:01",
    "13:04",
    "13:05",
    "13:07",
    "13:09",
    "13:13",
    "13:16",
    "13:19",
    "13:22",
    "13:24",
    "13:26",
    "13:29",
    "13:32",
    "13:35",
    "13:37",
    "13:40",
    "13:42",
    "13:44",
    "13:46",
    "13:49",
    "13:50",
    "13:51",
    "13:54",
    "13:55",
    "13:58",
    "13:59",
    "14:01",
    "14:02",
    "14:05",
    "14:06",
    "14:09",
    "14:11",
    "14:12",
    "14:15",
    "14:18",
    "14:22",
    "14:25",
    "14:27",
    "14:29",
    "14:30",
    "14:32",
    "14:34",
    "14:36",
    "14:38",
    "14:42",
    "14:44",
    "14:45",
    "14:49",
    "14:53",
    "15:10",
    "15:24",
    "15:27",
    "15:30",
    "15:33",
    "15:33",
    "15:37",
    "15:38",
    "15:40",
    "15:41",
    "15:44",
    "15:46",
    "15:48",
    "15:50",
    "15:51",
    "15:52",
    "15:54",
    "15:56",
    "15:58",
    "15:59",
    "16:01",
    "16:03",
    "16:04",
    "16:06",
    "16:09",
    "16:11",
    "16:14",
    "16:18",
    "16:22",
    "16:24",
    "16:28",
    "16:30",
    "16:31",
    "16:35",
    "16:37",
    "16:38",
    "16:42",
    "16:44",
    "16:45",
    "16:46",
    "16:49",
    "16:50",
    "16:52",
    "16:53",
    "16:56",
    "16:59",
    "17:01",
    "17:02",
    "17:05",
    "17:09",
    "17:11",
    "17:12",
    "17:15",
    "17:16",
    "17:20",
    "17:23",
    "17:25",
    "17:26",
    "17:27",
    "17:30",
    "17:32",
    "17:34",
    "17:35",
    "17:38",
    "17:39",
    "17:41",
    "17:43",
    "17:46",
    "17:47",
    "17:51",
    "17:53",
    "17:54",
    "18:00",
    "18:02",
    "18:09",
    "18:11",
    "18:12",
    "18:13",
    "18:16",
    "18:18",
    "18:20",
    "18:22",
    "18:25",
    "18:28",
    "18:30",
    "18:32",
    "18:34",
    "18:36",
    "18:38",
    "18:39",
    "18:41",
    "18:43",
    "18:44",
    "18:46",
    "18:48",
    "18:48",
    "18:50",
    "18:52",
    "18:53",
    "18:56",
    "18:58",
    "19:00",
    "19:01",
    "19:02",
    "19:04",
    "19:08",
    "19:10",
    "19:12",
    "19:14",
    "19:16",
    "19:20",
    "19:21",
    "19:23",
    "19:24",
    "19:27",
    "19:29",
    "19:32",
    "19:34",
    "19:38",
    "19:41",
    "19:42",
    "19:46",
    "19:47",
    "19:49",
    "19:51",
    "19:53",
    "19:56",
    "20:00",
    "20:03",
    "20:05",
    "20:06",
    "20:08",
    "20:10",
    "20:13",
    "20:14",
    "20:16",
    "20:17",
    "20:20",
    "20:22",
    "20:25",
    "20:27",
    "20:29",
    "20:32",
    "20:33",
    "20:36",
    "20:40",
    "20:42",
    "20:43",
    "20:47",
    "20:50",
    "20:51",
    "20:55",
    "20:58",
    "20:59",
    "21:00",
    "21:02",
    "21:05",
    "21:06",
    "21:08",
    "21:10",
    "21:12",
    "21:14",
    "21:17",
    "21:18",
    "21:21",
    "21:26",
    "21:29",
    "21:32",
    "21:34",
    "21:35",
    "21:37",
    "21:40",
    "21:41",
    "21:44",
    "21:45",
    "21:47",
    "21:49",
    "21:51",
    "21:52",
    "21:55",
    "21:58",
    "22:01",
    "22:02",
    "22:03",
    "22:05",
    "22:06",
    "22:08",
    "22:10",
    "22:13",
    "22:14",
    "22:16",
    "22:18",
    "22:21",
    "22:23",
    "22:25",
    "22:27",
    "22:30",
    "22:32",
    "22:34",
    "22:36",
    "22:40",
    "22:42",
    "22:44",
    "22:46",
    "22:47",
    "22:48",
    "22:50",
    "22:53",
    "22:55",
    "22:56",
    "22:58",
    "23:00",
    "23:01",
    "23:04",
    "23:06",
    "23:09",
    "23:10",
    "23:13",
    "23:16",
    "23:17",
    "23:20",
    "23:23",
    "23:26",
    "23:27",
    "23:30",
    "23:31",
    "23:34",
    "23:37",
    "23:39",
    "23:40",
    "23:42",
    "23:44",
    "23:48",
    "23:48",
    "23:50",
    "23:52",
    "23:53",
    "23:56",
    "23:59",
    "24:01",
    "24:03",
    "24:06",
    "24:10",
    "24:12",
    "24:15",
    "24:17",
    "24:18",
    "24:19",
    "24:24",
    "24:25",
    "24:28",
    "24:31",
    "24:31",
    "24:34",
    "24:34",
    "24:38",
    "24:40",
    "24:42",
    "24:45",
    "24:46",
    "24:48",
    "24:50",
    "24:53",
    "24:54",
    "24:56",
    "24:58",
    "25:01",
    "25:04",
    "25:07",
    "25:08",
    "25:12",
    "25:14",
    "25:16",
    "25:18",
    "25:20",
    "25:23",
    "25:26",
    "25:27",
    "25:30",
    "25:33",
    "25:35",
    "25:36",
    "25:38",
    "25:40",
    "25:41",
    "25:44",
    "25:46",
    "25:47",
    "25:49",
    "25:51",
    "25:53",
    "25:55",
    "25:58",
    "25:59",
    "26:01",
    "26:02",
    "26:04",
    "26:05",
    "26:08",
    "26:09",
    "26:12",
    "26:13",
    "26:15",
    "26:18",
    "26:21",
    "26:22",
    "26:25",
    "26:27",
    "26:29",
    "26:30",
    "26:32",
    "26:33",
    "26:35",
    "26:39",
    "26:41",
    "26:45",
    "26:51",
    "26:56",
    "26:59",
    "27:01",
    "27:04",
    "27:07",
    "27:08",
    "27:11",
    "27:12",
    "27:15",
    "27:17",
    "27:22",
    "27:25",
    "27:27",
    "27:28",
    "27:29",
    "27:31",
    "27:32",
    "27:35",
    "27:36",
    "27:38",
    "27:40",
    "27:41",
    "27:43",
    "27:45",
    "27:46",
    "27:47",
    "27:51",
    "27:54",
    "27:54",
    "27:57",
    "27:59",
    "28:02",
    "28:04",
    "28:07",
    "28:09",
    "28:10",
    "28:13",
    "28:15",
    "28:17",
    "28:20",
    "28:20",
    "28:23",
    "28:25",
    "28:26",
    "28:29",
    "28:31",
    "28:32",
    "28:34",
    "28:35",
    "28:37",
    "28:39",
    "28:41",
    "28:44",
    "28:46",
    "28:47",
    "28:49",
    "28:51",
    "28:54",
    "28:55",
    "28:58",
    "28:59",
    "29:01",
    "29:03",
    "29:06",
    "29:09",
    "29:11",
    "29:13",
    "29:15",
    "29:16",
    "29:17",
    "29:19",
    "29:22",
    "29:23",
    "29:26",
    "29:28",
    "29:31",
    "29:33",
    "29:34",
    "29:36",
    "29:37",
    "29:39",
    "29:41",
    "29:42",
    "29:45",
    "29:46",
    "29:48",
    "29:49",
    "29:50",
    "29:53",
    "29:54",
    "29:57",
    "29:59",
    "30:00",
    "30:02",
    "30:03",
    "30:07",
    "30:10",
    "30:13",
    "30:17",
    "30:18",
    "30:21",
    "30:22",
    "30:25",
    "30:28",
    "30:31",
    "30:32",
    "30:35",
    "30:36",
    "30:39",
    "30:40",
    "30:42",
    "30:44",
    "30:47",
    "30:47",
    "30:50",
    "30:52",
    "30:53",
    "30:54",
    "30:58",
    "30:59",
    "31:01",
    "31:04",
    "31:05",
    "31:08",
    "31:09",
    "31:11",
    "31:12",
    "31:13",
    "31:15",
    "31:17",
    "31:19",
    "31:21",
    "31:22",
    "31:24",
    "31:26",
    "31:28",
    "31:30",
    "31:34",
    "31:36",
    "31:38",
    "31:40",
    "31:41",
    "31:43",
    "31:44",
    "31:47",
    "31:47",
    "31:50",
    "31:51",
    "31:53",
    "31:55",
    "31:55",
    "31:58",
    "32:00",
    "32:02",
    "32:04",
    "32:05",
    "32:06",
    "32:08",
    "32:10",
    "32:12",
    "32:13",
    "32:15",
    "32:17",
    "32:18",
    "32:20",
    "32:22",
    "32:23",
    "32:25",
    "32:28",
    "32:29",
    "32:31",
    "32:31",
    "32:33",
    "32:34",
    "32:35",
    "32:38",
    "32:40",
    "32:42",
    "32:44",
    "32:47",
    "32:47",
    "32:50",
    "32:51",
    "32:54",
    "32:55",
    "32:57",
    "32:59",
    "33:00",
    "33:02",
    "33:04",
    "33:06",
    "33:08",
    "33:09",
    "33:10",
    "33:12",
    "33:13",
    "33:15",
    "33:17",
    "33:19",
    "33:22",
    "33:26",
    "33:27",
    "33:29",
    "33:32",
    "33:33",
    "33:36",
    "33:38",
    "33:40",
    "33:43",
    "33:46",
    "33:49",
    "33:50",
    "33:52",
    "33:56",
    "33:58",
    "33:59",
    "34:01",
    "34:04",
    "34:07",
    "34:09",
    "34:12",
    "34:13",
    "34:16",
    "34:17",
    "34:20",
    "34:21",
    "34:24",
    "34:25",
    "34:27",
    "34:28",
    "34:30",
    "34:34",
    "34:36",
    "34:39",
    "34:41",
    "34:42",
    "34:46",
    "34:49",
    "34:51",
    "34:53",
    "34:56",
    "34:57",
    "35:00",
    "35:00",
    "35:03",
    "35:05",
    "35:07",
    "35:08",
    "35:11",
    "35:11",
    "35:13",
    "35:15",
    "35:16",
    "35:19",
    "35:21",
    "35:23",
    "35:25",
    "35:28",
    "35:29",
    "35:32",
    "35:34",
    "35:37",
    "35:38",
    "35:40",
    "35:42",
    "35:43",
    "35:47",
    "35:50",
    "35:52",
    "35:54",
    "35:56",
    "35:59",
    "36:01",
    "36:03",
    "36:04",
    "36:06",
    "36:08",
    "36:12",
    "36:13",
    "36:15",
    "36:17",
    "36:20",
    "36:20",
    "36:22",
    "36:24",
    "36:25",
    "36:27",
    "36:28",
    "36:31",
    "36:33",
    "36:35",
    "36:37",
    "36:41",
    "36:45",
    "36:49",
    "36:52",
    "36:54",
    "36:56",
    "36:57",
    "37:01",
    "37:04",
    "37:09",
    "37:12",
    "37:14",
    "37:16",
    "37:17",
    "37:19",
    "37:20",
    "37:24",
    "37:25",
    "37:29",
    "37:31",
    "37:33",
    "37:35",
    "37:36",
    "37:39",
    "37:42",
    "37:44",
    "37:46",
    "37:48",
    "37:49",
    "37:51",
    "37:52",
    "37:53",
    "37:55",
    "37:57",
    "38:00",
    "38:01",
    "38:03",
    "38:05",
    "38:20",
    "38:44",
    "38:49",
    "38:50"
  ],
  "transcripts": [
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "so",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "so",
    "[Music]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "[Applause]",
    "[Music]",
    "one other note on q as we noted",
    "[Music]",
    "so",
    "[Music]",
    "so",
    "this has been a interesting",
    "day for the dewine family i left",
    "right here in cedarville i left home at",
    "about six o'clock this morning and drove",
    "to cleveland",
    "and the idea was i was going to get",
    "tested which i did",
    "everyone who sees the president is",
    "tested so",
    "i was i was tested i went from there to",
    "the the airport",
    "and when i got to the airport found out",
    "shortly thereafter that i had tested",
    "positive",
    "so that was a big a big surprise uh",
    "obviously could not see the president",
    "and i could not greet the president it",
    "had been my intention to be there to to",
    "greet him when he",
    "flew into into cleveland uh",
    "called fran and uh headed",
    "headed back and uh stopped in in",
    "columbus uh",
    "and fran and i and some of the people",
    "who",
    "worked very very closely uh with me",
    "were tested it was not a rapid test so",
    "we don't do not have the test back",
    "yet but you know i feel fine",
    "have a headache but uh you know i",
    "i i get a lot of headaches throughout my",
    "life so",
    "a headache is not anything that unusual",
    "so",
    "besides that i i feel well so um",
    "a big surprise to me and certainly a big",
    "surprise to our family",
    "when i found out i called fran and i",
    "called each of our",
    "seven children because i figured the",
    "news would be out pretty quickly so i",
    "want them to hear that",
    "directly from me and i was able to reach",
    "all of them",
    "and so here we are friend i just got",
    "back",
    "here uh in cedarville i guess about a",
    "half an hour ago",
    "so more than happy to take any any",
    "questions",
    "just a reminder for reporters you will",
    "remain on mute uh",
    "until your question is called uh if you",
    "wish to ask a question",
    "please mention so in the zoom chat",
    "governor our first question will be from",
    "kevin landers at wbns 10 tv in columbus",
    "hello governor can you hear me kevin",
    "i can i can hear you well kevin thank",
    "you very",
    "very good i hope you're doing well thank",
    "you so much for taking the time",
    "um governor do you have any idea where",
    "you may have",
    "contacted this virus and considering",
    "your age",
    "what have doctors told you about your",
    "recovery from it thank you",
    "well they haven't told me anything but",
    "i've read enough about it",
    "uh you know just have some idea what",
    "what we're dealing with",
    "uh so we've not had any discussion with",
    "any doctor about",
    "about that um uh",
    "you know so where where did i get it",
    "i have no idea um you know",
    "you're watching me on the front porch uh",
    "at our home home that we've lived in",
    "since 1974.",
    "um and uh you know we i",
    "basically since uh the virus came",
    "on since we started dealing with the",
    "coronavirus in march",
    "fran and i have lived out of here we",
    "were living out here every week",
    "during the weekend but we left the",
    "governor's residence we came here",
    "we have a farm that goes down that way",
    "so",
    "you know we're very very careful with",
    "with who we see uh we have two daughters",
    "that live down the road",
    "we have four grandchildren uh but you",
    "know even with them",
    "uh you know we were a mask uh we walk",
    "down there",
    "uh we keep our distance uh both our both",
    "our daughters",
    "are are pregnant uh expecting babies and",
    "we're very excited about that",
    "uh but we you know we keep our distance",
    "there uh as far as our office",
    "um you know there's really four people",
    "down that way",
    "i see these four people only uh on",
    "tuesdays and thursdays",
    "or eric who's behind the camera who you",
    "hear me always talking about he's also",
    "behind the camera today he was also",
    "tested today",
    "you know i'll see him if we do a remote",
    "tv shot we did",
    "cuomo last night cnn we did it from",
    "right in here in the house and uh you",
    "know he was there so",
    "with those four people uh",
    "that's really about about it um",
    "and uh you know we i bear",
    "uh",
    "well we've got a little uh pause here i",
    "guess",
    "whoever has the next question the next",
    "question",
    "is from jason uh lg uh at usa today uh",
    "jason please want me to ask your",
    "question",
    "hi governor thanks for taking the time",
    "to speak with us",
    "uh have you been getting tested",
    "regularly before now",
    "as a matter of uh your government's",
    "protocol",
    "what does testing look like for you",
    "other than when you publicly",
    "demonstrated a test in june",
    "and in preparation for the president's",
    "visit today",
    "that's the only other test i've had so",
    "as of right now i've had three tests two",
    "today and",
    "and that one that we did did publicly",
    "that was it",
    "i mean i had no symptoms uh you know i",
    "had no indication that",
    "no reason to think i had the coca-19 so",
    "i've not done any other testing",
    "our next question is uh from uh farnesha",
    "miri at the associated press",
    "hi governor thanks for taking the time",
    "today",
    "um what message do you hope that",
    "that this sends to ohions i mean you're",
    "someone who has",
    "um very uh very",
    "publicly worn a mask and advocated for",
    "masks",
    "and social and like you said you have",
    "not left your residence you've avoided a",
    "lot of public",
    "gatherings even when the vice president",
    "was in town",
    "um last month so what does it",
    "does this kind of say to ohioans or to",
    "the american public that someone who",
    "took all the precautions",
    "still got well it's",
    "it's you know nothing really new",
    "i mean it's what we've said and what the",
    "experts have said",
    "uh and that is that it's uh you know",
    "very contagious",
    "uh it is here it lives among us um",
    "you know we know you're always simply",
    "dealing with trying to improve your odds",
    "and",
    "when you wear a mask you're improving",
    "yards odds dramatically",
    "but that does not mean you you won't get",
    "it uh you restrict the number of people",
    "you see",
    "that improves your odds dramatically but",
    "it simply does not mean that",
    "you know there's no guarantees there's",
    "no guarantees in life",
    "uh so you know i don't think people",
    "should read a whole lot",
    "uh a lot into this uh it is uh",
    "other than what we already know which is",
    "this is a very dangerous",
    "uh you know and it's very contagious",
    "governor your next question is from",
    "origins of spectrum news",
    "here we go good afternoon governor first",
    "of all i want to wish you well i hope",
    "you",
    "uh recover quickly i want to ask",
    "about the test what type of test was it",
    "that you took that gave you the results",
    "so quickly and i'm curious how available",
    "those tests are",
    "uh you know this was a test uh",
    "that was arranged by the white house and",
    "frankly that's all i know",
    "i really did not ask i didn't think much",
    "about it uh the protocol",
    "of course is i you know i had at one",
    "point i had",
    "uh an appointment to see the president",
    "uh in washington",
    "uh they explained that i would get a",
    "test right then they'd get the results",
    "back and then i would be able to go see",
    "the president we",
    "that did not take place the meeting did",
    "not take place i think we had some",
    "conflict",
    "uh but so i don't know i mean it's",
    "obviously it's a rapid test i mean",
    "they got the results back right away uh",
    "but beyond that",
    "i can't tell you i'm sure the white",
    "house can you know can tell you exactly",
    "what the test was i don't know",
    "our next question is from laura caso of",
    "wwkyc in cleveland",
    "hi governor i'm glad to see you are",
    "doing well i do have a question uh",
    "social media kind of going crazy right",
    "now a lot of people saying",
    "uh this is an example of why i don't",
    "need to wear a mask",
    "i thought masks worked what would you",
    "say to those people who are now",
    "doubting um that whether or not they",
    "should wear a mask since clearly",
    "you have been wearing one",
    "well i've already got a few texts um you",
    "know not so nice text",
    "uh from people uh about about that it's",
    "sort of",
    "you know we told you this was all fake",
    "and uh you know we told you that we're",
    "in mass didn't matter",
    "but look we know it we know it does uh",
    "if people you know take",
    "that lesson from the fact that i",
    "apparently haven't uh that would be the",
    "wrong lesson",
    "it would be very very sad and that would",
    "that will will upset me quite a bit",
    "uh because that's not the lesson that",
    "should come from this",
    "uh you know the lesson should come from",
    "this is that we're all human",
    "uh this virus is everywhere uh this",
    "virus is very tough",
    "um and yes you can contract it even when",
    "you're being very very careful and even",
    "when you're wearing a mask",
    "but uh your odds are just dramatically",
    "better",
    "and uh my odds obviously you know",
    "weren't good that day that i contracted",
    "and and you know there's some things",
    "that are out of our control",
    "but um you know i've had some",
    "people in the past of you know mention",
    "of god and that",
    "we god and i i kind of go back to",
    "what my wife fran always has said uh as",
    "long as i've known her",
    "uh and that is you know god helps those",
    "who help themselves and so",
    "you know you try and you you do those",
    "things and usually",
    "uh you know we know it improves your",
    "odds it improves your opera",
    "your chances of not getting it or",
    "decreases the chances that you get it",
    "but there's nothing certain in life and",
    "you know",
    "that's it's uh it's it's not",
    "uh there's just no guarantees in life",
    "our next question is from matt wright of",
    "wjw in cleveland",
    "hi governor can you please tell us",
    "exactly where and when you were tested",
    "here in the cleveland area today",
    "and then also on the second test you had",
    "have you received those results",
    "and if so what's the result no this was",
    "not the",
    "second test was not a rapid test so",
    "we've not received those uh",
    "results yet uh would not expect to for a",
    "while",
    "uh you know they said we might get those",
    "later tonight",
    "but i don't i don't know you know we",
    "didn't expect to have them back this",
    "soon",
    "at all as far as location the test i was",
    "not driving the highway patrol was",
    "driving and quite candidly i didn't even",
    "look to see where we were",
    "i was uh answering emails and on the",
    "phone",
    "and paid no attention i got out i got",
    "the test i got back in the car and",
    "started working again so i'm sure that",
    "uh you know we can supply that",
    "information uh for you it was a place",
    "where testing was occurring",
    "um and you know it was public testing",
    "that day",
    "our next question is from andrew tobias",
    "at cleveland.com",
    "hi governor uh my question are uh",
    "why lieutenant governor john husted",
    "continued with the event today if you're",
    "concerned that he was exposed and then",
    "also generally i was hoping that you",
    "could address",
    "how you envision this may affect the",
    "functionings of state government",
    "well john was tested too and john john",
    "uh you know",
    "it was not it was a negative test for",
    "him so there would be no reason for him",
    "not to",
    "not to move forward i guess i'd you know",
    "um",
    "look i mean i'm going to continue uh you",
    "know",
    "i'll be quarantined for at least 14 days",
    "see how this goes uh but uh anybody",
    "knows me",
    "knows that i'm going to continue to",
    "do what i do so um",
    "you know i'm spend most days right here",
    "anyway",
    "and uh you know i'm on the phone a lot",
    "uh",
    "i'm on uh conference call a lot",
    "and um so you know",
    "so far my work is not going to be",
    "impacted we'll we'll",
    "obviously we'll see you know i don't",
    "take anything for granted and uh",
    "this virus is is a nasty thing uh we we",
    "know that",
    "it impacts some people one way and some",
    "people another way some people are much",
    "worse",
    "you know we fully fully realize that",
    "so we'll see but you know",
    "john uh houston the lieutenant governor",
    "has been",
    "intimately involved in everything we do",
    "he and i are on the phone every day",
    "i i don't know how many times but you",
    "know some days six seven eight times",
    "so that process everything's just going",
    "to continue until",
    "you know unless for some reason it",
    "cannot",
    "our next question is from marty",
    "schleyden at the ohio capitol journal",
    "good afternoon governor good afternoon",
    "hope your",
    "case is one of the asymptomatic ones",
    "thank you",
    "um so a lot of the nasty",
    "social media traffic uh seems to be",
    "predicated on the assumption that",
    "one wears a mask to keep from getting",
    "the virus",
    "it's my understanding that cloth masks",
    "are more intended to keep from",
    "giving others the virus would you talk",
    "about what you understand from your",
    "health experts about that",
    "well the experts have told me that you",
    "wear a mask primarily to protect others",
    "there is some evidence and look they",
    "continue to learn about the spread",
    "but there's some evidence that it has",
    "some benefit to you as well",
    "you know basically everybody i've been",
    "around has had a mask on",
    "uh and i've had a mask on and that's",
    "kind of been our protocol",
    "so um you know going back to",
    "five questions ago i don't know where i",
    "got it",
    "uh you know we've kind of replayed",
    "through uh you know where that could",
    "have occurred and we just don't frankly",
    "we just",
    "can't figure it out now you know",
    "everybody around me was",
    "who as i said the kind of the people",
    "that are in my bubble were tested today",
    "uh it's not a very big group uh it's the",
    "highway patrol",
    "uh those people who are assigned",
    "directly to me uh",
    "and who would be in the same car with me",
    "uh you know there is a",
    "uh because of the virus we installed",
    "there's a shield",
    "now between the the front and back",
    "that's",
    "not what we had before but uh what we",
    "have now",
    "so you know with the highway patrol uh",
    "also",
    "um you know with as i said the people",
    "sort of in the bubble the four or five",
    "people that are in the bubble",
    "uh that i interact with in in the office",
    "obviously i'm with fran uh fran's",
    "brother is here",
    "uh some i don't interact with with her",
    "brother john but",
    "uh so you know trying to rack our brain",
    "try to figure it out we haven't really",
    "figured it out",
    "you know i think when we get the test",
    "back and we get results from other",
    "people that may give us some indication",
    "governor your next question is from john",
    "london at wlwt in cincinnati",
    "hi john",
    "john can you unbeat your line please",
    "he had to leave for a live shot okay uh",
    "curtis you can you may ask his question",
    "uh sure um",
    "he was going to ask um what more the",
    "state can do",
    "so the average ohioan can get a result",
    "like he did",
    "today um and how confident is he about",
    "reliability of rapid tests uh given",
    "percentage of false negative results",
    "well i i think you know i don't have any",
    "more information than anybody else does",
    "about",
    "the reliability i mean that's been",
    "published it's been debated that's been",
    "talked about",
    "we know there are generally false pos",
    "you know false",
    "false negatives usually as i'm was what",
    "i'm told",
    "uh but i don't i don't pretend to be the",
    "expert look",
    "we've done everything that we can and",
    "we're not stopping",
    "to make sure there's more testing",
    "available",
    "you know six weeks ago five weeks ago we",
    "were about 8",
    "000 tests a day we're now averaging",
    "about 22 000 tests a day",
    "but we have things in the works uh",
    "with contracts we announced the other",
    "the other day a joint effort",
    "with maryland uh michigan and other",
    "states uh",
    "to to purchase more",
    "so we're going to continue to do",
    "everything we can to ramp up testing in",
    "in the state of ohio you know one of the",
    "things that",
    "we're going to do in fact i was on the",
    "phone",
    "i was going to talk to the president",
    "about today is pooling",
    "white house has been urging pooling for",
    "some time",
    "uh in conversations and so we're working",
    "to be able to",
    "you know do that pooling so that you can",
    "speed the testing up not the results",
    "that you get back but you can do more",
    "tests uh and so you put you know four or",
    "five tests or maybe ten tests",
    "uh in and you run them if they're all",
    "negative if it comes back negative it's",
    "negative everybody clears out",
    "uh so you know we're working on that and",
    "and",
    "to do to do more of that so",
    "you know the other two tests i've taken",
    "has been the standard test uh",
    "the one that the white house provided",
    "today uh was the only rapid test that",
    "that i've taken",
    "governor your next question is from jack",
    "windsor at wmfd in mansfield",
    "hey jack how you doing hi governor i'm",
    "well uh",
    "my daughter and i are praying for your",
    "good health sir thank you so much",
    "yes sir uh this will dovetail the last",
    "question a bit",
    "uh since this was a rapid test if this",
    "does come back as a false positive",
    "uh does this give you pause to continue",
    "with the ramping",
    "of the rapid testing program you spoke",
    "about on tuesday particularly as it",
    "relates to",
    "you know if there's a fault or a false",
    "positive in a school or on a sports team",
    "it could really",
    "shut things down or um do you just feel",
    "like",
    "we have to go forward because of the raw",
    "number of tests you feel like we need to",
    "do",
    "well jack we're going forward with all",
    "kinds of different",
    "tests and and you know going forward",
    "pushing the rapid test but we're also",
    "doing",
    "you know the other the other more",
    "conventional tests",
    "uh look i i think that you know",
    "is a is a constant re-evaluation",
    "um of everything uh",
    "we constantly evaluate where we are",
    "with the virus what we know about the",
    "virus we know more and i don't mean me",
    "i'm not a scientist but i mean",
    "collectively we know more about uh",
    "the virus today than we did in march uh",
    "same way with testing and you know the",
    "testing is evolving",
    "so um i'm not gonna prejudge we'll see",
    "what",
    "what uh happens i'm i'm sort of hoping",
    "that uh",
    "you know it was a false test but i don't",
    "i certainly don't assume that and i i",
    "i assume that it was a correct test but",
    "we'll",
    "you know we'll we'll see and when when i",
    "get my results back and friend gets her",
    "results back we'll",
    "we'll certainly share those with",
    "everybody thank you sir",
    "governor your next question is from",
    "jackie borchardt the cincinnati enquirer",
    "hi jackie hi uh glad to hear that you're",
    "doing well",
    "um i also have a follow-up on the rapid",
    "test as your case is",
    "unique compared to most ohioans and that",
    "you were able to get a result in the",
    "same day",
    "and quarantine without coming into",
    "contact with additional people",
    "the white house has been using these",
    "kinds of tests since april",
    "should the federal government have done",
    "more or could you have done more at the",
    "state level to make that testing more",
    "widely available here i don't speak for",
    "the white house i'll speak for me",
    "uh look we will look back on this",
    "uh i'm sure and there'll be things that",
    "we look back and say gee wish we'd done",
    "that i wish we'd done this",
    "all i can tell you is that we have",
    "pushed as hard as i know how to get more",
    "testing",
    "and it has been a problem but uh you",
    "know",
    "again we're at 22 000 tests on an",
    "average today",
    "uh it's a lot better than we were we got",
    "double it and then we got double it",
    "again",
    "uh so you know that's been my message as",
    "i've talked to um",
    "you know senator portman senator brown",
    "whether i talk to the white house vice",
    "president",
    "you know any help you can give us in the",
    "funding of testing",
    "because you know the private sector is",
    "moving uh things are happening",
    "and uh there's going to be more and more",
    "tests available",
    "and if if we have the money to pay for",
    "it um",
    "and we've set aside a lot of money a lot",
    "of the karazhak dollars we we've set",
    "aside for",
    "for testing not just for this month but",
    "in the in the coming months",
    "but that's what we have to do we have to",
    "do more and more testing and you're",
    "right",
    "the faster you get the test back the",
    "more you the quicker you can make a",
    "decision",
    "or or you know to you know that you the",
    "person needs to isolate",
    "uh and then you can move you you move",
    "forward so yeah we need them quicker",
    "uh and we need more of them but um you",
    "know we",
    "we put a full court press on uh for a",
    "long time",
    "on this and some of this is taking",
    "longer",
    "but as i said driving to cleveland this",
    "morning i spent",
    "i don't know a couple hours on the phone",
    "talking about testing",
    "and you know what else we can do where",
    "we can go and what the progress",
    "is there's a lot of balls in the air a",
    "lot of things that you know some things",
    "at least we have not",
    "talked to you about uh because we want",
    "to wait until we've got them",
    "until we know that they you know are",
    "ready to deploy and ready to move",
    "forward and that they're actually",
    "we can do that um so you know a lot's",
    "coming and we're going to keep pushing",
    "governor uh next question is from",
    "danielle i'm algeria at",
    "fox 45 in dayton governor dewine we've",
    "seen over 74",
    "000 ohioans recover from the virus are",
    "you remaining positive and do you feel",
    "like your face",
    "will help you better keep ohioans safe",
    "i lost the audio sorry",
    "hi governor dewine can you hear me i can",
    "hear you now if you can start again",
    "yes thank you so much thank you so much",
    "um we know that 74 over 74 000 ohioans",
    "have recovered from the virus",
    "are you hopeful and do you feel this",
    "will give you a better understanding of",
    "how to keep ohio and safe",
    "well my experience in life is that uh",
    "you learn from every experience",
    "and uh so uh you know i'm sure this will",
    "be an experience",
    "um not not one i was looking forward to",
    "not one i wanted but",
    "uh you you always learn and i certainly",
    "will look at it",
    "uh from not just from the eyes of a",
    "patient but",
    "look at it from the eyes of the governor",
    "uh and",
    "a better understanding of what other",
    "people go through governor your next",
    "question is from molly co-week at whio",
    "in dayton",
    "hi governor um how do you plan to",
    "effectively lead",
    "while you're in quarantine",
    "well i'm been leading ohio from",
    "the place you're looking at this house",
    "uh since march",
    "i go to columbus uh any day for the",
    "press conference so for",
    "you know for weeks that was every day uh",
    "now we're",
    "using usually doing two a week so i go",
    "to columbus for the press conferences",
    "i go to public safety uh go there for",
    "that",
    "um but most of the work i've done is",
    "right here",
    "uh i mean you know i walk on our farm",
    "many times people don't",
    "don't know i'm walking on the farm but",
    "i'm out walking on the farm and uh",
    "you know talking on the phone you know i",
    "talked yesterday to a number of school",
    "superintendents",
    "um we did it right here did a couple",
    "hour walk",
    "on our farm so um you know",
    "this is this is the modern world and we",
    "can certainly certainly do that it's not",
    "not what we want we'd like to pull",
    "everybody together in a in a room",
    "physically but that's just not possible",
    "today",
    "so you know we do this and so",
    "as long as i'm feeling okay uh we're",
    "obviously we'll be okay in doing this",
    "i've got a great team around me i've got",
    "a great lieutenant governor",
    "um you know i've got a team that is uh",
    "for many of them been with me uh some",
    "for decades uh so it's a team i have a",
    "great deal of trust in",
    "a team that i know the people of the",
    "state of ohio can have trust in",
    "thank you governor we have time for one",
    "last question",
    "uh next up is laura bischoff at the",
    "dayton daily news",
    "hi laura hey governor thanks for doing",
    "this and um",
    "thanks for doing these socially",
    "distanced pressers over the past several",
    "weeks",
    "yeah i guess you you're happy about that",
    "now right",
    "exactly um can you tell us uh if you",
    "have any underlying conditions",
    "other than being over age 50 that could",
    "uh put you at risk for complications",
    "yeah i've had asthma",
    "probably since i was a teenager",
    "it's under control but i take",
    "i take an inhaler regularly in the",
    "morning at night",
    "but it's you know it's it's under",
    "control but it's it is there",
    "sure uh really no other uh",
    "outstanding uh",
    "nothing really i feel good um",
    "you know i think anybody's watch me",
    "whether they agree with me or not or",
    "or not at least say i have plenty of",
    "energy so",
    "i mean i literally start the day about",
    "six o'clock in the morning",
    "i'm working and you know we kick off",
    "about eight o'clock at night usually",
    "seven or eight so that's it",
    "well eric is giving me the sign uh i",
    "guess that is it thank you all",
    "for joining us this is kind of unusual",
    "as i said we're",
    "on our front front porch here and uh",
    "i know some people at least in the in",
    "across ohio have",
    "been here before because we do our",
    "annual ice cream social here so",
    "some sometimes in the summer we didn't",
    "have it this year but the summer",
    "sometimes we have up to 2 000 people",
    "here so",
    "many of you have had a chance at least",
    "to visit this uh our home before",
    "uh so look we'll be we'll be back my",
    "intention is to do uh be part of the",
    "press conference somehow tomorrow",
    "and look forward to talking to you all",
    "then thank you very much",
    "[Music]",
    "do",
    "[Music]",
    "you"
  ]
}