window.transcript = {
  "videoId": "YLF421XY-ls",
  "title": "Ohio Governor Mike DeWine - COVID-19 Update | October 29, 2020",
  "dateString": "Streamed live on Oct 29, 2020",
  "date": "2020-10-29T00:00:00",
  "timestamps": [
    "00:00",
    "01:03",
    "03:49",
    "03:50",
    "04:51",
    "05:29",
    "05:54",
    "06:01",
    "06:07",
    "06:10",
    "06:13",
    "06:15",
    "06:18",
    "06:20",
    "06:22",
    "06:25",
    "06:27",
    "06:30",
    "06:32",
    "06:34",
    "06:38",
    "06:41",
    "06:44",
    "06:46",
    "06:47",
    "06:50",
    "06:53",
    "06:54",
    "06:57",
    "06:59",
    "07:02",
    "07:04",
    "07:08",
    "07:11",
    "07:12",
    "07:16",
    "07:17",
    "07:20",
    "07:21",
    "07:24",
    "07:27",
    "07:30",
    "07:33",
    "07:34",
    "07:38",
    "07:40",
    "07:44",
    "07:47",
    "07:50",
    "07:51",
    "07:54",
    "07:57",
    "07:58",
    "08:01",
    "08:04",
    "08:05",
    "08:08",
    "08:09",
    "08:12",
    "08:14",
    "08:17",
    "08:21",
    "08:25",
    "08:28",
    "08:29",
    "08:31",
    "08:33",
    "08:37",
    "08:40",
    "08:44",
    "08:45",
    "08:48",
    "08:49",
    "08:54",
    "08:58",
    "09:01",
    "09:05",
    "09:08",
    "09:10",
    "09:13",
    "09:15",
    "09:16",
    "09:19",
    "09:22",
    "09:24",
    "09:30",
    "09:33",
    "09:35",
    "09:36",
    "09:39",
    "09:41",
    "09:44",
    "09:44",
    "09:49",
    "09:51",
    "09:54",
    "09:57",
    "10:00",
    "10:02",
    "10:04",
    "10:05",
    "10:08",
    "10:10",
    "10:13",
    "10:16",
    "10:18",
    "10:21",
    "10:24",
    "10:26",
    "10:29",
    "10:32",
    "10:34",
    "10:36",
    "10:38",
    "10:40",
    "10:41",
    "10:45",
    "10:47",
    "10:48",
    "10:50",
    "10:52",
    "10:55",
    "10:58",
    "11:00",
    "11:01",
    "11:04",
    "11:07",
    "11:09",
    "11:10",
    "11:12",
    "11:13",
    "11:16",
    "11:18",
    "11:21",
    "11:24",
    "11:29",
    "11:32",
    "11:35",
    "11:39",
    "11:43",
    "11:46",
    "11:48",
    "11:50",
    "11:52",
    "11:54",
    "11:56",
    "11:59",
    "12:04",
    "12:08",
    "12:11",
    "12:11",
    "12:16",
    "12:18",
    "12:20",
    "12:22",
    "12:24",
    "12:26",
    "12:27",
    "12:30",
    "12:33",
    "12:37",
    "12:38",
    "12:41",
    "12:44",
    "12:46",
    "12:47",
    "12:49",
    "12:52",
    "12:54",
    "12:56",
    "12:58",
    "13:00",
    "13:02",
    "13:04",
    "13:07",
    "13:09",
    "13:12",
    "13:14",
    "13:17",
    "13:19",
    "13:21",
    "13:25",
    "13:27",
    "13:30",
    "13:34",
    "13:38",
    "13:42",
    "13:44",
    "13:47",
    "13:48",
    "13:50",
    "13:51",
    "13:53",
    "13:55",
    "13:58",
    "13:58",
    "14:03",
    "14:06",
    "14:07",
    "14:11",
    "14:12",
    "14:15",
    "14:19",
    "14:20",
    "14:21",
    "14:24",
    "14:27",
    "14:28",
    "14:30",
    "14:32",
    "14:34",
    "14:38",
    "14:39",
    "14:43",
    "14:46",
    "14:49",
    "14:50",
    "14:54",
    "14:56",
    "14:56",
    "14:59",
    "15:02",
    "15:04",
    "15:06",
    "15:08",
    "15:11",
    "15:12",
    "15:16",
    "15:18",
    "15:22",
    "15:25",
    "15:26",
    "15:27",
    "15:30",
    "15:33",
    "15:36",
    "15:38",
    "15:39",
    "15:41",
    "15:43",
    "15:45",
    "15:47",
    "15:49",
    "15:51",
    "15:52",
    "15:57",
    "16:00",
    "16:00",
    "16:06",
    "16:08",
    "16:11",
    "16:16",
    "16:19",
    "16:22",
    "16:25",
    "16:27",
    "16:29",
    "16:30",
    "16:33",
    "16:36",
    "16:39",
    "16:40",
    "16:43",
    "16:45",
    "16:47",
    "16:48",
    "16:51",
    "16:53",
    "16:56",
    "16:58",
    "17:00",
    "17:02",
    "17:03",
    "17:06",
    "17:08",
    "17:09",
    "17:12",
    "17:16",
    "17:19",
    "17:22",
    "17:25",
    "17:27",
    "17:28",
    "17:31",
    "17:34",
    "17:36",
    "17:37",
    "17:40",
    "17:42",
    "17:47",
    "17:49",
    "17:50",
    "17:53",
    "17:54",
    "17:56",
    "18:00",
    "18:04",
    "18:06",
    "18:08",
    "18:10",
    "18:13",
    "18:16",
    "18:17",
    "18:18",
    "18:20",
    "18:21",
    "18:23",
    "18:24",
    "18:26",
    "18:30",
    "18:33",
    "18:34",
    "18:36",
    "18:37",
    "18:39",
    "18:41",
    "18:42",
    "18:45",
    "18:48",
    "18:50",
    "18:52",
    "18:54",
    "18:57",
    "18:58",
    "19:01",
    "19:03",
    "19:05",
    "19:06",
    "19:07",
    "19:10",
    "19:11",
    "19:13",
    "19:16",
    "19:17",
    "19:20",
    "19:21",
    "19:23",
    "19:25",
    "19:28",
    "19:29",
    "19:32",
    "19:32",
    "19:36",
    "19:37",
    "19:39",
    "19:40",
    "19:43",
    "19:44",
    "19:47",
    "19:50",
    "19:53",
    "19:55",
    "19:58",
    "20:01",
    "20:02",
    "20:04",
    "20:07",
    "20:10",
    "20:12",
    "20:14",
    "20:16",
    "20:19",
    "20:19",
    "20:22",
    "20:23",
    "20:25",
    "20:27",
    "20:29",
    "20:30",
    "20:34",
    "20:37",
    "20:37",
    "20:40",
    "20:41",
    "20:45",
    "20:47",
    "20:49",
    "20:51",
    "20:53",
    "20:54",
    "20:55",
    "20:58",
    "21:00",
    "21:02",
    "21:03",
    "21:05",
    "21:08",
    "21:11",
    "21:12",
    "21:14",
    "21:17",
    "21:18",
    "21:21",
    "21:22",
    "21:26",
    "21:28",
    "21:30",
    "21:32",
    "21:34",
    "21:35",
    "21:36",
    "21:39",
    "21:41",
    "21:43",
    "21:44",
    "21:46",
    "21:48",
    "21:50",
    "21:52",
    "21:54",
    "21:55",
    "21:57",
    "22:00",
    "22:03",
    "22:05",
    "22:06",
    "22:08",
    "22:12",
    "22:13",
    "22:15",
    "22:17",
    "22:19",
    "22:22",
    "22:23",
    "22:25",
    "22:27",
    "22:28",
    "22:31",
    "22:32",
    "22:35",
    "22:36",
    "22:38",
    "22:39",
    "22:41",
    "22:44",
    "22:46",
    "22:48",
    "22:49",
    "22:51",
    "22:53",
    "22:55",
    "22:57",
    "22:59",
    "23:01",
    "23:02",
    "23:04",
    "23:05",
    "23:07",
    "23:10",
    "23:12",
    "23:14",
    "23:17",
    "23:19",
    "23:20",
    "23:23",
    "23:24",
    "23:25",
    "23:28",
    "23:31",
    "23:34",
    "23:37",
    "23:39",
    "23:41",
    "23:43",
    "23:45",
    "23:47",
    "23:50",
    "23:51",
    "23:52",
    "23:54",
    "23:55",
    "23:57",
    "23:59",
    "24:01",
    "24:02",
    "24:05",
    "24:06",
    "24:09",
    "24:11",
    "24:11",
    "24:14",
    "24:15",
    "24:17",
    "24:20",
    "24:22",
    "24:24",
    "24:25",
    "24:27",
    "24:29",
    "24:30",
    "24:32",
    "24:33",
    "24:34",
    "24:36",
    "24:38",
    "24:40",
    "24:42",
    "24:44",
    "24:46",
    "24:47",
    "24:48",
    "24:49",
    "24:51",
    "24:52",
    "24:54",
    "24:56",
    "24:58",
    "25:00",
    "25:02",
    "25:02",
    "25:05",
    "25:07",
    "25:10",
    "25:14",
    "25:15",
    "25:17",
    "25:19",
    "25:21",
    "25:22",
    "25:24",
    "25:28",
    "25:29",
    "25:31",
    "25:33",
    "25:36",
    "25:38",
    "25:39",
    "25:42",
    "25:45",
    "25:47",
    "25:48",
    "25:50",
    "25:52",
    "25:53",
    "25:55",
    "25:57",
    "25:57",
    "26:00",
    "26:01",
    "26:02",
    "26:04",
    "26:06",
    "26:08",
    "26:10",
    "26:11",
    "26:14",
    "26:17",
    "26:18",
    "26:19",
    "26:21",
    "26:24",
    "26:26",
    "26:28",
    "26:31",
    "26:34",
    "26:36",
    "26:38",
    "26:40",
    "26:42",
    "26:45",
    "26:47",
    "26:48",
    "26:51",
    "26:52",
    "26:55",
    "26:56",
    "26:58",
    "27:00",
    "27:02",
    "27:05",
    "27:07",
    "27:09",
    "27:10",
    "27:13",
    "27:15",
    "27:18",
    "27:19",
    "27:22",
    "27:24",
    "27:26",
    "27:27",
    "27:29",
    "27:31",
    "27:33",
    "27:37",
    "27:39",
    "27:42",
    "27:44",
    "27:47",
    "27:50",
    "27:53",
    "27:55",
    "27:57",
    "27:59",
    "28:00",
    "28:04",
    "28:06",
    "28:07",
    "28:09",
    "28:11",
    "28:14",
    "28:17",
    "28:19",
    "28:20",
    "28:23",
    "28:25",
    "28:28",
    "28:29",
    "28:31",
    "28:35",
    "28:37",
    "28:39",
    "28:41",
    "28:42",
    "28:44",
    "28:46",
    "28:49",
    "28:50",
    "28:53",
    "28:54",
    "28:57",
    "29:01",
    "29:02",
    "29:04",
    "29:06",
    "29:08",
    "29:12",
    "29:14",
    "29:16",
    "29:18",
    "29:20",
    "29:22",
    "29:25",
    "29:26",
    "29:29",
    "29:32",
    "29:33",
    "29:34",
    "29:37",
    "29:40",
    "29:41",
    "29:43",
    "29:45",
    "29:48",
    "29:49",
    "29:53",
    "29:56",
    "30:00",
    "30:02",
    "30:04",
    "30:06",
    "30:09",
    "30:11",
    "30:13",
    "30:15",
    "30:17",
    "30:19",
    "30:20",
    "30:24",
    "30:27",
    "30:31",
    "30:33",
    "30:35",
    "30:37",
    "30:39",
    "30:41",
    "30:43",
    "30:46",
    "30:50",
    "30:51",
    "30:53",
    "30:55",
    "30:57",
    "30:59",
    "31:04",
    "31:05",
    "31:07",
    "31:11",
    "31:13",
    "31:15",
    "31:18",
    "31:20",
    "31:22",
    "31:24",
    "31:26",
    "31:29",
    "31:31",
    "31:34",
    "31:35",
    "31:38",
    "31:40",
    "31:43",
    "31:43",
    "31:46",
    "31:47",
    "31:51",
    "31:54",
    "31:56",
    "31:58",
    "32:00",
    "32:02",
    "32:06",
    "32:08",
    "32:12",
    "32:14",
    "32:15",
    "32:17",
    "32:19",
    "32:20",
    "32:22",
    "32:23",
    "32:25",
    "32:26",
    "32:29",
    "32:32",
    "32:34",
    "32:35",
    "32:38",
    "32:39",
    "32:42",
    "32:44",
    "32:47",
    "32:49",
    "32:50",
    "32:52",
    "32:54",
    "32:55",
    "32:58",
    "33:00",
    "33:03",
    "33:04",
    "33:07",
    "33:09",
    "33:09",
    "33:12",
    "33:13",
    "33:15",
    "33:17",
    "33:18",
    "33:23",
    "33:25",
    "33:26",
    "33:28",
    "33:30",
    "33:32",
    "33:34",
    "33:35",
    "33:35",
    "33:38",
    "33:41",
    "33:44",
    "33:46",
    "33:49",
    "33:51",
    "33:53",
    "33:54",
    "33:55",
    "33:57",
    "34:01",
    "34:03",
    "34:06",
    "34:07",
    "34:08",
    "34:10",
    "34:12",
    "34:14",
    "34:15",
    "34:17",
    "34:19",
    "34:21",
    "34:24",
    "34:25",
    "34:27",
    "34:28",
    "34:29",
    "34:30",
    "34:33",
    "34:37",
    "34:40",
    "34:42",
    "34:45",
    "34:47",
    "34:48",
    "34:51",
    "34:54",
    "34:57",
    "35:01",
    "35:02",
    "35:07",
    "35:10",
    "35:11",
    "35:14",
    "35:15",
    "35:18",
    "35:19",
    "35:22",
    "35:27",
    "35:30",
    "35:32",
    "35:34",
    "35:36",
    "35:38",
    "35:39",
    "35:41",
    "35:42",
    "35:47",
    "35:49",
    "35:50",
    "35:53",
    "35:55",
    "35:57",
    "35:59",
    "36:01",
    "36:04",
    "36:06",
    "36:08",
    "36:09",
    "36:11",
    "36:14",
    "36:16",
    "36:17",
    "36:19",
    "36:21",
    "36:22",
    "36:24",
    "36:26",
    "36:28",
    "36:30",
    "36:33",
    "36:35",
    "36:38",
    "36:40",
    "36:41",
    "36:44",
    "36:45",
    "36:48",
    "36:49",
    "36:50",
    "36:53",
    "36:54",
    "36:56",
    "36:57",
    "36:59",
    "37:02",
    "37:04",
    "37:05",
    "37:07",
    "37:09",
    "37:11",
    "37:12",
    "37:15",
    "37:15",
    "37:17",
    "37:19",
    "37:23",
    "37:24",
    "37:25",
    "37:28",
    "37:28",
    "37:31",
    "37:34",
    "37:36",
    "37:38",
    "37:41",
    "37:42",
    "37:44",
    "37:46",
    "37:50",
    "37:51",
    "37:54",
    "37:55",
    "37:58",
    "37:58",
    "38:01",
    "38:02",
    "38:05",
    "38:07",
    "38:08",
    "38:11",
    "38:12",
    "38:14",
    "38:18",
    "38:20",
    "38:22",
    "38:25",
    "38:27",
    "38:30",
    "38:32",
    "38:35",
    "38:37",
    "38:41",
    "38:44",
    "38:46",
    "38:48",
    "38:50",
    "38:52",
    "38:54",
    "38:56",
    "38:59",
    "39:01",
    "39:02",
    "39:04",
    "39:06",
    "39:08",
    "39:11",
    "39:12",
    "39:14",
    "39:16",
    "39:18",
    "39:21",
    "39:23",
    "39:25",
    "39:27",
    "39:29",
    "39:32",
    "39:36",
    "39:36",
    "39:38",
    "39:40",
    "39:41",
    "39:43",
    "39:45",
    "39:46",
    "39:48",
    "39:50",
    "39:51",
    "39:52",
    "39:56",
    "39:58",
    "40:00",
    "40:03",
    "40:05",
    "40:08",
    "40:11",
    "40:11",
    "40:13",
    "40:15",
    "40:16",
    "40:18",
    "40:20",
    "40:22",
    "40:24",
    "40:25",
    "40:28",
    "40:29",
    "40:31",
    "40:33",
    "40:35",
    "40:38",
    "40:40",
    "40:42",
    "40:44",
    "40:46",
    "40:48",
    "40:51",
    "40:54",
    "40:57",
    "40:59",
    "41:01",
    "41:02",
    "41:05",
    "41:06",
    "41:08",
    "41:09",
    "41:11",
    "41:13",
    "41:15",
    "41:16",
    "41:18",
    "41:20",
    "41:23",
    "41:25",
    "41:28",
    "41:29",
    "41:31",
    "41:33",
    "41:34",
    "41:36",
    "41:37",
    "41:38",
    "41:40",
    "41:42",
    "41:46",
    "41:49",
    "41:49",
    "41:53",
    "41:56",
    "41:57",
    "41:59",
    "42:00",
    "42:03",
    "42:04",
    "42:07",
    "42:07",
    "42:09",
    "42:11",
    "42:13",
    "42:14",
    "42:17",
    "42:21",
    "42:24",
    "42:26",
    "42:28",
    "42:29",
    "42:31",
    "42:32",
    "42:34",
    "42:36",
    "42:37",
    "42:39",
    "42:40",
    "42:42",
    "42:43",
    "42:45",
    "42:47",
    "42:49",
    "42:51",
    "42:55",
    "42:56",
    "42:58",
    "43:02",
    "43:03",
    "43:05",
    "43:06",
    "43:09",
    "43:11",
    "43:12",
    "43:15",
    "43:18",
    "43:20",
    "43:22",
    "43:24",
    "43:25",
    "43:27",
    "43:28",
    "43:30",
    "43:31",
    "43:33",
    "43:35",
    "43:37",
    "43:38",
    "43:41",
    "43:43",
    "43:44",
    "43:46",
    "43:47",
    "43:49",
    "43:52",
    "43:55",
    "43:58",
    "44:00",
    "44:00",
    "44:02",
    "44:04",
    "44:07",
    "44:08",
    "44:12",
    "44:15",
    "44:18",
    "44:20",
    "44:22",
    "44:24",
    "44:26",
    "44:28",
    "44:30",
    "44:31",
    "44:33",
    "44:36",
    "44:38",
    "44:39",
    "44:41",
    "44:43",
    "44:45",
    "44:47",
    "44:47",
    "44:49",
    "44:51",
    "44:52",
    "44:54",
    "44:58",
    "45:00",
    "45:01",
    "45:03",
    "45:06",
    "45:10",
    "45:13",
    "45:14",
    "45:17",
    "45:18",
    "45:20",
    "45:22",
    "45:22",
    "45:26",
    "45:27",
    "45:29",
    "45:31",
    "45:34",
    "45:36",
    "45:38",
    "45:41",
    "45:42",
    "45:45",
    "45:48",
    "45:49",
    "45:54",
    "45:57",
    "45:57",
    "45:59",
    "46:00",
    "46:02",
    "46:03",
    "46:07",
    "46:09",
    "46:12",
    "46:15",
    "46:18",
    "46:18",
    "46:22",
    "46:26",
    "46:29",
    "46:31",
    "46:33",
    "46:35",
    "46:37",
    "46:40",
    "46:41",
    "46:43",
    "46:45",
    "46:47",
    "46:49",
    "46:50",
    "46:53",
    "46:55",
    "46:56",
    "47:00",
    "47:02",
    "47:04",
    "47:08",
    "47:10",
    "47:13",
    "47:14",
    "47:16",
    "47:18",
    "47:21",
    "47:23",
    "47:25",
    "47:26",
    "47:29",
    "47:29",
    "47:31",
    "47:33",
    "47:35",
    "47:37",
    "47:38",
    "47:41",
    "47:43",
    "47:46",
    "47:50",
    "47:53",
    "47:55",
    "47:58",
    "48:02",
    "48:04",
    "48:06",
    "48:09",
    "48:11",
    "48:14",
    "48:16",
    "48:18",
    "48:20",
    "48:22",
    "48:24",
    "48:28",
    "48:30",
    "48:32",
    "48:34",
    "48:36",
    "48:40",
    "48:42",
    "48:43",
    "48:46",
    "48:47",
    "48:48",
    "48:51",
    "48:53",
    "48:54",
    "48:57",
    "48:59",
    "49:02",
    "49:05",
    "49:05",
    "49:08",
    "49:09",
    "49:11",
    "49:12",
    "49:14",
    "49:17",
    "49:19",
    "49:21",
    "49:23",
    "49:25",
    "49:28",
    "49:29",
    "49:32",
    "49:36",
    "49:38",
    "49:39",
    "49:41",
    "49:42",
    "49:45",
    "49:47",
    "49:48",
    "49:52",
    "49:54",
    "49:57",
    "49:59",
    "50:02",
    "50:06",
    "50:07",
    "50:09",
    "50:10",
    "50:13",
    "50:13",
    "50:17",
    "50:20",
    "50:22",
    "50:24",
    "50:27",
    "50:29",
    "50:31",
    "50:32",
    "50:34",
    "50:37",
    "50:39",
    "50:42",
    "50:44",
    "50:46",
    "50:49",
    "50:51",
    "50:53",
    "50:55",
    "50:56",
    "50:58",
    "50:59",
    "51:01",
    "51:05",
    "51:06",
    "51:08",
    "51:10",
    "51:12",
    "51:15",
    "51:17",
    "51:19",
    "51:20",
    "51:22",
    "51:24",
    "51:26",
    "51:28",
    "51:30",
    "51:32",
    "51:36",
    "51:38",
    "51:40",
    "51:42",
    "51:43",
    "51:45",
    "51:46",
    "51:48",
    "51:50",
    "51:52",
    "51:53",
    "51:56",
    "51:57",
    "51:58",
    "52:00",
    "52:03",
    "52:04",
    "52:06",
    "52:08",
    "52:11",
    "52:14",
    "52:14",
    "52:17",
    "52:18",
    "52:19",
    "52:21",
    "52:23",
    "52:25",
    "52:27",
    "52:28",
    "52:31",
    "52:33",
    "52:35",
    "52:38",
    "52:39",
    "52:41",
    "52:42",
    "52:45",
    "52:46",
    "52:48",
    "52:50",
    "52:52",
    "52:55",
    "52:57",
    "53:00",
    "53:02",
    "53:04",
    "53:05",
    "53:07",
    "53:08",
    "53:11",
    "53:13",
    "53:14",
    "53:17",
    "53:19",
    "53:21",
    "53:23",
    "53:25",
    "53:28",
    "53:28",
    "53:31",
    "53:35",
    "53:39",
    "53:42",
    "53:44",
    "53:47",
    "53:48",
    "53:50",
    "53:53",
    "53:56",
    "53:57",
    "54:02",
    "54:05",
    "54:07",
    "54:10",
    "54:12",
    "54:14",
    "54:16",
    "54:18",
    "54:21",
    "54:22",
    "54:25",
    "54:27",
    "54:30",
    "54:32",
    "54:35",
    "54:36",
    "54:38",
    "54:41",
    "54:42",
    "54:43",
    "54:46",
    "54:48",
    "54:50",
    "54:53",
    "54:56",
    "55:00",
    "55:01",
    "55:03",
    "55:05",
    "55:06",
    "55:08",
    "55:10",
    "55:12",
    "55:14",
    "55:16",
    "55:18",
    "55:19",
    "55:20",
    "55:22",
    "55:25",
    "55:27",
    "55:30",
    "55:32",
    "55:34",
    "55:35",
    "55:37",
    "55:39",
    "55:41",
    "55:43",
    "55:45",
    "55:47",
    "55:49",
    "55:51",
    "55:53",
    "55:55",
    "55:58",
    "56:02",
    "56:03",
    "56:04",
    "56:06",
    "56:08",
    "56:09",
    "56:10",
    "56:14",
    "56:16",
    "56:18",
    "56:20",
    "56:23",
    "56:24",
    "56:27",
    "56:29",
    "56:30",
    "56:33",
    "56:37",
    "56:40",
    "56:40",
    "56:45",
    "56:47",
    "56:49",
    "56:51",
    "56:52",
    "56:55",
    "56:56",
    "56:59",
    "57:00",
    "57:03",
    "57:05",
    "57:06",
    "57:09",
    "57:12",
    "57:13",
    "57:14",
    "57:17",
    "57:19",
    "57:20",
    "57:23",
    "57:25",
    "57:26",
    "57:29",
    "57:31",
    "57:32",
    "57:34",
    "57:36",
    "57:37",
    "57:41",
    "57:44",
    "57:46",
    "57:48",
    "57:51",
    "57:52",
    "57:54",
    "57:58",
    "58:00",
    "58:02",
    "58:03",
    "58:05",
    "58:07",
    "58:10",
    "58:14",
    "58:15",
    "58:16",
    "58:18",
    "58:20",
    "58:22",
    "58:24",
    "58:25",
    "58:27",
    "58:28",
    "58:30",
    "58:31",
    "58:33",
    "58:36",
    "58:40",
    "58:42",
    "58:43",
    "58:45",
    "58:46",
    "58:49",
    "58:50",
    "58:53",
    "58:54",
    "59:00",
    "59:02",
    "59:04",
    "59:07",
    "59:09",
    "59:11",
    "59:13",
    "59:15",
    "59:19",
    "59:24",
    "59:25",
    "59:35",
    "59:37",
    "59:38",
    "59:40",
    "59:42",
    "59:44",
    "59:46",
    "59:47",
    "59:50",
    "59:51",
    "59:53",
    "59:54",
    "59:56",
    "59:57",
    "59:59",
    "60:00",
    "60:03",
    "60:04",
    "60:08",
    "60:10",
    "60:12",
    "60:14",
    "60:16",
    "60:18",
    "60:19",
    "60:22",
    "60:24",
    "60:26",
    "60:29",
    "60:32",
    "60:34",
    "60:36",
    "60:38",
    "60:40",
    "60:42",
    "60:45",
    "60:45",
    "60:47",
    "60:49",
    "60:52",
    "60:55",
    "60:56",
    "60:58",
    "60:59",
    "61:02",
    "61:02",
    "61:05",
    "61:06",
    "61:09",
    "61:09",
    "61:12",
    "61:14",
    "61:15",
    "61:15",
    "61:17",
    "61:19",
    "61:22",
    "61:24",
    "61:27",
    "61:28",
    "61:30",
    "61:32",
    "61:35",
    "61:38",
    "61:43",
    "61:46",
    "61:48",
    "61:49",
    "61:53",
    "61:55",
    "61:56",
    "61:58",
    "62:00",
    "62:02",
    "62:03",
    "62:05",
    "62:07",
    "62:12",
    "62:13",
    "62:16",
    "62:17",
    "62:21",
    "62:23",
    "62:25",
    "62:28",
    "62:29",
    "62:31",
    "62:33",
    "62:35",
    "62:53",
    "63:13"
  ],
  "transcripts": [
    "[Music]",
    "[Music]",
    "[Laughter]",
    "[Music]",
    "[Music]",
    "[Music]",
    "afternoon everyone",
    "we are reporting 3500",
    "new cases today this is by far the",
    "highest number of cases we've ever seen",
    "uh during the entire pandemic in fact",
    "it's about 700 cases more than our",
    "previous high which was just a few days",
    "ago",
    "viruses raging throughout the state of",
    "ohio",
    "there's no place to hide we now only",
    "have two counties that are yellow",
    "and they represent only one-fifth of one",
    "percent of our state's total population",
    "so every county is red or orange",
    "only five of our counties are not high",
    "incident counties so 83 of our 88",
    "counties are",
    "high incident counties",
    "since there is no place to hide all of",
    "us",
    "together have to come together to fight",
    "this enemy",
    "we have to come together to fight this",
    "invader",
    "we have tools to beat this virus back",
    "and we've learned a lot during the",
    "pandemic",
    "the tools are very simple is more people",
    "wear a mask",
    "more people keeping distance washing our",
    "hands",
    "good ventilation when we're inside",
    "we got to get back to fundamentals we",
    "got to get back to the basics",
    "i am today calling on the leaders of",
    "each",
    "county each community throughout the",
    "state of ohio",
    "to come together to create a coveted",
    "defense team this coveted",
    "defense team that we are asking every",
    "community",
    "to form is really what we need",
    "to fight back it should certainly",
    "include",
    "the county commissioners mayors",
    "local hospital leaders certainly the",
    "health commissioner",
    "business leaders religious leaders and",
    "other",
    "local leaders it should be in each",
    "county representative",
    "of the community i am asking the coveted",
    "defense team in each of our counties",
    "to assess and understand their situation",
    "to inventory their assets in the",
    "community",
    "and to focus on what steps to take to",
    "turn the situation",
    "in their community around",
    "because we now know what works",
    "to fight the virus a major part of their",
    "job will be to explain",
    "to people in the community exactly what",
    "is going on",
    "in the community the state of the virus",
    "what's going on in their local hospitals",
    "and what steps must be taken",
    "to slow this advance of the virus",
    "and my team in the last three days and i",
    "have been doing",
    "our zoom calls starting with",
    "the counties that were high incidence",
    "counties and now we've moved to the",
    "counties that are the highest",
    "number of cases in the last two weeks we",
    "will continue",
    "to work down that list",
    "i think that these calls",
    "from my perspective have been extremely",
    "productive",
    "each county has committed to expanding",
    "their working group",
    "to include more people they have each",
    "committed",
    "to meet at least once a week",
    "and they have each one a specific goal",
    "reducing the active new cases",
    "that are coming in each day",
    "and i just want to say i've been so very",
    "very impressed",
    "by the leadership in these counties so",
    "far we have met",
    "with the leaders some of the leaders in",
    "clark county cuyahoga county",
    "hamilton county mercer allen",
    "putnam all glaze and this morning holmes",
    "county",
    "we will start again tomorrow morning",
    "with more counties but we asked the",
    "counties",
    "not to wait for us not to wait for",
    "us to schedule the call",
    "it will take a few days of course for us",
    "to get through all 88 counties but we",
    "ask people to go ahead",
    "schedule your own meeting put your own",
    "local leaders",
    "together as one of the leaders",
    "said to me yesterday if a tornado hit",
    "our county",
    "and he said has hit our county he said",
    "everybody rallied together",
    "we came out to help friends we came out",
    "even if we didn't know the people that's",
    "what we're asking communities to do",
    "again",
    "ohioans are great about this",
    "i remember a few years ago a lot of",
    "floods along the ohio river i was just",
    "so impressed",
    "uh that how many people came out to help",
    "their neighbors",
    "same way when tornadoes hit people come",
    "out",
    "this is a crisis that is is grave",
    "certainly and much more widespread",
    "than those crisis so despite the",
    "grim data that we see today",
    "that we'll show you in a moment",
    "i'm optimistic because ohioans",
    "have the tools we know what works",
    "we always rally when we need to rally",
    "and i'm confident that people will do",
    "that",
    "when people see a threat particularly to",
    "their families",
    "to their neighbors to their community",
    "they come together",
    "we can in fact slow down uh this invader",
    "the decisions each ohioans make each day",
    "will really determine what kind of",
    "winter",
    "that we have we must mass more",
    "we must distance more we must be more",
    "careful",
    "we must wash our hands more we must have",
    "more ventilation",
    "inside particularly as we move more",
    "inside",
    "as winter approaches we can",
    "control our own destiny",
    "eric let's look at the numbers as you",
    "will see",
    "um today we have as i said",
    "set another record as we report 3590",
    "cases",
    "uh this is the first time we've",
    "surpassed 3 000 daily",
    "cases per day to put that in perspective",
    "today's new cases",
    "our figure is about 25 higher than the",
    "second highest date which we reported",
    "just last saturday",
    "it's not only the case numbers though",
    "that are increasing",
    "we also have 192 new hospitalizations",
    "reported in the past 24 hours",
    "this is the third highest we have ever",
    "reported",
    "the top five highest new hospitalization",
    "numbers have all occurred in the past",
    "week and a half so we continue to",
    "to be very high let's look uh eric at",
    "the next slide",
    "this is all 88 counties reported",
    "by highest occurrence starting putnam",
    "all the way down during",
    "what you see here in the blue of course",
    "are these the high incident counties",
    "so as i said before 83 of our 88",
    "counties are",
    "high incident counties again this is",
    "what",
    "the federal government how the federal",
    "government",
    "determines it a hundred cases in two",
    "weeks",
    "based on 100 000 population",
    "uh let's go to the next slide again this",
    "this again tells us",
    "um we have putnam county at nine times",
    "the",
    "um high incident level all glaze about",
    "about five times homes about five times",
    "and",
    "just all the way down you can see these",
    "top these top counties",
    "uh the bottom of this 20 the 20th",
    "green county it's about three times the",
    "high incidence so we're seeing this in",
    "mid-sized counties we're seeing in small",
    "counties",
    "and we're seeing increases in our urban",
    "counties as",
    "well let's turn to the alert system",
    "uh we're seeing no counties uh go purple",
    "that is the one bright spot and i'll",
    "talk about that",
    "in in a moment uh we no longer have a",
    "purple we don't have any purple counties",
    "and no",
    "counties on our watch list",
    "however this virus is spreading as you",
    "can see significantly",
    "throughout the state so we're down now",
    "just to",
    "two counties eastern side of our state",
    "that are yellow",
    "everything else is red or orange and",
    "just shows the gravity of this",
    "spread today we have 43 red counties",
    "only two yellow counties",
    "this is the highest number of red",
    "counties lowest number of yellow",
    "counties we have seen to date",
    "our new red counties ashtabula all glaze",
    "clermont defiance and trumbull this is",
    "an increase of five counties from last",
    "week",
    "and two actually you know all glaze are",
    "red for the first time",
    "this week 78 percent of ohioans are",
    "living in a red county",
    "78 of ohioans are living in a red county",
    "less than one percent as i said are",
    "living in a",
    "in a yellow yellow county",
    "now let me talk for a moment about the",
    "three counties",
    "that drop from the watch list to red",
    "um",
    "our system is designed",
    "to something the county goes to purple",
    "it has to continue to accelerate it has",
    "to continue to go up",
    "what we've seen with",
    "clark county and hamilton basically is",
    "that they plateaued or did not see a",
    "significant",
    "increase and not a significant enough",
    "increase to move to the purple level",
    "but we're still seeing with these",
    "counties very",
    "very disturbing trends as i said our",
    "alert system is designed to flag",
    "indicators that are getting worse",
    "what we're seeing is these three",
    "counties have plateaued at high levels",
    "in cuyahoga county outpatient emergency",
    "visits are in an elevated plateau",
    "hospital missions have been increasing",
    "clark county emergency visits and",
    "hospital missions have plateaued an",
    "elevated level",
    "outpatient visits are still high",
    "hamilton county outpatient visits and",
    "hospital missions are an elevated",
    "plateau but cases continue",
    "to go up",
    "during the past month the average age of",
    "cases uh in cuyahoga county the age of",
    "the individuals uh in qatar clark and",
    "hamilton counties has moved from people",
    "in their early 40s to people in their",
    "late 40s so we'll continue to see",
    "an increase in the age or the average",
    "age if you recall back in june july when",
    "we saw that",
    "in significant increase that was really",
    "led by a younger",
    "by a younger younger group",
    "in quahog and hamilton county's cases",
    "continue to rise steadily and",
    "hospitalizations remain elevated",
    "clark county local health department",
    "officials told us today they're seeing",
    "alarming increases they have recorded",
    "271 cases during the past seven days 271",
    "during the past seven days",
    "hospitalizations are at a record high",
    "and they've had 41 deaths",
    "41 deaths in clark county in october",
    "their previous high for deaths was 17 in",
    "august",
    "[Music]",
    "what we see in these counties is similar",
    "to what we're seeing in the rest of the",
    "state case numbers are continuing to go",
    "up",
    "healthcare utilization is trending",
    "upward",
    "we've been sharing stories uh about",
    "where we see",
    "spread and i talk to the health",
    "directors every",
    "every monday morning and they share some",
    "stories with me they also share some",
    "stories",
    "with our staff",
    "a high school football team had 13",
    "players with kova 19.",
    "a couple of players were infected spread",
    "it to the other members of the team",
    "the spread mainly happened at informal",
    "gatherings of the team",
    "where there were more interactions than",
    "there should have been",
    "these were not regular team functions so",
    "again this is similar to what we're",
    "seeing",
    "in the adult world where it's not as",
    "much in",
    "you know look there's spread everywhere",
    "and but most businesses we're not seeing",
    "much spread",
    "uh same way with with schools but we're",
    "really seeing",
    "uh the spread is just the the personal",
    "interactions the more informal",
    "settings",
    "another example we learned about an",
    "outbreak among staff at a doctor's",
    "office",
    "as a result of non-compliance not worry",
    "mask",
    "staff members at the doctor's office",
    "were either not wearing masks or",
    "not wearing them correctly finally we",
    "learned about a funeral at the end of",
    "september that now has 19",
    "cases 19 individuals who have covered",
    "associated with that funeral",
    "17 of the cases were identified with a",
    "funeral in two cases where secondary",
    "spread one of the points we discussed",
    "on our call in holmes county this",
    "morning",
    "was that most things we can do um",
    "you know fran i've been to three",
    "funerals that were that were safe",
    "uh uh certainly as far as we could",
    "observe everything was done right",
    "um you know weddings can occur many",
    "things",
    "we can continue to do but it's just how",
    "we go about it",
    "that we have to be have to be careful",
    "about",
    "i spoke with hamilton county leaders",
    "yesterday and",
    "on that zoom conference meeting",
    "we heard from dr rick lofgren about what",
    "they're seeing",
    "in the hospitals in the region dr",
    "lofgren",
    "has been on here before he's a zone lead",
    "for the southwestern ohio region of her",
    "pandemic response team he's president",
    "ceo of uc health the university of",
    "cincinnati's affiliated healthcare",
    "system",
    "he also is an internal medicine",
    "physician who has also worked",
    "in kentucky wisconsin pennsylvania",
    "minnesota and michigan during the span",
    "of his career",
    "doctor thank you very much for being",
    "with us again appreciate it",
    "thank you governor and i appreciate",
    "having an opportunity",
    "to speak you know as you mentioned we",
    "have seen a decisive increase in the",
    "number of covet 19 cases",
    "and an increase in hospitalization in",
    "our region",
    "you know we did a great job as ohioans",
    "suppressing the spread of this virus",
    "through the summer and into the early",
    "part of the fall",
    "we were opening up our activities and i",
    "like",
    "and really what we were seeing at that",
    "time is really the opportunity or the",
    "scene across our community sort of hot",
    "spots was a facility or an area a",
    "specific group",
    "that we were seeing some cases we were",
    "able to get resources around that and",
    "actually bring it down",
    "however the last three weeks as you",
    "mentioned we've seen a rapid increase",
    "in the number of cases and",
    "hospitalizations that's been nearly",
    "doubling every two weeks",
    "and it to the hospitalization at a level",
    "like we've never seen before",
    "and i think that one of the things",
    "that's really notable i think is that",
    "unlike what we saw before this spread is",
    "diffuse",
    "there's no one particular area no one",
    "particular group or facility",
    "that really accounts for the increased",
    "number of cases i might also say that we",
    "used to see much more in the",
    "highly dense urban core that's not the",
    "case anymore we see it up in the suburbs",
    "and in the",
    "in the entire area and as you mentioned",
    "before we're also seeing a",
    "increase in our positivity rate in all",
    "the different age groups",
    "you know not that many weeks ago our",
    "positivity rate",
    "in hamilton county and in the various",
    "age groups is right around three percent",
    "for right now we are seeing positivity",
    "rates in every one of our age groups",
    "somewhere between five and six and a",
    "half percent all of which has really",
    "happened in the last",
    "three weeks you know our as you",
    "mentioned i think our businesses have",
    "really done a nice job of of adhering to",
    "safety guidelines and keeping the work",
    "environment",
    "safe and our schools have done i think a",
    "remarkable job",
    "as you said before is that they really",
    "have had really remarkably few",
    "positive cases as we adhere to those",
    "standards that we know work",
    "we know what keeps this virus on at bay",
    "it's there if you let your guard down it",
    "spreads",
    "and so it really appears that the vast",
    "majority of the spread is really",
    "occurring in",
    "private social events i think we're",
    "simply letting our guard down",
    "we all have cove fatigue",
    "we but we know it works you know and",
    "i think we're starting to see people",
    "expanding their bubble",
    "um you know you need to ensure that",
    "there's a small category of people who",
    "you live with",
    "but we all are social animals we want to",
    "increase our bubble and i think people",
    "are",
    "sort of letting their guard down and in",
    "some respects",
    "um sort of believe that well if i know",
    "you and you're a friend of mine",
    "you know i can let you in my bubble and",
    "you're really not at risk",
    "where in fact we need to recognize that",
    "if we expand our bubble",
    "you're increasing your risk at any given",
    "point in time we don't know who amongst",
    "us",
    "may be actually infected without",
    "symptoms and inadvertently spirit",
    "spreading the virus",
    "and so that we need to go recognize",
    "particularly as we start to go indoors",
    "because before we can do some of these",
    "social events outside",
    "that we really need to maintain those",
    "steps that we know to work",
    "when you're going to increase your",
    "bubble having somebody into your home",
    "you need to maintain the social",
    "distancing",
    "and you need to wear a mask you know you",
    "need to recognize that anybody who's",
    "new into your environment may",
    "potentially be infected",
    "i think this is going to be a particular",
    "challenge as we start to think about the",
    "holidays",
    "we're all going to be delighted to see",
    "some relatives and friends that we",
    "haven't seen before but we need to",
    "understand",
    "that way which we celebrate has to",
    "change you know",
    "in that if you're going to bring people",
    "in your into your environment you have",
    "to maintain social distancing you have",
    "to",
    "maintain uh the masking and all those",
    "things that we know that work",
    "and are effective as we move forward um",
    "so sometimes i get asked about testing",
    "before events and it's certainly nice to",
    "know whether or not you are",
    "negative before an event but it's also",
    "not a reassuring assurance",
    "you know i could be tested today and be",
    "negative and then be cook",
    "be percolating the virus within me",
    "go into somebody's bubble and",
    "inadvertently spread the virus",
    "so i think the message to our community",
    "and to each other into ohio",
    "is that we've learned a lot in the last",
    "six months we've learned what's",
    "effective in terms of keeping this",
    "the virus under control we really have",
    "seen our organizations and our community",
    "responding in the businesses",
    "and the things that they're doing in the",
    "schools",
    "and as you mentioned the football story",
    "it's not the formal events where we take",
    "these measures where we're seeing the",
    "spread",
    "it's the informal events that happen",
    "that we really start to let our guard",
    "down",
    "so i think one of the messages that i",
    "think is important as we see",
    "this marked uptick throughout our",
    "community is that we really need to",
    "recommit",
    "and understand that we need to maintain",
    "our exposure and our bubble we have a",
    "small cadre of nuclear people that we",
    "live with",
    "and we realize that anybody else who",
    "comes into it we just need to",
    "treat them like even a stranger keep",
    "your distance",
    "wear your mask wash your hands and",
    "sanitize your environments",
    "doctor thank you very much we appreciate",
    "all you're doing and",
    "thanks for that summation of what where",
    "we are today",
    "thank you very much we appreciate it",
    "it goes without saying that the pandemic",
    "has changed",
    "all of our daily routines but for",
    "children with",
    "developmental disabilities these changes",
    "can be extremely disruptive",
    "to their learning and to their",
    "development many children can struggle",
    "with remote learning",
    "but children with ieps are often also",
    "losing needed in-person support",
    "such as individualized instruction",
    "behavioral support",
    "occupational therapy to assist children",
    "families with ieps who are",
    "doing remote learning we are launching",
    "learning",
    "aid ohio a supplemental tutoring program",
    "starting on monday eligible families can",
    "apply for up to fifteen hundred dollars",
    "in grant funding",
    "to cover costs of tutoring and other",
    "needed supports",
    "to apply for a grant or to sign up as a",
    "provider visit",
    "learningohio.comlearningohio.com",
    "ready for questions our first question",
    "today is from laura hancock",
    "at cleveland.com",
    "hi governor hello hi um",
    "my question is um you've you've pointed",
    "out some anecdotal data",
    "about like the football party um",
    "football teams and formal parties but",
    "how can you say",
    "that this ongoing surge stems from",
    "private informal gatherings among family",
    "and friends",
    "the actual types of events where contact",
    "tracing is easier",
    "than other places such as bars when you",
    "have no empirical data to back that up",
    "have you made any kind of renewed effort",
    "to find out",
    "other than just tweaking last week from",
    "the contact tracing system",
    "yeah i mean we're going to we're trying",
    "to get better",
    "better data the old system was not",
    "designed the system is not designed to",
    "drill down on in a pandemic to find out",
    "where the spread is",
    "so i think we explained last week",
    "exactly",
    "you know what what we have we have",
    "antidotal notes",
    "that are coming in from tracers and so",
    "we're going to try to",
    "bring about some consistency but even",
    "then",
    "even then let's say",
    "someone has got the virus",
    "you're on the phone with them the tracer",
    "is on the phone with them",
    "and they say i was in a bar uh one night",
    "he was in a restaurant the next night",
    "i was at work today i was here here here",
    "here so all that person would write down",
    "is all those different things and you",
    "still are not going to know",
    "where they got it so you know unless",
    "it's a big super spreader event",
    "many many times it is impossible to know",
    "for",
    "sure but what",
    "we rely on is some of this what we're",
    "hearing",
    "from the health directors they are the",
    "ones that are out there 113",
    "different different organizations out",
    "there",
    "they're the ones who are monitoring and",
    "watching it every day",
    "this is what they tell me because i'm",
    "not out there",
    "i'm not making the calls dr lofgren",
    "uh what he just said",
    "which was the same thing and",
    "other doctors are telling us that as",
    "well doctors who are treating covert",
    "patients are telling us",
    "this is where we are seeing the spread",
    "this is what they're telling me",
    "so we're never gonna please don't",
    "misunderstand what i'm saying i'm not",
    "saying there's not spread in",
    "workplace i'm not saying there's not",
    "spread in schools i'm not saying there's",
    "not spread in bars",
    "but what i am saying is",
    "a big component part of this",
    "according to everybody who is dealing",
    "with it every single day",
    "front line people they are describing",
    "these informal",
    "get-togethers and these informal events",
    "and the big spreader",
    "the big big spreader ones",
    "funerals weddings big get-togethers um",
    "you know that's what we're that's what",
    "we're seeing so all we're trying to do",
    "all i'm trying to do for the people of",
    "ohio is report what we're hearing",
    "as we talk to the people who are on the",
    "front line",
    "next question is from ben schwartz at",
    "wcpo in cincinnati",
    "hey ben hi governor um with this",
    "kovid defense team that you're calling",
    "on community leaders to create",
    "what do you expect to see from it and",
    "have you thought about the next steps",
    "if this defense team is not able to",
    "control the spread of the virus",
    "yeah i mean look this then this is one",
    "more thing that we think is is important",
    "now",
    "some communities are already have this",
    "they may not call it that",
    "uh you know different communities are at",
    "different stages",
    "of battling back but my experience in",
    "life",
    "has been in my experience in politics",
    "and government in ohio",
    "is things happen at the local level",
    "and somebody at the local level",
    "who might not think they should wear a",
    "mask",
    "is a lot more likely to listen to a",
    "neighbor than they are to me",
    "uh or to they are to dr fauci or they",
    "are to the lieutenant governor or",
    "or or our health director so you know",
    "engaging people in the local community",
    "um",
    "and one thing that you know we've tried",
    "to do on these calls so far and we're",
    "just",
    "you know not too far into these calls",
    "but",
    "um you know a lot of communities are",
    "doing a good job",
    "we try if that community has a hospital",
    "uh you know we want to get that that",
    "head of the hospital or some",
    "representative of the hospital",
    "in that call because they can really",
    "give a good indication",
    "here's what we are seeing in real time",
    "that's coming into our hospital",
    "and you know while we do not want to",
    "imply to anyone that our hospitals are",
    "overflowing",
    "because they're not but the hospitals",
    "can give you a good good read and",
    "they're all seeing",
    "an increase in what you know what is",
    "coming in or basically most of them are",
    "so pulling those people together to be",
    "communicators to the community",
    "pulling those people together to say hey",
    "do we have a problem in the nursing home",
    "with",
    "not enough ppe okay let's go call dewine",
    "let's go call the",
    "the governor's office let's call the the",
    "health department if we've got a problem",
    "here a problem there",
    "you know that's how we we see this group",
    "and as i said different counties are at",
    "different levels some are some are up",
    "here some are here",
    "but all everybody we've talked to so far",
    "wants to help wants to be involved and",
    "so this is not not magic we're not",
    "saying this is going to solve the",
    "problem",
    "but we can't win this we can't push back",
    "the virus unless we're all engaged",
    "you got to do it next question is from",
    "jim otte at whio in dayton",
    "hey jim hey governor good afternoon",
    "given the numbers out today",
    "and the steady increase that we've seen",
    "over the last couple of weeks what's",
    "your prescription whether it's you or",
    "the doctor prescription for families",
    "who still insist they're on the uh still",
    "planning on having a hollywood",
    "uh a halloween get-together this weekend",
    "the weather's going to be terrible",
    "outside",
    "so they're going to have this halloween",
    "gathering inside",
    "despite what you've said in the past",
    "perhaps with the new numbers help",
    "convince them to do otherwise",
    "well halloween parties are fun but they",
    "make no sense this year",
    "we'll save it till next year um that's",
    "not what anybody wants to hear",
    "but look thanksgiving's got to be",
    "different christmas has got to be",
    "different",
    "uh we're already starting to think in",
    "our family how we're going to do it",
    "ohio's ohioans you know",
    "are resourceful we'll figure out how to",
    "do these things but",
    "it's everywhere as dr lofgren said and",
    "the difference today is used to have hot",
    "spots you say okay here's a problem",
    "here's a problem here's a problem",
    "today you know it is just spread",
    "and you know it it's just",
    "it's everywhere and it is advancing at a",
    "very",
    "fast pace we've got to slow it down",
    "so we can't be doing things like",
    "halloween parties",
    "we could carefully do trick-or-treat if",
    "we're careful",
    "how we go about it you know we can do",
    "most things",
    "but we can't do them the way",
    "we've always done them in the past",
    "next question is from john reed at",
    "gangwar news service",
    "good afternoon governor there have been",
    "reports um around the country for months",
    "about people getting what",
    "they're calling long covid where they",
    "have symptoms serious symptoms for",
    "months",
    "um has the state collected any data on",
    "how many people in ohio have that and",
    "maybe",
    "for uh for the doctor if he's still on",
    "have we seen that what's the prevalence",
    "of that",
    "yeah i don't know if dr lofgren is still",
    "on uh eric or not",
    "to be available yeah i am um okay",
    "and i don't have those numbers right in",
    "front of me so i can't give you this",
    "percentages",
    "but this phenomena of what's being",
    "called long haulers is very real",
    "i think one of the things as we learn",
    "more about the virus",
    "is that the small percentage of people",
    "who get the virus even if they survive",
    "it",
    "has this an intense inflammatory",
    "response it's the inflammation",
    "that it triggers that can cause a lot of",
    "of ongoing problems",
    "including the the infection of the heart",
    "called myocarditis kidney problems",
    "in in inflammation of other organs",
    "and there's definitely a cadre of",
    "individuals who",
    "six nine months plus later still have",
    "problems with fatigue",
    "low grade fevers and recovering and",
    "speaking to my colleagues around the",
    "country this is enough of a",
    "of a ongoing phenomena that people are",
    "starting their what they call",
    "long-haul or clinics where they're",
    "really getting people together to really",
    "help support them",
    "uh through this recovery period so",
    "it's not always a very simple recovery",
    "it isn't a",
    "large number of people but there are",
    "definitely cadre of people who really",
    "manifest ongoing symptoms for months",
    "later um",
    "and we need to know a lot more about it",
    "and",
    "unfortunately i don't have a percentage",
    "about it it's it's not common but it's",
    "it's definitely a phenomenon and doctor",
    "is it my understanding that we really",
    "don't know",
    "why some people react that way and why",
    "some people",
    "don't or most people don't yeah you know",
    "one of the things i've i've said is that",
    "since the on the introduction this virus",
    "in this community we've learned a lot",
    "and we have a lot more to learn um and",
    "so i think that",
    "the science and my colleagues the",
    "research are doing is phenomenal but",
    "you know it really is um unclear why",
    "somebody will have an infection and",
    "really not have any problems whatsoever",
    "and another group of individuals will",
    "have this intense inflammatory response",
    "that can be",
    "caused multiple organs to damage it up",
    "to and causing death",
    "um so we've gotten some more insights",
    "into it but there's a whole lot more to",
    "learn",
    "good thank you doctor thank you",
    "next question is from jack windsor at",
    "wmfd in mansfield",
    "hey jack hi governor um",
    "since it's clear that even though cases",
    "have increased 400 percent",
    "uh there has been an uptick",
    "uh in in actually i think you just said",
    "not an uptick in covet hospitalizations",
    "um we continue to see uh hospital",
    "utilization drop overall",
    "over the past two weeks inpatient bed",
    "occupancy dropped from 71 to 67",
    "icu from 66 to 63 and then ventilator",
    "usage is about flat",
    "is this evidence that our health care",
    "system is not at risk",
    "and as deaths are not increasing that we",
    "need to continue to restore freedoms",
    "get people back to working on site and",
    "kids back into school buildings full",
    "um it appears that it's fear at this",
    "point it's killing our businesses and",
    "people more than the virus",
    "well let's let's go with the facts i",
    "mean we know uh",
    "i'm gonna have dr lofgren again to",
    "comment about what they're seeing in",
    "cincinnati but",
    "um you know we know that the number of",
    "people in the hospital",
    "today is double",
    "people in the hospital from covet is",
    "double what it was",
    "three four weeks ago dr lofgren you want",
    "to address that what you're",
    "actually seeing in the cincinnati region",
    "yeah thank you um just as you said i",
    "think that",
    "one of the things that i really look at",
    "frequently to really understand the",
    "burden of the disease",
    "on our community is really the number of",
    "people not infected but also affected to",
    "the point that they require to be",
    "hospitalized",
    "and we have seen a decisive increase in",
    "the number of individuals",
    "in our community who have been",
    "hospitalized in our region in the latter",
    "part of september we had about 90 people",
    "in the hospital who were head covered",
    "today we have i think it's about 260",
    "individuals who are hospitalized in our",
    "in our hospitals um we've also",
    "recently seen a real uptick in icu as",
    "well",
    "um you know one of the things i do think",
    "is the case is then",
    "is that we are more effective in",
    "treating the infection we know a lot",
    "more about how to treat patients now",
    "than we did six months ago so i do think",
    "that we're doing a better job in terms",
    "of",
    "uh preventing them to really to prevent",
    "some of the progression",
    "definite uptick in in terms of",
    "hospitalizations definite uptick in",
    "utilization",
    "within our region you know we are",
    "able to accommodate the current volume",
    "of patients but if they were to",
    "continue to double or triple from that",
    "number you know it will start to squeeze",
    "out non-covalent care",
    "thank you next question is from marty",
    "schlayton at the ohio capitol journal",
    "governor how are you today i'm good sir",
    "um",
    "as you've outlined i think that most",
    "people agree that the numbers look",
    "really grim and uh you know last week",
    "you",
    "said that this idea that just because",
    "we're doing more testing that's the",
    "reason we're seeing more cases is just",
    "nuts but like you just said to my",
    "previous question earlier let's go to",
    "the facts uh",
    "donald trump's one of the people who's",
    "out there saying that",
    "the reason we got more positive cases is",
    "because we're doing more testing",
    "he went to circleville and uh said that",
    "the media will stop reporting on",
    "coronavirus on november 4th and he",
    "jokingly talked about going out in the",
    "crowd and",
    "kissing everybody and so you know we're",
    "right before election day and i wanted",
    "to ask you",
    "who do you think is better suited to",
    "deal with this uh coronavirus problem",
    "donald trump or joe biden",
    "oh a good political questions though",
    "look",
    "i i i said this yesterday um",
    "on tv i was on but",
    "look i think the president has not",
    "gotten enough credit for what he's done",
    "in regard",
    "to making a decision very very early to",
    "invest",
    "real big money uh into the drug",
    "companies",
    "for them to do the research that they",
    "needed to do",
    "we don't know when that's coming but we",
    "hope it's coming",
    "soon and that i think will make a huge",
    "huge difference you know if you look at",
    "the cases",
    "we are testing more there's absolutely",
    "no doubt about it look at the numbers",
    "from yesterday",
    "even before they fill in they fill in",
    "for the next few days",
    "as it keeps coming in but you know fifty",
    "thousand tests",
    "uh now look i'd love to double the",
    "testing i'd love to have it a hundred",
    "thousand",
    "but uh at you know fifty thousand",
    "certainly we've been able to",
    "increase the average testing that we're",
    "doing in the state of ohio",
    "so testing in and of itself will",
    "increase cases",
    "but uh it's not nearly uh",
    "you know the increase we're seeing in",
    "positive cases",
    "does not is not caused solely by the",
    "increase in just",
    "testing and the way we can tell that is",
    "the positivity number",
    "you know normally when we started off",
    "and we were only testing we say oh we're",
    "only going to test you",
    "if you have symptoms well you know",
    "we got away from that and so we've said",
    "we're going to basically test anybody",
    "today which is the right thing to do in",
    "my opinion and we made that decision",
    "several months ago",
    "so when you go from only testing",
    "positive",
    "excuse me only testing people who have",
    "symptoms",
    "um you know obviously the numbers are",
    "going to be higher there",
    "but what we're doing now is you know",
    "throwing that net",
    "in a much broader group and the numbers",
    "positivity numbers should be coming down",
    "they haven't been coming down they've",
    "been going up they went from two and a",
    "half i think",
    "i looked today number the last number i",
    "saw is 6.9 for one day",
    "or 6.8 or 6.9 for one day and that's a",
    "far cry from two two and a half percent",
    "so the positivity numbers should be",
    "going down",
    "instead they're going up like a rocket",
    "every day so",
    "it's not you know that's not why we're",
    "seeing more",
    "more more more positive cases",
    "next question is from justin dennis at",
    "mahoningmatters.com",
    "the governor uh thanks as always for",
    "keeping us informed",
    "you begged for mass squaring earlier",
    "this week and last week",
    "and today we've now far surpassed a",
    "state record of new cases",
    "last week you said quote government",
    "cannot mandate unless we're in china",
    "or some totalitarian state but we have",
    "seat belt laws we have no smoking laws",
    "and the enhanced gun penalty laws you",
    "want less about enforcement and more",
    "about changing behavior",
    "uh you said last week quote it's time to",
    "get serious so my question is why can't",
    "you",
    "and the ohio legislature get serious and",
    "approve a law to mandate mask",
    "enforcement in public",
    "who lacks the will to get that done you",
    "or the legislature",
    "well you'd have to ask the legislature i",
    "think you have a",
    "pretty good idea the answer to that",
    "question that question",
    "look ohioans have been able to",
    "dramatically increase mass warring and",
    "we saw this",
    "back in july when we put we have a",
    "statewide",
    "let me just say it very clearly we have",
    "a statewide mass order on if you're out",
    "in public",
    "you need to have a mask on now we do not",
    "have a mass",
    "police and we've had some police",
    "departments that obviously don't want to",
    "enforce that health department's overrun",
    "with work and really not in a position",
    "to do that so we rely",
    "on the goodwill of the people of the",
    "state of ohio",
    "as we rely frankly on them for most",
    "compliance with with regulations or most",
    "laws",
    "and so we saw a dramatic increase",
    "in mass wearing in july in our urban",
    "areas",
    "and it went from we we don't know",
    "exactly but",
    "it would appear it went from something",
    "in the 50 percent",
    "somewhere in the 90 85 90",
    "and when we saw that we saw cases go",
    "down we can do this again",
    "um and that is the most effective",
    "the most efficient and frankly the only",
    "way",
    "uh that we're going to see uh",
    "knock this these number of cases down",
    "we've got to see more masks worrying and",
    "ohioans have proven they can do it",
    "before",
    "we don't have the ability uh to have a",
    "mass police",
    "everywhere and you know we rely on",
    "the goodwill the people of ohio and i",
    "think the more people learn about the",
    "more we learn about",
    "the power of these masks and what masks",
    "have done in the past and i think as",
    "people see",
    "community by community what is",
    "doing and will be doing to their",
    "community i think we're going to see",
    "mass compliance and wearing go up",
    "next question is from joe ingles at ohio",
    "public radio and television",
    "good afternoon governor um about",
    "election day you've said that",
    "local police will respond first to",
    "polling places if there are",
    "problems and then the national guard",
    "could go in",
    "but potential problems can happen",
    "quickly on election day",
    "so and we've heard a lot of problems",
    "lately",
    "with um people's tempers getting out of",
    "line",
    "over politics we we have numerous",
    "examples of that",
    "you put a lot of people together on",
    "election day in a line that could be",
    "problematic",
    "so is the response enough",
    "and is it going to be fast enough to",
    "actually deal with problems at the polls",
    "on tuesday",
    "well we have a long history in this",
    "country",
    "uh of having fair and free",
    "elections and peaceful elections",
    "we've done it for over 200 years we've",
    "done it exceedingly well",
    "um are there people out there that might",
    "want to disrupt something yeah sure",
    "i mean we know that um 6 30 this morning",
    "i was on a conference call",
    "with our team with the national guard",
    "the highway patrol",
    "and others just kind of going over what",
    "what we know",
    "and what plans that we have",
    "according to the ohio revised code the",
    "sheriffs have a unique role",
    "a unique role if there is a problem",
    "inside inside",
    "the flag area",
    "the local if there's something outside",
    "the flag area then of course the",
    "the depending on where that is if it's",
    "out in the county then it's the sheriff",
    "it's",
    "if it's the municipality village city",
    "uh then it's up to the local police",
    "department so they're they",
    "they would be the first responders but",
    "you know we're all tied in",
    "uh with communication and",
    "you know we basically have a war room",
    "and",
    "if we need to do things we will we will",
    "do them",
    "uh but you know the first line of",
    "defense is a local government state the",
    "first line of defense",
    "is the local police local sheriff",
    "we have the highway patrol to back up we",
    "also have the national guard",
    "and so again the national guard is",
    "limited by federal law",
    "into what they correctly into what they",
    "can do",
    "uh particularly around elections but uh",
    "you know i we are ready um",
    "and we do not you know we have a long",
    "history",
    "of running good elections in this",
    "country in this state",
    "and i think people you know should have",
    "confidence they can go to the polls they",
    "can have confidence they can go",
    "and to board elections today or",
    "you know they can continue they can vote",
    "by absentee ballot",
    "next question is from jeff redick at",
    "wsyx in columbus",
    "jeff afternoon governor um it was just",
    "looking over",
    "some of the numbers for example the",
    "testing",
    "is approaching the highest positivity",
    "rate",
    "since i believe july 16th",
    "still on quite an upward trajectory",
    "um and you've talked about that there's",
    "no sign of a plateau",
    "in sight you talk about the goals for",
    "mask wearing and things some people do",
    "like to",
    "very seriously look at the numbers for",
    "themselves so what would signal a",
    "plateau what are we shooting for",
    "numbers-wise that shows that a plateau",
    "is coming",
    "well i think plateau by definition is",
    "means you stop going up",
    "and you're not going down um you know we",
    "had a plateau in cases for quite a",
    "period of time around a thousand cases a",
    "day but we didn't like it having a",
    "thousand a day",
    "but at least it wasn't going up so i",
    "think that's a minimum what i've",
    "challenged the counties to do",
    "um as i said we started in these",
    "conference calls we've been having we",
    "started with the high the most high",
    "highest incident counties and we said",
    "look",
    "set a goal to knock these numbers down",
    "and start taking start taking them down",
    "so that uh you know when you look at",
    "them every several days",
    "those numbers in the last two weeks are",
    "going down",
    "there's no reason uh the county that's",
    "at 500",
    "you know five times the the high",
    "incident level the cdc there's no reason",
    "that by good adherence to",
    "to good practice and getting back to",
    "fundamentals and putting masks on",
    "you know if you if you if a county goes",
    "from 30",
    "wearing mass to 60 i will guarantee you",
    "those",
    "those cases will start down and we've",
    "just seen it time after time so",
    "i think every county i'll set a goal and",
    "say look here's",
    "what what do we think we can do and the",
    "goal should not be to plateau",
    "of course the goal should be to start",
    "taking those taking those numbers down",
    "and we know what works this is not",
    "rocket science",
    "this is not difficult you know we know",
    "what works we just got to do it",
    "and i think trying to look at",
    "88 counties one at a time and local",
    "community",
    "getting directly involved and as i say",
    "many of them",
    "have great leadership they've been",
    "directly involved but every county being",
    "involved in every county having a group",
    "that is that is fighting i think is the",
    "way to knock this down",
    "or at least one of the ways to knock it",
    "down next question",
    "jackie borchardt at the cincinnati",
    "inquirer",
    "good afternoon governor um you mentioned",
    "the other day that",
    "if we keep on this trajectory things",
    "might shut down on their own",
    "businesses will close schools will close",
    "um",
    "there's no stimulus or extra",
    "unemployment compensation in sight",
    "are we prepared to support ohioans",
    "through this third and greatest surge",
    "and what is your plan for ensuring that",
    "safety net is there this winter",
    "well as you know we put out five billion",
    "dollars yesterday as i'm absolutely",
    "unprecedented",
    "uh going out to businesses all over the",
    "state of ohio",
    "to help keep them open in some cases",
    "you know they decide how to spend the",
    "money but um",
    "keep people working uh so that five",
    "billion dollars we think is important",
    "uh doesn't solve certainly solve every",
    "problem uh i'm optimistic",
    "that uh congress will after this",
    "election in a lame duck session come up",
    "with",
    "an additional bill to help um",
    "but you know the the best way for us",
    "to help people economically",
    "is for this state to keep working",
    "and the biggest threat to work the",
    "biggest threat to being in school",
    "is the virus i've talked to",
    "superintendents in the last week",
    "who have had to pull back for a week",
    "two weeks a few days because of the",
    "virus",
    "and so an understanding",
    "all of us understanding that the safety",
    "of my grandmother a grandmother in",
    "a nursing home depends on keeping the",
    "community spread down",
    "the ability to keep that school open",
    "depends on that as well",
    "and the ability to go into a hospital",
    "and be treated as you can today for a",
    "heart attack or",
    "whatever the medical problem is you know",
    "our hospitals are not overflowing",
    "they're open but that it",
    "would be threatened if this spike",
    "continues to go up and at some point",
    "you'll start seeing hospitals saying we",
    "can't do electric surgeries",
    "we can't do this we can't do that so a",
    "lot of this will simply happen",
    "organically",
    "if these cases continue to go up and we",
    "continue to see hospitalizations go up",
    "and we continue to see",
    "deaths next question is from kevin",
    "anders at wbns in columbus",
    "well governor judging by today's cases",
    "it seems",
    "very clear that the masked message isn't",
    "working i know it worked in the past but",
    "it doesn't seem to be working now and",
    "i'm wondering if the message",
    "is getting muddled because we don't have",
    "a health director directly speaking to",
    "the people of ohio",
    "every day about this serious issue it",
    "seems like the state's strategy now is",
    "to",
    "sort of hope for a vaccine and we all",
    "know that hope is not a plan",
    "so what more have you thought about that",
    "you can do have we run out of ideas what",
    "is the strategy moving forward",
    "thank you yeah i mean our what we",
    "started to do this week some of you",
    "reported",
    "you know as a new plan i didn't look at",
    "it quite like that but that was",
    "that's fine uh you know was was really",
    "drilling down",
    "county by county and as we have these",
    "calls",
    "you know sometimes we're finding hey",
    "somebody needs this",
    "health department needs this nursing",
    "home needs this",
    "so but really it is about getting",
    "neighbors friends leaders in that",
    "community",
    "saying hey we don't want our county",
    "ripped apart",
    "we don't want our lives ripped apart we",
    "want to keep our kids in school we want",
    "to keep working",
    "and so giving that that support",
    "um i think you know will in fact make a",
    "difference it's one more thing one more",
    "thing that we can certainly",
    "certainly do so uh look we're going to",
    "continue to",
    "um look at different things that we",
    "might be able to do or that we can do",
    "and we're going to",
    "we're going to do those but",
    "you know so much of this comes down to",
    "what people do in their own individual",
    "lives",
    "where government cannot really interfere",
    "and unless you're in a totalitarian",
    "state",
    "and i don't think we want to be in a",
    "totalitarian state",
    "so it is people of good will coming",
    "together understanding the facts and",
    "taking action to save their own lives",
    "lives of family members in their",
    "community",
    "governor next question is the last",
    "question today and belongs to farnucha",
    "miri of the associated press",
    "hi governor um so with the number of",
    "cases rising",
    "at an alarming rate that you outlined",
    "here today there's a concern among",
    "voters about showing up to the bulls",
    "both on election day",
    "and in the days leading up to it um what",
    "would you tell voters concerned about",
    "the infection",
    "rate in ohio yeah yeah i mean i think i",
    "think if you feel that you can go to the",
    "grocery store you ought to be able to",
    "feel you can go to vote",
    "what i think i would do is try to",
    "determine",
    "you know what is the time of day",
    "that um the least crowd will be there",
    "um that's what i would if i had just you",
    "know if i had the discretion",
    "uh you know if you could pick a time",
    "let's say someone is retired and they",
    "want to vote in person",
    "they can certainly do that it looks like",
    "maybe over half the people in the state",
    "who are going to vote will have voted by",
    "election day",
    "so that means when you walk into your",
    "precinct",
    "or precincts where some precincts may be",
    "are together you know those are the only",
    "people are going to be coming to that",
    "polling place",
    "so i know we're seeing a lot of long",
    "lines with boards of elections but",
    "that's only one polling place in the",
    "whole county and i'm not discouraging",
    "people from going",
    "today tomorrow any this weekend that's",
    "great",
    "but if people want to wait until",
    "election day you're going to have",
    "already half the people voted",
    "and so there's going to be fewer people",
    "but i think being careful wearing a mask",
    "you know keeping a distance if there is",
    "a line standing back",
    "respecting where that other person is",
    "get in and vote",
    "and leave you know i think that is you",
    "know just as safe as",
    "is going to a grocery store and and some",
    "of the other things that you know people",
    "do",
    "so we end today i want to introduce you",
    "to an ohioan who is one of our",
    "state's heroes of hope",
    "master sergeant smith is one of 60 ohio",
    "national guard and ohio military reserve",
    "members who are helping with cobia 19",
    "testing around ohio",
    "which since june they've done in 151",
    "sites to find a site near you go to",
    "coronavirus.ohio.gov",
    "and let's take a look at the video",
    "are you doing today i'm master sergeant",
    "josh smith i",
    "work as a speech therapist at the",
    "beginning of the year",
    "uh but with the pandemic heading i ended",
    "up starting work as a nurse",
    "based off of the training that i got in",
    "the air force and then in may i was",
    "activated",
    "to work and do this covid testing for",
    "the national guard",
    "the 10 seconds each nostril with the",
    "guard we have",
    "people who are all throughout the",
    "community",
    "all walks of life we have people who",
    "work in construction we have",
    "your nurses your emts students at osu",
    "all coming together putting down their",
    "current life",
    "to come and help out their communities",
    "help out their neighbors",
    "they're raising their hand to work with",
    "the guard to help",
    "out when they're most needed so results",
    "take about two to four business days",
    "i've traveled to all corners of the",
    "state from toledo down to portsmouth",
    "we're here in cincinnati today i've been",
    "as far east as gallipolis",
    "been all over the state doing testing we",
    "put in long hours",
    "we often say that we're making the best",
    "out of a bad situation",
    "we're all reacting to large amounts of",
    "stress",
    "constantly changing environment and i'm",
    "seeing a positive attitude",
    "every city town and village i've been in",
    "it's been heartening seeing how much",
    "everybody",
    "has risen to the occasion not just the",
    "members of the military but",
    "our community partners local health",
    "boards",
    "even the private businesses have come",
    "together with us",
    "and it's worked as one large team rather",
    "than",
    "dozens of disjointed and fantastic if",
    "you do have a positive result you'll be",
    "getting a call from the health",
    "department",
    "this has been probably one of the most",
    "exhausting",
    "stressful and rewarding moments of my",
    "career in the guard",
    "to be able to say that i raised my hand",
    "and said",
    "i will help when ohio needed me the most",
    "i can say i was there",
    "and i helped i did my duty for my state",
    "i am definitely proud to be here in ohio",
    "all right have a good day",
    "we want to thank our heroes of hope",
    "members of the national guard who've",
    "done such a great job with",
    "taking testing to many many communities",
    "around the state we'll close with a",
    "quote from",
    "three-time presidential candidate",
    "unsuccessful",
    "but three-time presidential candidate",
    "william jennings bryan",
    "and i think it's appropriate to and the",
    "challenges that we're facing",
    "uh today destiny is not a matter of",
    "chance",
    "it's a matter of choice it's not a thing",
    "to be waited for",
    "it's a thing to be achieved end of quote",
    "tuesday is election day we will not have",
    "a press conference on",
    "on tuesday a regular scheduled press",
    "conference will be thursday unless there",
    "is some",
    "breaking news and some reason that we",
    "need to have a press conference before",
    "next thursday thank you very much",
    "[Music]",
    "um"
  ]
}